### ISSUE TITLE
第二回全体ミーティングを開催します！

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#10]
松江Ruby会議07の第二回全体ミーティングを開催したいと思います！

| 日時 | 場所 |
| --- | --- |
| 7月6日（月）19:00〜21:00 | オープンソースラボ |

当日は以下の内容について皆様に報告と相談をしたいと思います。
## 報告事項
- 企画について（企画内容・タイムテーブル他）
- 懇親会・昼食LTについて
- スポンサーについて
## 相談事項
- 基調講演の内容について
- ゲスト講演の内容について
- スペシャル企画について
- Tシャツについて

一応、以下のDoorkeeperから参加登録をお願いします。

https://matsue-rb.doorkeeper.jp/events/27627

**Comment by Takashi-U** [comment]
乙でございました。
私、連続で欠席になってしまって申し訳ないです。第３回ミーティングは、なるべく参加したいと思っています。いつ頃予定ですか？
（第３回のIssue作ってCloseかなと。。）

**Comment by sho-h** [comment]
他には議事録などですかね。以下にやっていただいていますね。どもです！
- [議事録](https://github.com/matsuerb/matrk/wiki/07_00-第二回ミーティング（議事録）)
- [プログラミングコンテストについて](https://github.com/matsuerb/matrk/wiki/07_プログラミングコンテストについて-powerd-by-paiza)

**Comment by yoshiokaCB** [comment]
次回のミーティングは今のところ7月末 - 8月頭を想定中。

ちょっと今週末に現状の整理をするので、そこから次のミーティングで何の協議が必要で何を準備しないといけないのか考えます。

それから第三回ミーティングのissueを作りますね。

**Comment by kenjiSugihara** [comment]
全体MTGマターではありませんが、備忘録としてコメントのっけときます！

9月26日、RubyWorld Conferenceのルーター5機、借用OKです（一畑江角さん）。

**Comment by yoshiokaCB** [comment]
第二回のミーティングは終了してますので、クローズします。
何かこの件で問題があれば、別にissueを作りたいと思います。
