### ISSUE TITLE
地域Ruby会議写真展の選別

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk#102]
以下があるので応募する。

* http://25.ruby.or.jp/rk_photos.html

**Comment by sho-h** [comment]
それぞれで何枚か選ぶ事になると思うけど、まずは過去の写真のURLをピックアップしてから考える。

* 08: まだなかった気がする @inoh さんから直接もらうのがいいかも。
* 07: https://www.flickr.com/groups/2901550@N22/
* 06: 以下。
    * https://www.flickr.com/groups/2875305@N22/pool/
    * https://www.flickr.com/groups/2860565@N21/pool/
    * https://www.flickr.com/groups/2819938@N24/pool/
    * https://www.flickr.com/groups/2813862@N25/pool/
    * https://www.flickr.com/groups/2863519@N23/pool/
    * https://www.flickr.com/groups/2886121@N22/pool/
    * https://www.flickr.com/groups/2823956@N23/pool/
    * https://www.flickr.com/groups/2849741@N23/pool/
    * https://www.flickr.com/groups/2886131@N22/pool/
* 05: 見当たらないけど、[役割](https://github.com/matsuerb/matrk05/wiki/Roles)には2人載ってるので @tomo-k さんから直接貰うのがいいかも。なければ諦める感じの緩めで。
* 04: これ以前は見当たらないが20周年より前になってくるからいい気もする。

各個人が写ってるものを選ぶよりはそれぞれ集合写真に近いものなど人が多く写ってるもの、松江でのみ撮れそうなものを選んで合計10枚弱とか？。

**Comment by sho-h** [comment]
以降はslackででも。送付が済んだらcloseします。

**Comment by inoh** [comment]
@sho-h さん
返信できていませんでした。ごめんなさい。。
08 何か写真選定した方がよいですか？

**Comment by sho-h** [comment]
@inoh 遅くなりました...ありがとうございます！僕もあまり時間取れてないのもあるのですが集合写真だけ送ろうかと思いまして、いまのところ大丈夫そうです。

**Comment by inoh** [comment]
👍

**Comment by sho-h** [comment]
やはり集合写真だけになりました。送付までdone。
