### ISSUE TITLE
松江Ruby会議09のWebサイトの準備

### ISSUE THREAD

**Issue by sada** [matsuerb/matrk#103]
- [x] 松江Ruby会議08からコピー
- [x] 不要な項目を削除。
- [x] 目的を松江Ruby会議09のものに変更
- [x] 決定したタイムテーブルに修正
- [x] 松江Ruby会議08ように発表者の写真を表示するか確認

**Comment by sho-h** [comment]
以下みたいなのも毎回やってもらえるとありがたいかもです。今回まとめてjquery-latest.min.jsみたいなのにできれば一番嬉しいかもしれません(存在すれば)。最もアクセスがあるのは1年ほどなので、動かなくなる方が古いバージョンで放置するよりマシという考え方ですね。

* https://github.com/matsuerb/matsuerb-nanoc/pull/486

bootstrap.jsやholder.jsも更新した方がよければ併せて同じようにしてもらえるとありがたい感じです。

**Comment by sho-h** [comment]
あと、ホームをクリックした時にJavaScriptのエラーが(Safariだと)出てるので他のブラウザでも同じなら直してもらえるとこれもありがたい感じです。

**Comment by sada** [comment]
@yoshiokaCB 松江Ruby会議09のページ用のPRを作成しました。
タイムテーブルはまだ決定していませんが、GitHubのissueに書いてあったものを表示しています。

https://github.com/matsuerb/matrk/issues/105

このPRでは以下の情報が欲しいです。

* 松江Ruby会議08の目的のテキストのままなので、松江Ruby会議09の目的のテキスト。
* LTの募集用のテキストを表示しています。不要ならば削除。

https://github.com/matsuerb/matsuerb-nanoc/pull/494

以下の情報は、またPRを作成してページを更新することを考えています。

* 決定したタイムテーブル。
* 松江Ruby会議08のように発表者の写真を表示する場合は画像。
* スポンサーの情報とロゴ画像。
* Rubyクイズの賞品情報。

確認よろしくお願いします。

**Comment by sho-h** [comment]
> bootstrap.jsやholder.jsも更新した方がよければ併せて同じようにしてもらえるとありがたい感じです。

実際には使ってないダミーのpackage.jsonを置いて問題があるかわかるようにしましたので、開催準備機関中は以下に脆弱性があれば対応してもらえるとうれしいです。(自分以外に通知が来ないようならslackででも依賴します。現時点では特に警告はないです。

* jquery
* bootstrap
* holderjs

**Comment by yoshiokaCB** [comment]
@sada 

> 松江Ruby会議08の目的のテキストのままなので、松江Ruby会議09の目的のテキスト。

ちょっと別issueでみなさんにも確認してもらうので少々お待ちください。
（今週いっぱいで切る感じでもいいかな）

> LTの募集用のテキストを表示しています。不要ならば削除。

LTの募集はありでお願いします。
通常セッションの募集はなしでお願いします。

**Comment by yoshiokaCB** [comment]
@sada 

> 松江Ruby会議08の目的のテキストのままなので、松江Ruby会議09の目的のテキスト。

投げまんまですみません。
下記のissueの内容でお願いします。
#108

**Comment by sada** [comment]
松江Ruby会議09のサイトにissue作成時に考えていた必要な情報は掲載し終わったので、このissueは閉じます。何かある場合、別issueで対応します。
