### ISSUE TITLE
第二回ミーティングについて

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#104]
下記日程でミーティングを開催したいと思います。ご都合のつく方はご参加お願いします。

| 日時 | 場所 |
|----|----|
| 4/21（土） 午前11時〜 | オープンソースラボ |

基本的には進捗状況の共有になるかと思います。以下議題はおって作成します。

**Comment by tomo-k** [comment]
@yoshiokaCB 
https://github.com/matsuerb/matrk/wiki/09_00_02_%E7%AC%AC%E4%BA%8C%E5%9B%9E%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0
議題を作成しました

**Comment by yoshiokaCB** [comment]
議事録は下記をご確認ください。

* [議題](https://github.com/matsuerb/matrk/wiki/09_00_02_第二回ミーティング), [議事録](https://github.com/matsuerb/matrk/wiki/09_00_02_第二回ミーティング（議事録）)
