### ISSUE TITLE
当日のタイムスケジュールを決める

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#105]
以下、昨年のスケジュールを元にした案です。

| 時間 | プログラム |  |
| --- | --- | --- |
| 11:00 〜 11:05 | オープニング |  |
| 11:10 〜 11:55 | ゲスト講演 |  |
| 12:00 〜 13:30 | 昼食休憩 |  |
| 13:30 〜 14:20 | 基調講演 |  |
| 14:30 〜 14:45 | session 1 | 通常発表 |
| 14:45 〜 15:00 | session 2 | 通常発表 |
| 15:10 〜 15:25 | LTセッション | - |
| 15:30 〜 15:45 | session 3 | 通常発表 |
| 15:45 〜 16:00 | session 4 | 通常発表 |
| 16:00 〜 16:15 | session 5 | 通常発表 |
| 16:15 〜 17:00 | Rubyクイズ | - |
| 17:00 〜 17:10 | クロージング | - |

**Comment by sho-h** [comment]
closeしちゃいます。
