### ISSUE TITLE
基調講演の依頼をする

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#106]
取り急ぎ、基調講演を依頼しスケジュールが問題ないか確認する。

日時：6/30 13:30 -14:20 （50分程度）
場所：オープンソースラボ

また、githubとサイトに名前を掲載して良いか確認をする。

話していただく内容に関しては別のissueとする。

**Comment by sho-h** [comment]
時間等についてはまだですが、丁度今日のところで当日の予定がない事を確認しました。

**Comment by yoshiokaCB** [comment]
@sho-h 
おお！ありがとうございます！！

とりあえずスケジュールを空けいただける感じですかね？
一応次回ミーティング（4/21）の時に依頼内容（日時以外の話してもらう内容）を固めたいなと思っています。

**Comment by sho-h** [comment]
@yoshiokaCB はい。時間は後日お伝えする事になっていますが、当日は空けていただけるとの事です。

**Comment by yoshiokaCB** [comment]
@sho-h 
基調講演の依頼についてですが、下記のような感じでいかがでしょうか？
何か追記・修正がありましたらお願いします。

---

## 日時
6/30 13:30 - 14:20（50分程度）

## 講演内容 :

今回お聞きしたいお話は直接Ruby話ではなく、Rubyの周囲の話をお聞きしたいと思っています。
例えば、下記のような項目でお話ししていただけそうな内容をお聞きできればと思います。

- Rubyが影響を与えた言語のお話
- Rubyでこういう使い方をされるとは思ってなかったお話（ウイルス、JACSA関連）
- キーボードのお話
- 政府関係の会合に出席された時のお話
- エディターへのこだわりのお話
- メールチェッカーのお話
- ペットのお話

## 確認事項

- Githubと告知サイトに名前を掲載しても良いか確認
- 掲載用の所属、名前、タイトル（とりあえず仮でOK）の確認  
あと、写真を掲載する場合、昨年と同じさ写真を使用しても良いか。
http://matsue.rubyist.net/matrk08/img/matz.jpg

**Comment by sho-h** [comment]
具体例は抜いたのと、ペットのお話は抜いてお伝えしています。
