### ISSUE TITLE
企業協賛金

### ISSUE THREAD

**Issue by kenjiSugihara** [matsuerb/matrk#11]
現在の協賛金依頼書（案）は別途アップします！

・参加者見込み数を約８０名として、学生見込み数も別掲する
・イベントサイトのURLを
・企業ロゴは、JPEGでもよいが、サイズでかいのを
・領収書、請求書は、フリーソフトを利用
・口座は、橋本さんを予定
・決裁手続きをTPJ様（鶴原さん？）に確認する
・協賛金目標は、９社（９万円）
　→　学生補助@3,000円☓20人　＋　商品代3万円

**Comment by inoh** [comment]
[松江Ruby会議07-協賛募依頼書案.docx](https://github.com/matsuerb/matrk/files/543/Ruby.07-.docx)

**Comment by inoh** [comment]
[松江Ruby会議07-協賛募依頼書案.docx](https://github.com/matsuerb/matrk/files/544/Ruby.07-.docx)

**Comment by kenjiSugihara** [comment]
県内大手企業様にご確認をしました。
以下の手続きで特段の問題はない、とのことでした。
取り急ぎご報告です！

（以下）
１：事前に協賛企業候補代表者様にご相談をさせて頂く。
２：内諾を頂けたら、主催者より別添のような依頼書を送付する。
　　※依頼元印は、吉岡さんの個人印
３：協賛企業様より依頼書記載内容に基づき、協賛金のお申込みを頂く
４：主催者より、請求書をお送りする
　　※発行元は、実行委員長の吉岡さん（個人印を押印）
　　 また、振込先口座は、Matsue.rbの橋本さんの個人名口座
５：協賛企業様のお振込を確認次第、主催者より領収書を送付
　　※発行元は、実行委員長の吉岡さん（個人印を押印）
６：イベント後、主催者より開催報告・会計報告を協賛企業様に提出

**Comment by yoshiokaCB** [comment]
@kenjiSugihara さん
ちょっと確認です。
1. ゲストの昼食代と懇親会費用（5,000程度）
2. 会場の備品費用（2,000〜5,000円程度）

※もしかすると某Tシャツのスポンサー様（未定）、プログラミングコンテストのスポンサー様からそれぞれ1名（計2名）来場されると、その方の昼食・懇親会費用の負担は必要かと思います。（計10,000円程度）

上記も予算に入れておいた方が良いかと思います。
ただ、前回の繰越金がありますので、そちらを使っても構いません。また次回ミーティングで相談ですかね。

あと、協賛企業の方らからはLTに参加せれる場合は懇親会費用は別途必要としたいです、でよろしいでしょうか？（懇親会費用をこちらで負担すると計算がかなり狂うので。）

**Comment by kenjiSugihara** [comment]
yoshioka@tm-21.comさん、お返事が遅くなりました。
まず、LT参加企業の交流会参加費は、それぞれ負担でよいと思います。

今回の支出を予定するものは、
・会場借上費（松江市さんが負担）
・学生の交流会参加費補助（@3千円☓20名＝6万円）
・プロコン商品代（約2万円）
・ゲストの昼食代、懇親会費用（約5千円）
・会場の備品費用（約5千円）
・Tシャツスポンサー、プロコンスポンサーの昼食代、懇親会費用（約1万円）
って感じですかね？
漏れが在ればご指摘ください。

前回の繰越金を踏まえて、協賛金収入見込額を明確にする必要がありますね。
次回ミーティングを待たずに、整理しておきたいと思います！

予算書って、橋本さんがgoogleドライブにアップなさっているんでしたっけ？
であれば、しまった！
sugihara.shimane.pref@gmail.com
で僕も共有させて頂くと有難いっす！

**Comment by sho-h** [comment]
@kenjiSugihara さん、共有しました！07も上記ほど項目がしっかりしてないですが、ざっくりと作っています。内容はまた更新しますね。

**Comment by kenjiSugihara** [comment]
$BM-Fq$&$4$6$$$^$9!*(B
$BAaB.$KM=;;=q$rAG@2$i$7$$$G$9!#(B
$BKM$b>/$7<j$r2C$($F$b$h$$$G$7$g$&$+!)(B

iPhone$B$+$iAw?.(B

2015/07/09 12:48$B!"(BSho Hashimoto notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by sho-h** [comment]
@kenjiSugihara (ウェブで見ると化けてますがたぶん「修正しても良いかどうか」というご質問だと感じましたので、)はい。修正していただいて大丈夫です！

**Comment by kenjiSugihara** [comment]
@sho-h さん、超絶さすがです！その通りです！！

**Comment by yoshiokaCB** [comment]
@kenjiSugihara さん
ありがとうございます。
今、自分が把握してる限りでは漏れがありません。

**Comment by kenjiSugihara** [comment]
お疲れ様です！
ちなみに僕は疲れていません（正確に言えば、生まれてこのかた疲れたことがありません）。
橋本さんが作成されたスプレッドシートに07の収支予算書案を記載してみました。

橋本さんのご作成された内容を少し加筆した程度です。
詳細は今後相談ですね！
お時間のある時にご確認くださいませ〜

**Comment by yoshiokaCB** [comment]
@kenjiSugihara さん
ありがとうございます！
また後ほど確認しておきます！！

> ちなみに僕は疲れていません（正確に言えば、生まれてこのかた疲れたことがありません）。

自分、今日はヘロヘロっす(^^;;)
夕方までに元気にならねば！

**Comment by kenjiSugihara** [comment]
協賛依頼書（案）、営業先候補リストをアップします！

で、出来ない…

**Comment by yoshiokaCB** [comment]
最終的に11社集まりました！
ご協力していただいた皆さん、ありがとうございました！！
