### ISSUE TITLE
Rubyクイズの内容を決める

### ISSUE THREAD

**Issue by ToruKurahashi** [matsuerb/matrk#114]

**Comment by ToruKurahashi** [comment]
08からの転記（を編集）

# タスク（全体の流れ）

## 1. 冒頭の説明

### 流れ

- ２商品x２サイクル（負けても２回目に参加可能とする）
- １サイクル２５分（（問題 -> 説明）を５ターム -> ジャンケン -> 表彰）
- 各問題を解く時間は１分、説明は３分ぐらい。

### 注意事項

- スマホやPCをつかわない
- 正解したかどうかの判断は個人 => 良心に従って行動してほしい

## 2. タイムキーパー

- 問題を開始してから１分をカウントダウン
- カウントダウン的な動画があればサブスクリーンで表示
- カウントダウン時に流す音楽（著作権フリーのもの）

## 3. ナレーション

- その場をちょっと盛り上げる、なにかネタを言う。
- 事前に表示する問題のスライドを共有して、ナレーションを挟めそうなとこを考える。

## 4. プレゼントを渡す

- 残った人でジャンケン（人が多かったら、司会者とジャンケン）=> ２人？選出
- 提供企業さん（前の方に座ってもらう）に前に来てもらって、渡してもらうのを誘導。

## 5. 最後に解説URLを配布

**Comment by sho-h** [comment]
closeしちゃいます。
