### ISSUE TITLE
懇親会の企画をする

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#116]
懇親会で何かゲームをする。
景品は10個程度用意する。

**Comment by yoshiokaCB** [comment]
案1. ビンゴゲーム
https://itunes.apple.com/jp/app/%E3%81%B5%E3%81%A4%E3%81%86%E3%81%AE%E3%83%93%E3%83%B3%E3%82%B4-%E7%84%A1%E6%96%99%E3%81%AE%E3%83%91%E3%83%BC%E3%83%86%E3%82%A3%E3%83%BC%E3%82%B2%E3%83%BC%E3%83%A0/id1082797006?mt=8

**Comment by yoshiokaCB** [comment]
ビンゴカードは百均で購入する。

**Comment by sho-h** [comment]
closeしときます。
