### ISSUE TITLE
松江Ruby会議09 WEBサイトの情報追加

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#118]
- [x] 「内容」の追加（ゲスト講演、基調講演、スピーカー、LT）
- [x] LTの参加者を公式サイトに追加する。
- [x] スポンサーを掲載する。

**Comment by yoshiokaCB** [comment]
@sada 
すみませんが以下WEBサイトへの掲載お願いします。

## 1. 「内容」追加

下記を参考にh2で「内容」というタイトルで追加お願いできますか？（ゲスト講演、基調講演、スピーカー、LT）「内容」ってタイトルがおかしければ適当に直してもらってOKです。

https://github.com/matsuerb/matrk/wiki/09_01_%E6%A6%82%E8%A6%81#%E5%86%85%E5%AE%B9

## 2. 上記に合わせて「タイムテーブル」のLTの箇所に発表者の名前の掲載をお願いします。

## 3. スポンサーの掲載

現在、スポンサーは下記の3社になります。画像は昨年掲載した画像を利用して掲載をお願いします。

```

## スポンサー

### RubyQuizスポンサー
- エクスウェア株式会社
- 株式会社ネットワーク応用通信研究所
- ファーエンドテクノロジー株式会社
- 株式会社Misoca

### 懇親会スポンサー
- 株式会社イーストバック

```

注）RubyQuizスポンサーはあと2社追加予定です。

**Comment by yoshiokaCB** [comment]
スポンサーに ` ファーエンドテクノロジー株式会社 ` を追加でお願いします。

**Comment by yoshiokaCB** [comment]
RubyQuizのスポンサーに ` エクスウェア株式会社 ` を追加でお願いします。

**Comment by yoshiokaCB** [comment]
エクスウェア様のロゴはこちらを使用してください。

![35026701_2034168889990503_3678631371535810560_n](https://user-images.githubusercontent.com/4011289/41223025-97947748-6da3-11e8-8257-a2fddaa32ffe.png)

**Comment by sho-h** [comment]
遅くなりましたが、許可取りましたので基調講演の写真も追加お願いしますー。

**Comment by yoshiokaCB** [comment]
自分の方で作業します。

**Comment by sada** [comment]
@yoshiokaCB 申し訳ありません。よろしくお願いします。

**Comment by sho-h** [comment]
だいたい終わりですかね。closeしちゃいます。
