### ISSUE TITLE
togetterを作成する

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk#119]
#matrk09のtogetterを作成する。

**Comment by nishidayuya** [comment]
#122 のためにも便利なのでざっとまとめました． https://togetter.com/li/1243152

**Comment by sho-h** [comment]
おぉっ、ありがとうございます！ではcloseです！

**Comment by sho-h** [comment]
あ、https://gamelinks007.net/tags/matrk09 みたいなMastodonも含められるとよいかも...と思いましたけど、可能かわからないのでした(とりあえずcloseしたまま

**Comment by sho-h** [comment]
https://togetter.com/li/1181476 でできるかもしれません。掲載する許可はもらいました。いったんreopenします。

**Comment by nishidayuya** [comment]
おお，了解です．見てみます．

**Comment by sho-h** [comment]
お手数です。よろしくおねがいしますー。m(_ _)m

**Comment by nishidayuya** [comment]
遅くなりましたが，自分の環境（Google ChromeとFirefox）だと「もっと見る」ボタンが機能しなくてうまくいかないですね...

**Comment by sho-h** [comment]
じゃあ諦めますかねぇ。closeしますー。
