### ISSUE TITLE
レポート作成

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk#122]
以下に従ってレポートを作成する。

* https://github.com/matsuerb/matrk/wiki/09_03_役割#レポート担当

**Comment by sho-h** [comment]
まずはテンプレート作るので少々お待ち下さい。一旦橋本にアサインします。例年と違ってmarkdownになったはずなので少し確認に時間かかります。

**Comment by yoshiokaCB** [comment]
確認です。
レポートって橋下さんのテンプレート作成待ちで良かったですかね？

**Comment by sho-h** [comment]
です。もう少しお待ちください。

**Comment by sho-h** [comment]
遅くなりました。 https://github.com/sho-h/rubima/tree/matsue-rubykaigi09 にお願いします。
前回まではHikiフォーマットでしたけど今回からMarkdownです。
吉岡さんだけすみませんけど最後のあたりの「著者について」のところを追記してください。

あと、写真を選定しないとですねー。

**Comment by yoshiokaCB** [comment]
> 吉岡さんだけすみませんけど最後のあたりの「著者について」のところを追記してください。

ラジャー！

**Comment by nishidayuya** [comment]
> あと、写真を選定しないとですねー。

https://www.flickr.com/groups/4470994@N25/pool/ からお選びいただけます!

**Comment by sho-h** [comment]
>> あと、写真を選定しないとですねー。
> https://www.flickr.com/groups/4470994@N25/pool/ からお選びいただけます!

ありがとうございます！ @yoshiokaCB @tomo-k @sada 担当分は各自で選んでいただくとありがたいです！

**Comment by sho-h** [comment]
@tomo-k @nishidayuya @sada  slackでもお知らせしていますが8/12(日)が締め切りですので、その少し前にはそろうとありがたいです。(橋本もやっとですが半分ほど書きました。
多少は融通が効くみたいですので、難しそうなら教えてくださいませ。

**Comment by sada** [comment]
> slackでもお知らせしていますが8/12(日)が締め切りですので、その少し前にはそろうとありがたいです。(橋本もやっとですが半分ほど書きました。
> 多少は融通が効くみたいですので、難しそうなら教えてくださいませ。

以下のPRを作成しました。よろしくお願いします。

https://github.com/sho-h/rubima/pull/14

**Comment by nishidayuya** [comment]
書きました．

他，気づいたこととかもpull-request出しておきました．ご確認よろしくお願いします．

**Comment by sho-h** [comment]
どもでしたー。

**Comment by sho-h** [comment]
以下で公開されてる状態ですのでcloseします。

* https://magazine.rubyist.net/articles/0058/0058-MatsueRubyKaigi09Report.html
