### ISSUE TITLE
09の写真の公開

### ISSUE THREAD

**Issue by nishidayuya** [matsuerb/matrk#123]
予定地は https://www.flickr.com/groups/4470994@N25/

**Comment by nishidayuya** [comment]
* 漏れがないか確認した．
    * 6/30時点で全ファイルアップロードできていた．
    * 漏れがありそうと思ったのはソート順が「Date uploaded」になっていて極端に歯脱けがあるように見えたためだった．「Date taken」にしてから確認したところ手元と一致していた．
* 同じような絵で目をつぶった写真やピントが甘い写真は取り除いた．
* https://www.flickr.com/groups/4470994@N25/pool/ で確認できるよう，グループに「Add photo」した．

**Comment by sho-h** [comment]
closeでいいという事でしたのでcloseしますー。
