### ISSUE TITLE
公式サイトで開催のお知らせを公開する

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk#126]
こういうやつ。09はまだなかった。

* http://matsue.rubyist.net/news/2016/03/19/matsue-rubykaigi07/

**Comment by sho-h** [comment]
@amidaku 動画のURL、以下のみで良かったです？

* https://github.com/matsuerb/matsuerb-nanoc/pull/572/commits/ef13b628838fe33ad04b8c709d8ded6eea795ee6#diff-1d0af967572b2849b703389a3477e0bfR23

**Comment by amidaku** [comment]
あ、すみません。まだ上記URLのライブ録画だけです。
お正月に頑張ります。

**Comment by sho-h** [comment]
了解ですー。では今のところはこれにしてしまって、分けてもらったところで置き換えようかと。(1つリンクがあればとりあえずは急がないですー

**Comment by sho-h** [comment]
という事で一旦作成したのでclose。
