### ISSUE TITLE
Rubyの会で開催宣言をする 

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#132]
下記のリポジトリーのissueで概要をまとめて開催宣言する。
https://github.com/ruby-no-kai/official/issues

またはRubyのSlackで宣言する。

**Comment by yoshiokaCB** [comment]
@tomo-k 
開会宣言が終わったら（終わってましたら）宣言内容を書いてクローズしてください。
（すでに終わっているかもですが、次回以降の参考になるので残しておきましょう）

**Comment by tomo-k** [comment]
@yoshiokaCB 
この宣言だけでOK（ゲスト決まったのでのちのち連絡）という認識ですが合っていますか？
https://github.com/ruby-no-kai/official/issues/392

**Comment by yoshiokaCB** [comment]
@tomo-k 
それで大丈夫だと思います！

**Comment by tomo-k** [comment]
Matsue.rb の @tomo-kと申します。
第10回目となる 松江Ruby会議の開催を以下の要領にて計画しております。

名称：松江Ruby会議10
開催日：2020/06/06(土)
会場：松江オープンソースラボ
参加費：なし
配信：あり（URL未定）
定員: 60名程度
実行委員長：木村 友哉
るびまのレポート記事担当：佐田 明宏
会計 : 杉原 健司
サイト： http://matsue.rubyist.net/matrk10/ （準備中）

イベントにてお招きするゲストスピーカーへの交通費と宿泊費のご支援をお願いできないでしょうか。
昨年までの実績を元にした概算ですが、費用は以下ように考えております。

概算費用詳細
交通費：￥40,000 程度
宿泊費：￥16,000 程度（前泊が必要なため2泊分計上）
合計：￥56,000 程度

詳細が決まり次第、改めてご連絡させていただきます。
何卒よろしくお願いいたします。
