### ISSUE TITLE
レポート班の募集と人員配置

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk#14]
以下の作業を行う。
- 第3回のミーティングなどで募集(@sho-hを含めて4人〜8人)を行う
- matsuerb/matrk06#35 のように担当を決める

| 内容 | 発表者 | レポート担当 |
| --- | --- | --- |
| ゲスト講演 | まるやまさん | @nishidayuyaさん |
| 昼休憩 | ------ | ------ |
| 基調講演 | まつもとさん | @nobyuki さん |
| matsuerb.products(2014..2015) | Matsue.rb橋本 |  |
| タイトル検討中(活動内容に関するお話) | Sprout.rb松岡さん | @inohさん |
| プログラミングコンテスト結果紹介 |  | @sho-h |
| タイトル検討中(学校で使用しているシステムのアップデートについての話) | 藤井さん | @sadaさん |
| タイトル検討中(スモウルビーに関するお話) | プロ少高尾さん、本多さん | @sho-h |
| RubyQuiz |  | @tomo-kさん |

**Comment by sho-h** [comment]
@inohさん, @nishidayuyaさん、@sadaさん、@nobyukiさん、@tomo-kさんと僕の6名を考えてます(一人一人了解をとっている最中)。担当はまた別途考えようと思っています。

**Comment by sho-h** [comment]
上記の6人になりました。(時間的な制約以外では)たぶんみんなどれでもOKだと思いますので、近くにいる人からヒアリングして担当を埋めていきます。

**Comment by sho-h** [comment]
9/11のミーティングで@inohさんがいらっしゃるようなら、担当を相談しておきたい(というメモでした)

**Comment by sho-h** [comment]
@nobyuki 先生を基調講演担当にして僕を2つほど担当にしました。あとMatsue.rb枠をどなたか決めるのと、@nobyuki先生が問題なければおしまい。

**Comment by nobyuki** [comment]
上記、了解しました。問題ありません。
