### ISSUE TITLE
プログラミングコンテストで決めておくこと

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#15]
- [x] 残った時間を何のイベントに割り当てるか？（クイズ大会でよいか？）
- [x] コンテスト枠の時間
- [x] 受賞者人数および賞品（上位何名にするか？特別賞はどうするか？）
- [x] 問題の締め切り日（前日でよいか？片山さんと相談の上決める必要があるかも）
- [x] 解説をサポートする人、コメンテーターはどうするか？
- [x] 事前に内容チェックする人

**Comment by yoshiokaCB** [comment]
## コンテストの期間

9/1 - 9/24

## コンテストの流れ
1. paizaさんの説明
2. プログラミングの説明
3. 模範解答
4. 3位の発表
5. 2位の発表
6. 1位の発表
7. 全体の順位の発表
8. 特別の紹介

上位３人にコードの感想と工夫した点を話してもらう。

## コードチェック・コメンテーター

@sho-h @takaokouji @Takashi-U @yoshiokaCB

**Comment by yoshiokaCB** [comment]
一位に関しては賞品を決定し発注済みです。

二位以下に関しては、書籍を検討中。

**Comment by sho-h** [comment]
書籍について候補挙げて相談するとかでしたっけ。以下あたりを思いつきました。
- [メタプログラミングRuby第2版](https://www.oreilly.co.jp/catalog/soon.html)は間に合わなさそう...
- [Effective Ruby](http://magazine.rubyist.net/?0050-EffectiveRuby_ja)
- Ruby認定試験対策本/Rails認定試験対策本

**Comment by amidaku** [comment]
書籍について個人的に欲しい本と読んだことのある定番本を書きます。
皆さんがRuby的目線で書かれると思ったので、あえてRuby以外から。
- 暗号技術入門 第3版 秘密の国のアリス
  ISBN: 978-4797382228
- データサイエンティスト養成読本 機械学習入門編 (Software Design plus)
  ISBN: 978-4774176314
- ビジネスモデル・ジェネレーション ビジネスモデル設計書
  ISBN: 978-4798122977
- 体系的に学ぶ 安全なWebアプリケーションの作り方　脆弱性が生まれる原理と対策の実践
  ISBN: 978-4797361193
- たのしいバイナリの歩き方
  ISBN: 978-4774159188
- 実践 Metasploit ―ペネトレーションテストによる脆弱性評価
  ISBN: 978-4873115382

**Comment by sho-h** [comment]
データサイエンティスト養成読本 機械学習入門編 (Software Design plus)なんかは2000円くらいなので、Ruby徹底攻略 (WEB+DB PRESS plus)とかとセットにしてとかもいいかもしれませんね。

**Comment by yoshiokaCB** [comment]
自分は、以下の本が欲しい。
- [珠玉のプログラミング 本質を見抜いたアルゴリズムとデータ構造](http://www.amazon.co.jp/%E7%8F%A0%E7%8E%89%E3%81%AE%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0-%E6%9C%AC%E8%B3%AA%E3%82%92%E8%A6%8B%E6%8A%9C%E3%81%84%E3%81%9F%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0%E3%81%A8%E3%83%87%E3%83%BC%E3%82%BF%E6%A7%8B%E9%80%A0-Jon-Bentley/dp/4621066072)
- [リファクタリング:Rubyエディション](http://www.amazon.co.jp/%E3%83%AA%E3%83%95%E3%82%A1%E3%82%AF%E3%82%BF%E3%83%AA%E3%83%B3%E3%82%B0-Ruby%E3%82%A8%E3%83%87%E3%82%A3%E3%82%B7%E3%83%A7%E3%83%B3-Jay-Fields/dp/4048678841/ref=sr_1_1?s=books&ie=UTF8&qid=1442324429&sr=1-1&keywords=%E3%83%AA%E3%83%95%E3%82%A1%E3%82%AF%E3%82%BF%E3%83%AA%E3%83%B3%E3%82%B0+ruby)

あとは「Effective Ruby」と「データサイエンティスト養成読本 機械学習入門編 」は気になりますね！

一応注文の期間を考えて、今週を目処に決めたいと思います。

**Comment by sho-h** [comment]
リファクタリング:Rubyエディションは掲載されてるコードの多くが動かないらしいというのを聞いた事があるのでちょっとそこが気になりました。[検索してみる](https://www.google.co.jp/search?q=%E3%83%AA%E3%83%95%E3%82%A1%E3%82%AF%E3%82%BF%E3%83%AA%E3%83%B3%E3%82%B0:Ruby%E3%82%A8%E3%83%87%E3%82%A3%E3%82%B7%E3%83%A7%E3%83%B3%E3%80%80%E5%8B%95%E3%81%8B%E3%81%AA%E3%81%84)とやっぱりそんな感じですね。[書籍サイト？](http://index.ascii.jp/7018/)にerrataすら掲載されてないのでRubyエディションじゃない方にするのがいいかもしれません。

**Comment by yoshiokaCB** [comment]
なるほど。確かにそんなコメントがありますね。
言われるように、こっちの方がいいかもしれないですね。

[新装版 リファクタリング―既存のコードを安全に改善する― (OBJECT TECHNOLOGY SERIES)](http://www.amazon.co.jp/%E6%96%B0%E8%A3%85%E7%89%88-%E3%83%AA%E3%83%95%E3%82%A1%E3%82%AF%E3%82%BF%E3%83%AA%E3%83%B3%E3%82%B0%E2%80%95%E6%97%A2%E5%AD%98%E3%81%AE%E3%82%B3%E3%83%BC%E3%83%89%E3%82%92%E5%AE%89%E5%85%A8%E3%81%AB%E6%94%B9%E5%96%84%E3%81%99%E3%82%8B%E2%80%95-OBJECT-TECHNOLOGY-SERIES/dp/427405019X)

**Comment by sho-h** [comment]
コードチェック・コメンテーターですが、@nobyuki 先生が興味あるらしいです！

**Comment by nobyuki** [comment]
やりたいです！

**Comment by nobyuki** [comment]
賞品の件ですが、『[あなたの知らない超絶技巧プログラミングの世界](http://www.amazon.co.jp/gp/product/4774176435)』はぎりぎりイベント前日の発売だったんですね。
今回のコンテストはコードゴルフの様相を呈しているので、発売日に余裕があったらちょうど良い賞品だったんですけどね〜^^;

**Comment by amidaku** [comment]
どの本にするかって、どうやって決めます？

**Comment by yoshiokaCB** [comment]
おっし！
@nobyuki 選手、よろしくお願いいたします！（コメンテーター）
あとでissueを作りますが、前日（25日）の夜にコード確認しますので、予定を空けておいてください。

**Comment by yoshiokaCB** [comment]
そうですね。選考方法考えてなかったですね。
今のところ2票獲得してる、以下の２冊は決定でいいかと思っています。
- 「Effective Ruby」
- 「データサイエンティスト養成読本 機械学習入門編 」

あとは明日くらいまで待って金曜日に皆さんの意見を見て決めようかと思っています。もちろん上記に冊よりも欲しいという意見が多い本が出て来れば考え直します。金額によって3,4冊選びます。
（なければ独断で決めます。）

なので、ご意見あればお早めに！

**Comment by nobyuki** [comment]
> 前日（25日）の夜にコード確認しますので、予定を空けておいてください。

了解です。

あと、『[あなたの知らない超絶技巧プログラミングの世界](http://www.amazon.co.jp/gp/product/4774176435)』ですが、イベント当日までに確実に入手できる算段がつきましたので、賞品にできそうです(^0^)

サンプルコードもRubyが多いので（というかぱっと見では全てRuby）、ちょうど良いと思います。
ぜひ候補に加えてくださいませm(_ _)m
- [著者による紹介記事](http://d.hatena.ne.jp/ku-ma-me/)
- [書籍の公式ページ](http://gihyo.jp/book/2015/978-4-7741-7643-7)

**Comment by yoshiokaCB** [comment]
おお！
いいですね！！
間に合うかどうか、試しの意味も込めて、個人的にポチするとこでした(^^;;)

**Comment by yoshiokaCB** [comment]
特にご意見もないようなので、下記の3冊にしたいと思います。明日にでもポチします。
ご意見あれば今夜中にお願いします。
- 「Effective Ruby」
- 「データサイエンティスト養成読本 機械学習入門編 」
- 「 あなたの知らない超絶技巧プログラミングの世界」

あと、予算を確認してからですが、余裕がありそうだったら、 @sho-h さんのご意見を採用して「Ruby徹底攻略 (WEB+DB PRESS plus)」もセットに加えたいと思います。

**Comment by nobyuki** [comment]
「 あなたの知らない超絶技巧プログラミングの世界」ですが、本日の直前ミーティングの際に @yoshiokaCB さんにお渡ししたいと思います。

**Comment by yoshiokaCB** [comment]
ありがとうございます！
私の方も下記三冊ゲット済み
- 「Effective Ruby」
- 「データサイエンティスト養成読本 機械学習入門編 」
- 「Ruby徹底攻略 (WEB+DB PRESS plus)」

あと、「 あなたの知らない超絶技巧プログラミングの世界」は今井書店に発注済みです！
（連絡ないから今日は届かないかな。。。）

@sho-h さん、 @nobyuki さん
どちらにお聞きしたらよいかわかりませんが、特別賞としてサイン入りの書籍を準備する予定だったと思いますが、いかがでしょうか？
まぁ、なければないでどうにかします。

**Comment by amidaku** [comment]
えっと、ゲスト講演が弊社の技術顧問ですし、弊社社長も参加予定ですので、「入門Redmine」1冊献本することできますがいかがでしょう？
プロコンの商品に合わないようであれば遠慮させていただきますが。

**Comment by yoshiokaCB** [comment]
めっちゃ嬉しいです！
ぜひぜひお願いします！！

**Comment by amidaku** [comment]
では今日持って行きます。

**Comment by nobyuki** [comment]
サイン入りの書籍については、今日お会いできればサインをいただいておこうと思います。
今日お会いできなかったら、当日にサインをいただこうかなと思っています^^;

**Comment by yoshiokaCB** [comment]
ありがとうございます！
合う合わないはあるかもしれませんが、そこは受賞者の選択肢が多い方が良いと思うので(^^;;)

**Comment by yoshiokaCB** [comment]
@nobyuki さん
了解です。ありがとうございます！

**Comment by nobyuki** [comment]
@yoshiokaCB さん
先ほどサインをいただきました。こちらも今日お渡ししたいと思います。

**Comment by yoshiokaCB** [comment]
今日の話し合いで準備は終わったと思うのでクローズします。
