### ISSUE TITLE
sessionの発表者の募集

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#16]
現在依頼候補として
- Matsue.rb
- スプラウト.rb
- プログラミング少年団

が上がっております。

**Comment by Takashi-U** [comment]
公募のような事はお考えでしょうか？それとも、こちらからお願いする路線でしょうか？
公募であれば、早めの周知とWeb班との調整が必要かなと思いました。

**Comment by yoshiokaCB** [comment]
7/10にサイトを公開するのでそこで募集開始予定。
まぁ、他に宛てもあるので、埋まらなかったら個別にお願いしてまわります。

**Comment by yoshiokaCB** [comment]
Matsue.rb, スプラウト.rb, プログラミング少年団 の三団体の発表が決まりました。

**Comment by yoshiokaCB** [comment]
ビジ専の藤井さんが発表してくれることになりました。
よって07/29現在、発表者は以下のようになります。

| 発表内容 | 発表者 |
| --- | --- |
| 未定 | Matsue.rb（発表者未定） |
| 活動内容に関するお話 | スプラウト.rb（松岡さん） |
| スモウルビーに関するお話 | プログラミング少年団（高尾さん、本多さん） |
| 学校で使用しているシステムのアップデートについての話 | 藤井貴さん |

**Comment by sada** [comment]
「仕様」は「使用」の間違いでしょうか。

**Comment by yoshiokaCB** [comment]
@sada さん
ご指摘ありがとうございます。最近よく「仕様」って変換するのでPCが気を使ったみたいです。

**Comment by sada** [comment]
:thumbsup:

**Comment by inoh** [comment]
sessionの内容をそろそろホームページに反映しようと思います。
セッションの発表順は適当でよいです？

**Comment by yoshiokaCB** [comment]
はい。お願いします。
とりあえず、適当でOKです。
そういえば、後一人空きがあるので、発表者をボチボチ探さなきゃでした(^^;;)

**Comment by sho-h** [comment]
Matsue.rbの発表のタイトルは「matsuerb.products(2014..2015)」とかにしようかと思います。発表者は橋本将でお願いします。

**Comment by inoh** [comment]
@sho-h 
:+1:

**Comment by sho-h** [comment]
残りの1枠はクイズにしたので完了。(違ってたらreopenします)

**Comment by yoshiokaCB** [comment]
クイズ枠であってます！
