### ISSUE TITLE
懇親会備品について

### ISSUE THREAD

**Issue by sakasita001** [matsuerb/matrk#17]
懇親会で使う備品について、このイシューを使って管理しようと思います。
備品について、必要なものが今後追加されたり変更になった場合は更新以下の箇条書きを更新していきます。

懇親会で使う備品。
・マイク
・音響
~~・プロジェクタ~~
・タイムキープ用ベル(new)

会場にすでにあるものは
マイク（本数）
音響設備
50インチディスプレイ（PC入力可、形式は後日下見時に確認）

OSSラボからお借りしたいもの（松江市様に許可をいただきました。持ち出し、返却について打ち合わせが必要）
PC－ディスプレイ(HDMIオス)

個人からお借りするもの（借りる方）
現状無

**Comment by amidaku** [comment]
普通に「OSSラボから〜」とありますけど、自分たちの資産では無いので外に持ち出すことについて合意を得ておいてくださいね。
あと、懇親会後に返却しないといけないのでラボを解錠してもらう必要がありますよね。
このあたりも決めておく必要があると思いました。

**Comment by sakasita001** [comment]
承知いたしました。
文言修正させていただきます。
次回ミーティング時に個別で打ち合わせさせていただこうと思います。

**Comment by sho-h** [comment]
個人の名前が載っていたので一応「松江市様」に書き換えました。

**Comment by sakasita001** [comment]
ありがとうございます。

これからは自分の書いたものについて見直すようにします。
配慮が足りず、申し訳ございませんでした。

**Comment by sho-h** [comment]
https://github.com/matsuerb/matrk/issues/40#issuecomment-140666357 って感じです！(てきとう)

**Comment by yoshiokaCB** [comment]
@sakasita001 さん
個人も含めて返却が確認できましたらクローズお願いします。
支払いに関しては別のissueを立てます。

**Comment by sakasita001** [comment]
返却完了しました。
