### ISSUE TITLE
ruby-lang.org/newsに開催のお知らせを載せる

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk#18]
以下のような話があるみたいですが、
- https://github.com/ruby-no-kai/official/issues/111

以下では既にやろうぜみたいな様子なので募集開始後にPRを投げて上記Issueでこんな感じですかね？と聞いてみる。
- https://github.com/ruby-no-kai/official/wiki/Regionalrubykaigi#参加申し込みを開始したら

以下を参考にする予定。
- https://github.com/ruby/www.ruby-lang.org/blob/master/ja/news/_posts/2014-07-26-rubykaigi-2014-registration-online.md

**Comment by sho-h** [comment]
修正内容は[こんな感じ](https://github.com/sho-h/www.ruby-lang.org/blob/add-matrk07-registration-news/ja/news/_posts/2015-09-03-matsue-rubykaigi-registration-is-open.md)かなぁ。というところです。

**Comment by yoshiokaCB** [comment]
良さそうですね！

**Comment by sho-h** [comment]
どもです！PR投げました。

**Comment by yoshiokaCB** [comment]
ありがとうございます！
