### ISSUE TITLE
懇親会会場下見

### ISSUE THREAD

**Issue by sakasita001** [matsuerb/matrk#19]
懇親会の下見について、7/13の夜9時に行ってきました。
報告しようと思います。

【聞くこと】
　値段設定
　　・備品使用料等料理以外に発生するのか
　　・料理代はいくらになるのか（コースで設定されているはず）
　　・飲み放題について（飲み放題の値段、ソフトドリンクのみの人数で値段が変化するかどうか）
~~音出し（マイクの使用）はOKか？~~
【確認すること】
　会場の間取り
　　・床の寸法
　　・テーブルの寸法（後で配置を決めるため）
　　・音響等、ケーブルの位置
　　・全体の写真

**Comment by sakasita001** [comment]
マイクは会場に備品として備えてあり、使用しても大丈夫です。

**Comment by yoshiokaCB** [comment]
料理についてですが、飲み放題有り・無しとかソフトドリンクの人の飲み放題は料金が変わるかなども聞いておいてもらえると助かります。
（多分、飲み放題はつけるし、ソフトドリンクの人も同じ料金にはなると思いますが。。。）

**Comment by sakasita001** [comment]
承知いたしました。ありがとうございます。

**Comment by sakasita001** [comment]
ウィキに書く前の下書きです。

　値段設定
　　・備品使用料等料理以外に発生するのか
　　　　・発生しません
　　・料理代はいくらになるのか（コースで設定されているはず）
　　　　・選択肢は飲み放題付のコース2種類です。
　　　　　　A貸切時間2時間、飲み放題90分、コース料理込　4,300円（生ビール等無）
　　　　　　B貸切時間2時間半、飲み放題120分、コース料理込　4800円（生ビール等あり）
　　・飲み放題について（飲み放題の値段、ソフトドリンクのみの人数で値段が変化するかどうか）
　　　　・飲み放題付のプランしか選択肢がなかったです。ソフトドリンクのみ等の管理ができないので一律アルコール料金です
音出し（マイクの使用）はOKか？
　　・OK
【確認すること】
　会場の間取り
　　・床の寸法
　　　　・8ｍ×12ｍ
　　・テーブルの寸法（後で配置を決めるため）
　　　　・0.58×1.2＠4島
　　・音響等、ケーブルの位置
　　　　　　・モニターへの接続はHDMI端子（ケーブルはないので準備の必要がある）
　　　　　　・週末にUPします
　　・全体の写真
　　　　　・週末にUPします。

【お店から確認されたこと】
　　・会場内禁煙（喫煙所有）
　　・受付場所は会場外、入り口そばに設営
　　・人数の概算を9月頭、一週間前、前日の三回に分けて確認を取りたい。
　　・前日以降にキャンセルが出た場合キャンセル料が発生する。
　　・持ち込みの機材で電源使うのはいいけど、ブレーカーの保障はできない（予行でつけてみてはどうか。）
　　・PCの音声を会場スピーカーに乗せれないが、DVD再生なら可能（PC再生もモニター備え付けのスピーカーのみ出力可）

とりあえず、こんな感じでした。
細かいところ端折ってますので、WIKIに必要な項目が不足してましてらご一報いただけると幸いです。

相談といたしましては値段が予想より数百円オーバーしてるのですが、どういたしましょうか？（主に企業協賛金の関係）
個人的には端数を学生が負担にするのが無理が生じない形なのかなと思うのですが。

**Comment by kenjiSugihara** [comment]
お疲れ様です！

> 値段が予想より数百円オーバーしてるのですが、

今、皆さんと予算案を作成してますが、交流会参加費を一般4,300円、学生1,000円（つまり3,300円を補助する）で見積もっていますから、大丈夫っすよ！

**Comment by kenjiSugihara** [comment]
B貸切りプランにされるかどうかは、皆さんでご相談ですね！

**Comment by yoshiokaCB** [comment]
@kenjiSugihara さん, @sakasita001 さん

ありがとうございます。

> B貸切りプランにされるかどうかは、皆さんでご相談ですね！

次回のミーティングで皆さんと相談しましょう。

**Comment by kenjiSugihara** [comment]
@yoshiokaCBさん、有難うございます！
なんとなく
1）個人負担でのBプランの会費が、高いかどうかの相場観
2）仮に10社が協賛、交流会のプレゼンを希望した場合の交流会の進行
　（10社☓＠5分がプレゼン時間）
3）Bプランの場合、学生への補助額が上がることによる収支見込み
　（損益分岐点が上がるため、結果、協賛企業を増やす必要が生じるかも）
このあたりが検討ポイントかと思いますので、
僕の方で「3）」を一度積算してみておきますね！

**Comment by sakasita001** [comment]
@yoshiokaCB　さん @kenjiSugihara さん

ありがとうございます。よろしくお願いいたします。

**Comment by kenjiSugihara** [comment]
@yoshiokaCBさん、@sakasita001さん
Bプラン、学生への補助額が上がることによる収支見込みを作ってみました。
（Googleのスプレッドシートです）
結論から言うと、協賛企業数が10社必須になります。

**Comment by sakasita001** [comment]
全景とメニュー表です。
![90](https://cloud.githubusercontent.com/assets/9796684/8887907/45db91ac-32d2-11e5-9efd-651b7c0e6fb1.JPG)
![120](https://cloud.githubusercontent.com/assets/9796684/8887908/45dc0484-32d2-11e5-8a35-7bdb179d5992.JPG)
![default](https://cloud.githubusercontent.com/assets/9796684/8887910/45dfb110-32d2-11e5-9142-51854fbfcc2e.JPG)
![default](https://cloud.githubusercontent.com/assets/9796684/8887909/45de5afe-32d2-11e5-8674-8ceab7ecd903.JPG)

**Comment by sho-h** [comment]
本Issueはcloseしてもいい感じですっけ？wiki？

**Comment by sakasita001** [comment]
wikiは使い方が分かっていなかった為誤用です。
ミーティング後、コースが決定してからCloseでお願いいたします。

**Comment by sakasita001** [comment]
すいません。嘘言いました。#8があるのでこちらは閉じて頂いて大丈夫です。

宜しくお願いいたします。

**Comment by sho-h** [comment]
はいー。
