### ISSUE TITLE
ゲスト講演の掲載について

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#20]
@inoh さん

ゲスト講演の内容の修正をお願いします。

講演タイトル：「Redmineの歴史とアーキテクチャ(仮)」
講演者： Toshi MARUYAMA (Redmineコミッター)

よろしくお願いします。

**Comment by inoh** [comment]
修正してプルリクエストを送っておきました！
https://github.com/matsuerb/matsuerb-nanoc/pull/275

@sho-h さん

反映お願いします！

**Comment by sho-h** [comment]
反映しました！

**Comment by inoh** [comment]
ありがとうございます！

**Comment by yoshiokaCB** [comment]
ありがとうございました。
