### ISSUE TITLE
告知サイトのプログラミングコンテスト用のページを作る

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#22]
@inoh さん

以下のページを参考にプログラミングコンテスト用のページの作成をお願いできますか？

https://github.com/matsuerb/matrk/wiki/07_%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E3%82%B3%E3%83%B3%E3%83%86%E3%82%B9%E3%83%88%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6-powerd-by-paiza

まだ、不明な点があるかと思いますので、そちらをこのissueにアップしてもらえると助かります。
よろしくお願いいたします。

**Comment by inoh** [comment]
@yoshiokaCB 
プログラミングコンテストって正式にはプログラミングクイズですか？
OSCのときの発表がクイズになっていたのでどっちにしようか悩み中です。

**Comment by yoshiokaCB** [comment]
@inoh さん
プログラミングコンテストの正式名称はプログラミングコンテストでOKです。
プログラミングクイズ大会は別の企画で考えています。
（クロージングの時間かプログラミングコンテストの余った時間でやる予定です。）

**Comment by inoh** [comment]
あ、そうでした...私の勘違いでした！

**Comment by sho-h** [comment]
とりあえずこっちもおしまいかなと思うので、しれっとcloseしておくのであった。
