### ISSUE TITLE
イベントTシャツ作成

### ISSUE THREAD

**Issue by AyakoMakihara** [matsuerb/matrk#23]
松江Ruby会議07イベントTシャツを作成します。
昨年度は松江Ruby会議05Tシャツの追加発注だったが、今回はデザインを刷新予定。
## 担当

加藤さん（デザイン）・槇原（発注・取りまとめ）
## タスク
- [X] Tシャツスポンサーを依頼  （7月末頃）
- [X] 注文する人を取りまとめて枚数を確定（8月末頃）
- [X] サイズの取りまとめ                             （8月末頃）
- [X] データの受け渡し                                （9/5まで）
- [X] tmixさんに注文                                   （到着2週間前 9/5頃）
- [X] 受取　　　                                         （9/14）
- [X] 配付　　　                                         （イベント1日前or当日）
## サイズ別注文リスト

| 　サイズ　 | 枚数　 |
| --- | --- |
| 150 | 1 |
| 160 | 5 |
| S　 | 0 |
| M　 | 11 |
| L　 | 8 |
| XL　 | 3 |
| XXL | 2 |
| 合計 | 30 |

**Comment by AyakoMakihara** [comment]
昨年同様、TシャツスポンサーＯＫ頂きました。昨年より多くの枚数プレゼント頂けます :smiley:

**Comment by yoshiokaCB** [comment]
@AyakoMakihara さん
ありがとうございます！

**Comment by AyakoMakihara** [comment]
サイズの取りまとめを行います。希望者は下記シートへ入力をください:smiley:
http://3step.me/36qp
サイズは[Tmix](http://tmix.jp/item/tshirt/tshirt_cvt)さんを参照ください。
**期限：9/4(金)中**

**Comment by KatoAtsue** [comment]
「しまねっこ」の利用申請に必要ですので、松江Ruby会議を開催する「団体名」と「代表者名」を教えていただけますでしょうか。
よろしくお願いします。

**Comment by sho-h** [comment]
僕の分を記載するのに併せて何名かぶんは05の時のサイズ(facebookに記録がある分だけ)を記載しました。 備考き05の記述がある方は確認して備考消してください。

**Comment by KatoAtsue** [comment]
明日試作品が届く予定になっています。
現物があまり派手だったら少し地味にしようと思っています。
修正等ご指摘をお願いします。

**Comment by AyakoMakihara** [comment]
試作品完成おめでとうございます :tada:

**Comment by KatoAtsue** [comment]
槇原さん、どうもありがとうございます。

**Comment by yoshiokaCB** [comment]
ありがとうございます！
どんな感じか楽しみですね！
ちなみに土曜の定例会で見れますかね？

**Comment by KatoAtsue** [comment]
どうもありがとうございます。
明日の午後、持参しますのでよろしくお願いします。

**Comment by KatoAtsue** [comment]
Tシャツ届きました。明日よろしくお願いします。
![tshirt_photo_01](https://cloud.githubusercontent.com/assets/5475425/9537348/e9ab1f14-4d71-11e5-9741-e56e64439b61.png)

**Comment by yoshiokaCB** [comment]
やった！
明日楽しみです！！

**Comment by KatoAtsue** [comment]
どうもありがとうございます。

**Comment by amidaku** [comment]
d(>_< )GJ!!
明日行けないですけど本番が楽しみです。

**Comment by KatoAtsue** [comment]
どうもありがとうございます。本番に間に合って嬉しいです。

**Comment by sakasita001** [comment]
試作品完成おめでとうございます！
明日楽しみにしてます♪

**Comment by KatoAtsue** [comment]
ありがとうございます。明日はよろしくお願いします。

**Comment by yoshiokaCB** [comment]
皆様
そろそろTシャツ申し込みの締め切りですが、記入漏れとかありませんかね？
可能であれば、自分の物以外にも漏れがないかチェックしてもらえると助かります！
（スタッフで抜けてる人がいるとか、誰かプレゼントをしなきゃいけない人が抜けてるとか。）
よろしくお願いします。

**Comment by AyakoMakihara** [comment]
事前に @KatoAtsue さんからデータ受領済みです。申込みシートの確認が終了次第、発注します :smile_cat:

**Comment by sho-h** [comment]
僕の宿題が完遂できてないんですけど、(#25 的にも)直接会ってお話ししたかったのですが、不運にももう少し先になりそうなので、メールで確認しますね。おそらく期限ギリギリになります。

**Comment by AyakoMakihara** [comment]
@sho-h なるほど、ギリギリでも大丈夫です :ok: 連絡取りながら行いましょう！

**Comment by sho-h** [comment]
ありがとうございます！ところでシートのJ列とK列ってどなたか何か編集されました？

**Comment by AyakoMakihara** [comment]
:question: 私は何も編集していません！

**Comment by sho-h** [comment]
編集してない了解です。まつもとさんのサイズを記入しようとしたらJ, K列が真っ黒だったので誰か操作ミスとかかなぁと思って質問でした。

**Comment by ToruKurahashi** [comment]
そう言えば片山さんのTシャツは@yoshiokaCB さんが本人に送られる感じですか？

**Comment by sho-h** [comment]
確認したところ、Anonymous(といっても@AyakoMakiharaさん以外のどなたかの可能性はありますが)の9/2 13:01の修正でおかしな事になってるようでしたので、その前に巻き戻しました。

その後で先ほど(9/3 17:22)に僕がまつもとさんのサイズを記入しました。問題があれば再度9/2 13:01の時点に巻き戻します。上記の時間に編集した方が名乗りでなければ今のままでいいかなぁ。

**Comment by ToruKurahashi** [comment]
ちなみに私は編集しておりませぬ。

**Comment by sho-h** [comment]
ちなみに僕は僕を疑っています。(https://github.com/matsuerb/matrk/issues/23#issuecomment-137373231 がそれくらいの時間だと思うため

**Comment by amidaku** [comment]
注文枚数のセルの計算式がおかしかった（対象セルが26までだった）ので修正しておきました。

**Comment by yoshiokaCB** [comment]
プレゼントの件は、とある人に聞いてくださいと投げましたが返ってきませんので、これから確認して見ます。

**Comment by yoshiokaCB** [comment]
@AyakoMakihara さん
これでOKです！
いっちゃってください。

**Comment by AyakoMakihara** [comment]
皆さま確認ありがとうござます :tada: お昼休みに注文しますね。
取りまとめのシートは参照のみの設定に変更しております :+1:

**Comment by AyakoMakihara** [comment]
tmixさんへ注文が完了 :ok_woman: 
追加注文があるといけないので、希望ある人は下記の**追加注文シート**へ記入ください。 
ただし、イベント当日には納品ができないと思われます。
http://3step.me/36qp

**Comment by KatoAtsue** [comment]
Tシャツの副産物で小さなメモ帳も作ってみましたので、もしよかったら何かで使ってください。
![memo_sample](https://cloud.githubusercontent.com/assets/5475425/9752754/ee56cf00-56ee-11e5-8f74-e9d2944b2121.png)

**Comment by AyakoMakihara** [comment]
@KatoAtsue 素晴らしい :tada:  楽しみです。
Tシャツは9/25までで、なるべく早くとして、テクノプロジェクトに発送を希望しています。ただ、私が9/23-25まで大阪に出張になったため、発送先は変更した方が良いかなと思っています。どうしましょうか？ @yoshiokaCB @sho-h

**Comment by KatoAtsue** [comment]
@AyakoMakihara さんどうもありがとうございます。

**Comment by sho-h** [comment]
@KatoAtsue すごい！！

@AyakoMakihara 僕もその日休みですが、高田さんに弊社サテライトオフィスで受け取ってもらうと移動が少なくて済みそうですね。どうでしょう？ > @yoshiokaCB

**Comment by yoshiokaCB** [comment]
サテライトオフィスで受け取り可能であれば、お願いしたいです！
ただ、みなさんに配るのは前日か当日（9/25, 9/26）を予定しています。

**Comment by sho-h** [comment]
@yoshiokaCB りょうかいです。高田さんに相談してOKいただきました。宛先を別途お伝えします。

**Comment by yoshiokaCB** [comment]
ありがとうございます！

**Comment by AyakoMakihara** [comment]
@sho-h @yoshiokaCB ありがとうございます :smile_cat: 宛先受け取り次第、発送先変更をしておきます！

**Comment by AyakoMakihara** [comment]
@sho-h @yoshiokaCB 9/14(月)午前　Naclサテライトオフィス　高田様宛に到着予定です :ok: 余裕がある発送で対応して下さってtmixさんに感謝です！

**Comment by teeta32** [comment]
Tシャツの受け取り承知しました。

**Comment by AyakoMakihara** [comment]
@teeta32 よろしくお願いします :smiley:

**Comment by AyakoMakihara** [comment]
@teeta32 tmixさんから予定通り、出荷メールが来ました！9/14お願いします。

**Comment by teeta32** [comment]
@AyakoMakihara Tシャツの出荷連絡ありがとうございます。受け取り了解です!

**Comment by teeta32** [comment]
@AyakoMakihara Tシャツが届きました！
納品書などを @AyakoMakihara さんへお送りします。(これから私が終日出かけるので、納品書などは今晩以降にお送りします。)

**Comment by AyakoMakihara** [comment]
@teeta32 受取ありがとうございます :+1: 納品書はTシャツと一緒に入れといて頂ければ大丈夫です。ただし、枚数確認は必要ですね。どうしましょうか？明日・明後日に事務所にお伺いしても大丈夫でしょうか？

**Comment by teeta32** [comment]
@AyakoMakihara さんと相談して、こちらでTシャツの枚数を確認することにしました。本Issueの"サイズ別注文リスト"の枚数と届いているTシャツの枚数を確認します。

**Comment by AyakoMakihara** [comment]
@teeta32 よろしくおねがいします :smile_cat:

**Comment by teeta32** [comment]
@AyakoMakihara Tシャツの枚数を確認しました。本Issueの"サイズ別注文リスト"どおりのサイズと枚数でした。Tシャツは、このままオープンソースラボの隣のNaClの事務所でお預かりしますね。私も開催前日の打合せに参加予定ですので、そのときにTシャツを持っていけると思っています。

**Comment by teeta32** [comment]
昨日、今日とTシャツの配布が進んでいますので本件は終了します。

**Comment by AyakoMakihara** [comment]
:+1:
