### ISSUE TITLE
クイズ大会の問題作成（Tシャツプレゼント）

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#24]
クイズ大会用の問題作成をしたいと思います。
以下の4名に作成依頼をします。

@sho-h さん @sada さん @Takashi-U さん 西田さん

また、問題が出来ましたら自分まで直接送ってください。
その他、何か不明な点等ありましたらこちらのissueにコメントお願いします。

**Comment by yoshiokaCB** [comment]
すでに橋本さんからは問題をいただいてます！
あと、どなたか西田さんにここのissueのことを伝えてもらえると助かります。
（西田さんのgithubのアカウントがわかりませんでした。。。）

**Comment by nishidayuya** [comment]
確認しました!

送り方としては@yoshiokaCBさんがGitHub.comに登録されているメイルアドレスに送れば良いでしょうか．

**Comment by yoshiokaCB** [comment]
@nishidayuya さん
はい。GitHubのメールか、FBのメッセージで送ってもらえればと思います。
よろしくお願いいたします！

**Comment by sho-h** [comment]
ちなみに自分ですが @nobyuki 先生が挙げてた[The Ruby Challenge](https://therubychallenge.com/code_challenges)っぽい2択の選択問題を作りました。ただこれは速いのはどっちかという濃い問題しか僕には見つけられなくて、RubyKaigiにはいいかもしれんけど松江だと答えるの辛いだろうなぁと思ったので、◯◯なのはどっちか？といった問題を3問ほどつくりました。(一応認定試験問題っぽくした問題もつくったけど、そっちは別に捨ててもいいつもり)

一旦口頭ではお聞きしたと思うんですが、改めて残しておくと方針はそんな感じ(The Ruby Challengeっぽい)ですかね？

**Comment by yoshiokaCB** [comment]
@sho-h さんのご指摘の通りきちんと明文化しておくべきでした。すみません。

もともとの目的はTシャツプレゼントでジャンケン大会の代わりにクイズ大会で成績優秀者（最後まで正解し続けた人）にプレゼントするという形にしたいと考えていました。
ですので、問題の回答はマルバツか選択式（2択）とかで回答できる形式にしていただくと助かります。
逆に言うとマルバツ・選択式で答えれるならどんな問題でもOKです。

以下、個人的な考えですが、
問題の難易度等に関しては特に気にしてないです。
選択式なら運勝負でもいいかなと思っています。
皆さんに普段あまり考えないこと（気にしないこと）を考えるきっかけくらいになればと思っているところです。

もし、こうした方がいいとか、ご意見ありましたらいただけると助かります。
プログラミングクイズをしたいと言うこと以外は特に強いこだわりは無いので(^^;;)

ちなみに @sho-h さんから頂いた問題はすごく良かったです！

**Comment by sho-h** [comment]
どもです！

**Comment by AyakoMakihara** [comment]
プレゼント用のTシャツ枚数が決定したら、Tシャツ注文への反映を忘れずに :rabbit2:  #23

**Comment by yoshiokaCB** [comment]
@AyakoMakihara さん
ありがとうございます。
基本的に余りで良いので、スタッフの集計が終わってからにしようと思ってます！

**Comment by yoshiokaCB** [comment]
@sada さん、 @nishidayuya さん、 @Takashi-U さん
お忙しいところ恐縮ですが、問題の作成をお願いします！

**Comment by nishidayuya** [comment]
@yoshiokaCB さん
すみません遅くなりましたが送りました!

**Comment by yoshiokaCB** [comment]
@nishidayuya さん
確認しました！
ありがとうございます！！

**Comment by yoshiokaCB** [comment]
問題が出揃ったのでクローズします。
