### ISSUE TITLE
基調講演の依頼内容について

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#25]
## 

基調講演
講演者：まつもと ゆきひろ氏
時間：13:30 〜 14:20
内容：未定
## 

どのようなテーマでお願いをするか、まだ決まってませんでした。
皆さんで、こんな話を聞いてみたいと言う意見がありましたら、こちらにコメントお願いします！

@sho-h さん、とりまとめお願いしても大丈夫でしょうか？

**Comment by yoshiokaCB** [comment]
ちなみに自分は、ありきたりですが、Ruby2.3の情報をコードを交えてお話しいただけるといいかなと思いました。

**Comment by sho-h** [comment]
Issueありがとうございます。今月末くらいを目処にやろうかと思います。

**Comment by nobyuki** [comment]
ライブコーディングというテーマに合わせる感じで、まつもとさんの開発環境のことをお話してもらうのも面白いかなと思います。
- これだけは欠かせないという機能
- 最近導入して良かったという機能
- 過去においてライフチェンジングだった機能

資料的に過去の資産が無いかもしれないので、反応を伺いつつお願いする感じになるでしょうけど^^;

**Comment by yoshiokaCB** [comment]
@nobyuki さん
ありがとうございます！
@sho-h さんと少し相談しましたが、その線でお願いすると思います！！

**Comment by nobyuki** [comment]
:+1:

**Comment by nobyuki** [comment]
今日、まつもとさんにご依頼しました。
開発環境のことというテーマで承諾いただきました。
