### ISSUE TITLE
スポンサーのロゴを確保する

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk#26]
@yoshiokaCB 
スポンサー様のロゴとかってありますか？

**Comment by yoshiokaCB** [comment]
@inoh さん
メールで送りましたがどんな感じでしょうか？

**Comment by inoh** [comment]
対応が遅くてすみません。
メールをあさりつつスポンサー様のページ作成中です。
子供の妨害のあってなかなか作業進まず、、、また今夜整理確認してホームページプルリク送ります

**Comment by sho-h** [comment]
全部揃った感じっぽいのでcloseしときます。(ついでに共有ですが「株式会社」と社名間のスペースの扱いがバラバラだったので、全部削りました)
- http://matsue.rubyist.net/matrk07/
