### ISSUE TITLE
ホームページを正式に公開する

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk#27]
**残作業**
- [x] スポンサーをホームページに載せる
- [x] Doorkeeperを公開する

**公開日（予定）**

8/29

**Comment by inoh** [comment]
次回まつえるびーの定例会で調整させてくださいということで公開予定日は8/29にかってに設定しています。

**Comment by sho-h** [comment]
プログラミングコンテスト関連もぼちぼちその頃です？もうちょっと後ですっけ？

**Comment by sho-h** [comment]
あ、matsuerb-nanocの方のプルリクに含めていただいてますね。:)

**Comment by inoh** [comment]
いちおざらっと私の方でもページを作成してますが詳細は9/1あたりにpaizaさんからも出るという認識です。
8/29に問題なければあわせてプルリクマージ公開って感じですかね
https://github.com/matsuerb/matsuerb-nanoc/pull/282

**Comment by yoshiokaCB** [comment]
@sho-h さん
プログラミングコンテストは9/1の11:00 か12:00から開始の予定です。
詳しくは8/29の定例会で相談したいです。

**Comment by kenjiSugihara** [comment]
すいません、スポンサーのロゴ（現状エントリーの3社分）を先ほどメールで井上さん、吉岡さんに送りました！サイトへのアップをお願い致します。
※テクノプロジェクト様から、「当社で公式サイト、スポンサーであることを宣伝してよいタイミングを教えてください」と言われていますので、サイトに掲載したタイミングでお知らせしようと思います！

**Comment by kenjiSugihara** [comment]
また、広くスポンサーは募集した形を取るものとして、公式サイトの「スポンサー」欄に次のような文言を掲載しては、と思いますが、如何でしょうか？

（掲載文案）
今年の開催では、RubyやRuby on Railsに関心のある学生やエンジニアに、
これまで以上に参加してもらえる企画を用意したいと考えてます。
つきましては、松江Ruby会議の趣旨にご賛同いただき、協賛金のご協力をお願い申し上げます。
１） 募集金額：１口１万円
２） 協賛金の使途（予定）：プログラミングコンテストの賞品、学生の交流会参加費補助
３） 協賛特典：
        ①  交流会で予定する5分間の貴社紹介のプレゼン機会
        ②  会場への貴社パンフレットの備え置き
        ③  イベントサイトへの貴社バナーの掲載　
４）募集期間：2015年8月●日（●）　〜　9月11日（金）
５）お申込み方法：以下の情報を添えて、sugihara.shimane.pref(at)gmail.comまでご連絡ください。
　　　　　　　　　・貴社、組組織、又は個人名 
　　　　　　　　　・貴担当者様の氏名、電話番号、メールアドレス 
　　　　　　　　　・請求書送付先(御担当者様の氏名、電話番号、メールアドレス、住所) 
　　　　　　　　　・お申し込み口数
　　　　　　　　　・お希望の特典内容
　　　　　　　　　・イベントサイトへのロゴ掲載を希望の場合のロゴデータ
　　　　　　　　　　※データ形式は特に問いません。
　　　　　　　　　　　可能な限りサイズの大きなファイルでお願いします。

**Comment by inoh** [comment]
上記の掲載文章を今度のアップに併せて載せようと思います！

**Comment by sho-h** [comment]
今日順番は吉岡さんと相談して決めたので反映しました！

上記の文章の分は@inohさんにお願いさせてください。m(_ _)m

**Comment by sho-h** [comment]
公開の日は9/1になりました。その日付はこちらで修正しようかと。

**Comment by inoh** [comment]
公開の日了解しました。
私の方でもスポンサー欄の修正とスポンサーの募集要項等を修正したのであわせて日付を修正しています。
コンフリクトが起きたらごめんなさい！
順番やプログラム内容についてはこれから見直しします。

https://github.com/matsuerb/matsuerb-nanoc/pull/285

**Comment by sho-h** [comment]
日付ありがとうございます！まだだったのでコンフリクトは特になかったです！

スポンサーさんのリンク先の更新もしたいのですが、@inohさんもらっとられます？(各社様のトップページでよいとは思うのですが一応)

**Comment by yoshiokaCB** [comment]
@inoh さん、@sho-h さん
すみませんが、今日中にプログラミンコンテストのページを修正してプルリク送らせていただきます！

**Comment by inoh** [comment]
あ、スポンサーのリンク先コピペで全然直してなかったです。。。
特にリンク先は聞いてないですがとりあえずトップページに直しておきます

**Comment by sho-h** [comment]
@inoh よろしくお願いします！！

あ、今気づきましたけど、これまでの口頭での会話の流れからmatrk07/contest.htmlに以下の記述を追加したいかもしれません。記載する場所や文言は変更になってもかまいません。

```
--- a/static/matrk07/contest.html
+++ b/static/matrk07/contest.html
@@ -124,7 +124,8 @@
           <h4>1. 上位成績者決定</h4>
           <p>
             松江Ruby会議07参加者のメールアドレスおよびニックネームと照らし合わせて上位成績
者３名を決定します。<br>
-            また、面白い回答に特別賞をあげることも可能です。
+            また、面白い回答に特別賞をあげることも可能です。 <br>
+            (※事前に問題の内容に関する情報を得る権限がなく、回答締め切り前に他の回答者の途中結果を確認する権限のないメンバーに限り松江Ruby会議スタッフもコンテストに参加する場合があります。なお、採点はpaizaさまの方で機械的に行います。ただし、回答締切後に参加したスタッフが回答内容を確認する事はありえます)
           </p>
           <h4>2. プログラム発表</h4>
           <p>
@@ -139,4 +140,4 @@
       <p class="text-center"><a href="http://matsue.rubyist.net/"><img src="img/h_logo.jpg"
 alt="matsuerb"></a></p>
     </footer>
   </body>
```

**Comment by yoshiokaCB** [comment]
@sho-h さん
加えておきます！

**Comment by sho-h** [comment]
おふたりともありがとうございました。全部マージしました。日付が変わったら公開したらいいんでしたっけ？

**Comment by sho-h** [comment]
今日(9/1)のお昼に反映する事になりました。

**Comment by sho-h** [comment]
やりました。後はdoorkeeper！

**Comment by yoshiokaCB** [comment]
修正して公開しました。

@sho-h さん
色々とありがとうございました！

**Comment by sho-h** [comment]
doorkeeperまわりも完了してるのでこちらはcloseしてしまいますね。
