### ISSUE TITLE
配布用のチラシを作る

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#30]
きむらしのぶさんに依頼中

**Comment by yoshiokaCB** [comment]
先ほどデータをいただきました。

![matsue-ruby-kaigi-07](https://cloud.githubusercontent.com/assets/4011289/9632833/69ca22b6-51c4-11e5-844f-79c70434c2f0.jpg)

これで良いと思いますが、何かありましたら。

**Comment by shinob** [comment]
ちょっと微調整しました。

![matsue ruby kaigi 07](https://cloud.githubusercontent.com/assets/281774/9639915/7ea679a8-51e9-11e5-973e-6791592ce5c8.png)

**Comment by yoshiokaCB** [comment]
ちなみにこのロゴって勝手に使って大丈夫ですかね？
大丈夫だとは思いますが、今話題になってるのでちょっと気になりました(^^;;)

**Comment by shinob** [comment]
サイトで公開されてて、誰でもダウンロード可能ですが...確認しときますね。

http://www.ruby-assn.org/ruby-logo.html.ja

**Comment by ToruKurahashi** [comment]
@yoshiokaCB プロコンサイトのバナーのRubyロゴはこれだと思いますが、大丈夫ですか？
https://www.ruby-lang.org/ja/about/logo/

**Comment by yoshiokaCB** [comment]
プロコンというか、そもそも松江Ruby会議で使ってる。。。
ライセンス見ると大丈夫そうですよ。（加工しても良いし、商用でも自由に使ってねって書いてあるように思えますが。。。）
英語なので念のため @ToruKurahashi さん確認してもらって良いですか？

http://creativecommons.org/licenses/by-sa/2.5/

**Comment by ToruKurahashi** [comment]
このライセンスには、以下の様な記載がありました。

表示 — あなたは 適切なクレジットを表示し、ライセンスへのリンクを提供し、変更があったらその旨を示さなければなりません。あなたはこれらを合理的などのような方法で行っても構いませんが、許諾者があなたやあなたの利用行為を支持していると示唆するような方法は除きます。

**Comment by sho-h** [comment]
CCなら日本語もありますよ。(クレジットがない気がしますね)
- https://creativecommons.org/licenses/by-sa/2.5/deed.ja

**Comment by yoshiokaCB** [comment]
Copyright © 2006, Yukihiro Matsumoto
をどこかに付けなければいけないってことです？

**Comment by sho-h** [comment]
cc 2.5 by Yukihiro Matsumoto (http://creativecommons.org/licenses/by-sa/2.5/) とかcc2.5の部分が画像(で、画像にライセンスへのリンク)とかですかねぇ。(公式サイトとプロコンの方なので別Issueがいいかもですけど)

> サイトで公開されてて、誰でもダウンロード可能ですが...確認しときますね。
> http://www.ruby-assn.org/ruby-logo.html.ja

本題に戻ると特に不要そうに見えますね。

**Comment by ToruKurahashi** [comment]
参考まで
http://creativecommons.jp/faq/#a4

**Comment by amidaku** [comment]
一番下にCCが求めている記載を載せるのが一番綺麗なのでは。
「※Rubyロゴは〜の著作物であり、Creative Commons BY-SAライセンスにより〜で公開されています。」
って感じですかね。

**Comment by sho-h** [comment]
CCについてはもう公開してるから遅いので、ゆっくり対応したらいいと思います。#31 を作りましたのでそちらにしましょう。後で検索しづらいからあまり伸ばしたくないです。

**Comment by sho-h** [comment]
こちらも調べました。何故か[ロゴ紹介ページ](http://www.ruby.or.jp/ja/about/logo/)になにも載ってないのですが(派生物のくだりが好きにしていいってことかしら？とは思いました)、[Ruby公式ロゴ公開時のニュース](https://www.ruby-lang.org/ja/news/2008/01/09/ruby-logo-available/)によるとCC BY-SAですね。[コンテスト時の予定](http://www.ruby-assn.org/logo-contest.html.ja)でも同じだったみたいです。

公開以降現在までの変化がわかりませんでしたので、[公式サイトのレポジトリ](https://github.com/ruby/www.ruby-lang.org/)を日本語で確認する分には変わってないと思いますので、誰もがそこ間違ってるんじゃないかな...といまのところ考えている次第です。

```
$ lgrep ロゴ ja/news/_posts/*
ja/news/_posts/2007-09-01-ruby-logo-contest.md:title: "Rubyロゴコンテスト"
ja/news/_posts/2007-09-01-ruby-logo-contest.md:Rubyアソシエーション主催で、[Rubyロゴコンテスト][1]が開催されています。 みなさんのご応募をお待ちしています。
ja/news/_posts/2008-01-09-ruby-logo-available.md:title: "Ruby公式ロゴ公開"
ja/news/_posts/2008-01-09-ruby-logo-available.md:Ruby公式ロゴのデータが [ダウンロード可能][1] になりました。
```

直接確認した方がよさそうかな...と思いました。(^ ^;)

**Comment by yoshiokaCB** [comment]
たぶんRAに人に聞いてももう一つのロゴと同じくそこまで神経質にならなくていいよって言われそうですね。

@shinob さん
まぁ、話に出ちゃったんで、すみませんが以下のような文を、下の方に小さくで良いので入れていただけないでしょうか？（話に出した自分が言うのも何ですが…）

「RubyロゴはRubyアソシエーションの著作物であり、Creative Commons BY-SAライセンスにより http://www.ruby.or.jp/ja/about/logo/ で公開されています。」

**Comment by sho-h** [comment]
そうですね。同じ結果になりそうですし、こちらは著作権がRAでもありますし特に追加で確認する必要はなくなったかもしれません。

**Comment by shinob** [comment]
チラシについて、説明文を追加すること承知いたしました。
ただ、今日のお昼に松江工業高校へ行く用事があったもので、原案のまま持参してお渡ししておきました。チラシは修正したものを皆さんがダウンロードできる形でどこかにアップしておくので、各自でダウンロードして配ってもらう手順で良いですか？

**Comment by yoshiokaCB** [comment]
@shinob さん
ありがとうございました！
以下、ダウンロードできるようにアップしておきました。

https://github.com/matsuerb/matrk/raw/master/doc/matrk07-pamphlet.pdf

**Comment by sho-h** [comment]
作成お疲れさまです！

すいません、今頃気付いたんですけど、人名の後ろ「氏」のあるなしを統一した方がいいですかね？(あ、公式サイトがそうだったからっぽい)

**Comment by shinob** [comment]
了解です！
公式サイトにあわせて修正します！

**Comment by sho-h** [comment]
@shinob 全部「氏」をつけました！

**Comment by shinob** [comment]
了解です！今、熱海なので、帰ったら直して連絡しますね。

**Comment by sho-h** [comment]
@shinob ありがとうございます！

あと、 @yoshiokaCB さんがpdfコミットしてくださってますけど、元データもコミットして来年以降で誰でも作りやすいようにしたいところです！

**Comment by shinob** [comment]
おはようございます。
チラシの修正と元データおよびPDFを吉岡さんに送らせて頂きました！

**Comment by yoshiokaCB** [comment]
データアップしましたのでクローズします。

https://github.com/matsuerb/matrk/tree/master/doc

**Comment by nishidayuya** [comment]
来週松江高専に行くことがあるのでチラシ持参していきますね．

**Comment by sakasita001** [comment]
@nishidayuya さん

お疲れ様です。9/20に松江高専で開催される「高専カンファレンス」で宣伝しようかと思ってます。
掲示場所を教えて頂けますと幸いです。

お手数をおかして申し訳ございません、宜しくお願いいたします。

**Comment by sho-h** [comment]
おぉ。ありがたや！プロコンの宣伝もぜひよろしくお願いします！

**Comment by nishidayuya** [comment]
@sakasita001 さん

会った学生や教官に配るつもりでした...学生係の脇とか掲示ありますね．
掲示させてもらえないか聞いてみます．

**Comment by nishidayuya** [comment]
配っておきました．内，一人は反応が良さそうでした．

@sakasita001 さん

学生係に出してきました．入口のロータリーが見える棟の一階部分と学生係の棟の2階に掲示してもらえることになりました．

**Comment by sakasita001** [comment]
畏まりました。ありがとうございます。
