### ISSUE TITLE
第三回　全体ミーティング開催について

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#32]
急ですみませんが、下記日程で全体ミーティングをしたいと思います！

| 日時 | 場所 |
| --- | --- |
| 9月11日（金）19:00〜21:00 | オープンソースラボ |

（なるべく1時間くらいで終わらせたいです。）

当日は以下の内容について皆様に報告と相談をしたいと思います。
## 報告事項
- 企画の決定事項の報告（昼食LT, Ruby クイズ, プログラミングコンテスト）
- スポンサーについて（スポンサーの状況）
- Tシャツについて
- 当日の流れ
## 相談事項
- 懇親会について（料金と時間の相談）
- Matsue.rbの資産管理について（ロゴデータなど）
## その他
- 各役割ごとに当日までに準備することや当日にやる作業の確認をお願いします。  
  （特に当日役割をお願いしている方はなるべくご出席をお願いします。）

参加表明はまたdoorkeeperか何かで準備しますので少々お待ちください。
とりあえず、予定を空けておいていただけると助かります。

よろしくお願いいたします。

**Comment by shinob** [comment]
11$BF|6bMKF|!)(B14$BF|7nMKF|!)(B

$B$I$A$i$G$9$+!)(B(^-^)

2015/09/03 23:41$B!"(BTakayuki Yoshioka notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by amidaku** [comment]
「11日金曜日？14日月曜日？どちらですか？」
とデコードしました。

**Comment by yoshiokaCB** [comment]
@shinob さん、すみません。11日（金）です！

@amidaku さん、デコードありがとうございます！

**Comment by shinob** [comment]
iPhoneのメールで返信すると文字化けするようですね。すみませんでした。
11日参加します！

**Comment by yoshiokaCB** [comment]
第三回全体ミーティングの参加者確認のため、doorkeeperで申し込みページを作りました。

https://matsue-rb.doorkeeper.jp/events/31097

皆様よろしくお願いいたします。

**Comment by kenjiSugihara** [comment]
すいません、11日（金）に参加できそうもなく、予算関係は、予め吉岡さん、橋本さんはじめ関係される方と調整の上、共有資料は準備しておきます。
また、スポンサー関係で、特にLT、当日の資料配布などについてもまとめておきます。

**Comment by Takashi-U** [comment]
申し訳ありません。先約がございまして…決して飲み会ではありません。

**Comment by yoshiokaCB** [comment]
@kenjiSugihara さん
資料よろしくお願いします！

@Takashi-U 
了解！じゃ、後でいつもの場所で会いましょう（笑）

**Comment by Takashi-U** [comment]
い、行けたら連絡します :+1:

**Comment by nobyuki** [comment]
11日は仕事で益田にいて参加できません。ごめんなさい〜^^;

**Comment by sho-h** [comment]
11日、台風が心配になってきましたね。(^^;)

**Comment by yoshiokaCB** [comment]
@nobyuki さん
了解です！お仕事がんばってください！！

@sho-h さん
基本大丈夫だとは思いますが、前日の様子で判断したいと思います。

**Comment by AyakoMakihara** [comment]
すいません :sob: 11日は午後から出雲で仕事の為、参加できません。Tシャツ関連で事前に確認事項ありましたら、 #23でご質問ください！

**Comment by yoshiokaCB** [comment]
@AyakoMakihara さん
了解です！
また何かありましたら別途issueなりを作ります。

**Comment by ml-yamaguchi** [comment]
@yoshiokaCB さん
すみません！11日、仕事で東京にいて参加ができなくなってしまったので、
当日の昼食のLTの司会ことは別途、確認させてください。（山口）

**Comment by yoshiokaCB** [comment]
@tgucchi さん
了解です！別件でお願いしたいこともありましたが、また個別に相談させていただくかもしれません。
出張お気をつけて行ってきてください！！

**Comment by yoshiokaCB** [comment]
ちなみにですが、明日のミーティング後に、お時間ある人がおられましたら、食事でも行こうかと考えてます。（特に参加表明等不要です。）
言わずに食べに行くと事前に告知するようにと言われそうなので。。。

**Comment by ml-yamaguchi** [comment]
@yoshiokaCB さん、ありがとうございます、来週の水曜から松江に戻っていますので、別件も含め教えてください！

**Comment by yoshiokaCB** [comment]
議事録まだだけど終わったのでクローズします。

**Comment by sho-h** [comment]
> 議事録

すぐ思い出せる範囲で書きました。なんかあったら追記してください。> 出席者の皆様

> all(全員にmentionするのってどうするんだっけ...)

議事録中にもありますが、[当日の予定](https://github.com/matsuerb/matrk/wiki/07_10-当日の予定（注意事項）)は重要という事でしたので来週前半くらい目処で確認をしておいてくださいませ。m(_ _)m

**Comment by yoshiokaCB** [comment]
ありがとうございます！
週末にやろうと思ってましたが、めっちゃ助かります！！
また確認しておきます！
