### ISSUE TITLE
Matsue.rb資産をコミットして管理したい

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk#33]
いくつか個人管理のデータが増えてきました。以下のデータは今後のためにも管理しててもいいかもしれませんね。
- [x] Tシャツデータ(matrk07)
  - しまねっこ/背景的に大丈夫であれば本レポジトリにコミット
  - 問題があれば諦める
  - これは作成できる枚数に限りがある申請をしているため管理しない
- [x] Tシャツデータ(matrk05)
  - 松江Ruby会議に限らず使用できるデザインのためgithub.com/{KatoAtsue,matsuerb}/matsuerb-tshirtのいずれかにコミットしたい
- [x] パンフレット(matrk07)
  - 本レポジトリにコミット
- [x] @KatoAtsue さん作成のロゴデータ
  - 松江Ruby会議に限らず使用できるデザインのためgithub.com/{KatoAtsue,matsuerb}/ruby-logoのいずれかにコミットしたい
  - @KatoAtsue さんが問題なければPublic Domainとか

特に最後の項について我々にとってありがたいリソースだと思うので第3回ミーティングで相談したい感じです。

**Comment by KatoAtsue** [comment]
@sho-h さんどうもありがとうございます。
管理していただけるとありがたいです。
しまねっこは利用時に再度申請すれば、いつでも利用できるそうです。（申請に1週間程度必要です。）
他のデザインについては、自由に使っていただければと思います。
よろしくお願いします。

**Comment by yoshiokaCB** [comment]
@sho-h さん

> 特に最後の項について我々にとってありがたいリソースだと思うので第3回ミーティングで相談したい感じです。

了解です。議題に上げて相談しましょう。

**Comment by sho-h** [comment]
@KatoAtsue 本当にありがとうございます！！すごく嬉しいです。可能であれば今日データをくださいませ。(今日でなくても問題ないです)

@yoshiokaCB どもです。よろしくお願いします。

**Comment by sho-h** [comment]
別のIssueを見て思いましたけど、昨年度の領収書と今年度の領収書もコミットしておきたいところ。(なんでもコミットしておいて使いまわしたい人なので、引換券とか作るならそれも)

**Comment by KatoAtsue** [comment]
@sho-h さん

どうもありがとうございます。
よろしくお願いします。

ロゴのカラー版は@yoshiokaCBさんが作成されましたので、@yoshiokaCB さんに掲載していただければと思います。

Tシャツの背景なしの画像はプレビューがわかりづらいので２種類アップさせていただきました。
すべて自由に使っていただければと思いますのでよろしくお願いします。

・Matsue.rbロゴ（モノトーン）
![matsuerb_logo_mono](https://cloud.githubusercontent.com/assets/5475425/9828782/88cc6f14-592d-11e5-9fc2-8934c11423ec.png)
・Matsue.rbロゴ（２色）
![matsuerb_logo_red](https://cloud.githubusercontent.com/assets/5475425/9828784/8ec089b4-592d-11e5-82fb-bff1be1555dd.png)
・Tシャツ（背景なし）
![matsuerb_tshirt_mono](https://cloud.githubusercontent.com/assets/5475425/9828785/9807f0ca-592d-11e5-9c84-1b42242db1c1.png)
・Tシャツ（背景あり）
![matsuerb_tshirt_background](https://cloud.githubusercontent.com/assets/5475425/9828789/9ea76866-592d-11e5-8896-4942e91020b8.png)

**Comment by sho-h** [comment]
https://github.com/matsuerb/matsuerb-logo を作って本日 @KatoAtsue さんに見ていただいてOKをいただきました。
Public Domainでお話ししていたのですが、それは日本だと法的な影響力が微妙という事だったので、近いCC0のレポジトリとして作りました。
上で載せていただいた画像をサンプルとしてコミットしてあり、あとは元データをいただいてロゴについてはコミットしておしまいです。その後でTシャツを進める感じにしようとおもいます。

**Comment by yoshiokaCB** [comment]
![rogo](https://cloud.githubusercontent.com/assets/4011289/10577138/8840479e-76a3-11e5-856f-4f546c1782ea.jpg)

**Comment by yoshiokaCB** [comment]
AI（イラストレーター）のデータとかはどうしましょうか？

**Comment by sho-h** [comment]
@yoshiokaCB それもコミットしてしまいたいですね。急ぎはしないので、定例会とかで受け取りたい感じです。

**Comment by sho-h** [comment]
ロゴデータのコミット完了しました。あとついでにパンフのデータの項にチェックを入れました。後でTシャツをどうするか考えます。05のは同じようにレポジトリを作ろうと思います。

**Comment by sho-h** [comment]
おしまい。
- [Tシャツデータ(05)](https://github.com/matsuerb/matsuerb-tshirt)
- [ロゴデータ](https://github.com/matsuerb/matsuerb-logo)
- パンフレット([docx](https://github.com/matsuerb/matrk/blob/master/doc/matrk07-pamphlet.docx), [pdf](https://github.com/matsuerb/matrk/blob/master/doc/matrk07-pamphlet.pdf))
