### ISSUE TITLE
写真撮影の主担当を決める

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk#34]
@tomo-k
@KatoAtsue

当日の写真撮影で漏れがあると嫌なので主担当を決めておきたいと思います。
前回と同様で基本的に手が空いていれば全員で撮影という形にしたいです。
ちなみに撮った写真は最終的に下記のアドレスにアップしようと思っています。

https://www.flickr.com/groups/2901550@N22/

| 時間 | プログラム | 主担当 |
| --- | --- | --- |
| 11:00 〜 11:05 | オープニング | @tomo-k |
| 11:10 〜 11:55 | ゲスト講演 | @tomo-k |
| 12:00 〜 13:30 | 昼休憩(LT) | @KatoAtsue |
| 13:30 〜 14:20 | 基調講演 | @inoh |
| 14:30 〜 14:45 | Matsue.rb | @inoh |
| 14:50 〜 15:05 | スプラウト.rb | @tomo-k |
| 15:10 〜 15:55 | プログラミングコンテスト | @tomo-k |
| 16:25 〜 16:40 | 学校で使用しているシステムのアップデートについての話 | @KatoAtsue |
| 16:05 〜 16:20 | プログラミング少年団 | @KatoAtsue |
| 16:45 〜 17:00 | Ruby Quiz | @inoh |
| 17:00 〜 17:10 | クロージング | @inoh |

**Comment by KatoAtsue** [comment]
了解です。
お二人が発表される時間帯を含めて担当させていただければと思います。

**Comment by tomo-k** [comment]
Ruby Quiz はレポート、LT は発表があるのでそれ以外の時間であれば担当できます。

**Comment by inoh** [comment]
私が午前中用事があって参加が微妙なところなので午後からにさせてもらえるとありがたいです。
とりあえず私の方で適当に担当を振るので問題があれば言ってください。

**Comment by KatoAtsue** [comment]
承知しました。
よろしくお願いします。
