### ISSUE TITLE
受付の準備について

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#36]
受付では以下の準備が必要かと思います。
- [x] お弁当代、懇親会費用は受付で受け取る（領収書の準備）
- [x] お弁当引換券の準備、懇親会入場券の準備
- [x] 受付名簿の準備
- [x] 釣り銭

**Comment by yoshiokaCB** [comment]
@ToruKurahashi さん。
前日に参加者一覧の名簿の準備をお願いできますか？（懇親会も分かるように）

@kaorimatsuoka さん
お弁当の領収書とお弁当、懇親会の入場券の準備をお願いできますか？

ちなみに領収書ってそれぞれじゃなくて懇親会費用と弁当代をまとめた物を準備するべきですかね？
その場合だと、
- 懇親会のみの領収書
- 弁当のみの領収書
- 懇親会・弁当の領収

って感じで準備した方が良いですかね？

**Comment by KaoriMatsuoka** [comment]
領収書を活用する人は経費精算する人ですよね。
その人が、懇親会費用と弁当代をまとめた物がよければ３パターンになるでしょうね。
領収書に必須の項目とかわからないので
@Takashi-U に作成をお願いできると助かりますが、いかかでしょうか？

お弁当の引換券、懇親会の入場券は私の方で作成します。

**Comment by Takashi-U** [comment]
前回は、ケータリングの関係があり、会場費込みにするため領収書を実行委員会で発行しました。

今回は、明確に弁当代と飲食代だけになりますので、領収書は各お店で人数分用意していただければ、実務的にはそれで充分かと思います。

この流れですと懇親会の領収書は受付時に渡せないので、入場券が懇親会費の預かりを兼ねているという旨（入場券と領収書を引き替える旨）を、受付時にお伝えする必要はありそうです。

いずれにせよ、運営する側もそれが楽なので、そんな感じでどうでしょう？
（もちろん、その辺りの流れは私で監修します。）

**Comment by KaoriMatsuoka** [comment]
@Takashi-U 　監修よろしくお願いします。

懇親会の領収書はお店で発行して頂けるのであれば、いいと思います。

お弁当代金は500円の領収書を数分作成は難しいようです。
こちらで作成しようと思います。
経費で落とす人だけなので、枚数はそんなにいらない気がします。
去年のシートが残っていれば、送ってもらえば、私の方で書き換えします。

昨年同様、受付で受け取ったお金は、うちべっこが封筒で管理でよいですか？
私の準備の分担は以下の通りでよいですか？
お弁当の引換券
懇親会の入場券
つり銭の準備
お弁当の領収書（雛形が入手できたら）

**Comment by sakasita001** [comment]
懇親会のお話がでましたので。
日曜の夕方に別件でお店に連絡をする必要があるので、その時に聞いてみようと思いますが時間的に大丈夫でしょうか？

**Comment by kenjiSugihara** [comment]
すいません、完全に乗り遅れてますが、領収書を実行委員会　吉岡代表名で、
よければ僕の方で作成しますよ！（慣れてますんでww）

その場合、
4800円の一般の懇親会領収書
1000円の学生の懇親会領収書
500円のお弁当の領収書
の3種類作成でお願いします。
必要人数分を用意致しますよ。

**Comment by kenjiSugihara** [comment]
@sakasita001 さん、ちなみに懇親会は、請求書払いでしょうか？当日現金払いでしょうか？

**Comment by Takashi-U** [comment]
っと @kenjiSugihara 神が降臨されたので、手を合わせて拝みたいと思います。（よろしくお願いして良いですか？）

**Comment by kenjiSugihara** [comment]
@Takashi-U さん、もちろん、お任せください！

ここでなんですが、19日夕方に、たぶんエスパークで京都から帰ってくる「あの坊主」と飲みますよ！

**Comment by sakasita001** [comment]
領収書作成の件、ありがとうございます。
よろしくお願いいたします。

懇親会の支払いですが、確認はしていません。
当日現金払いだと思っております。
確認したほうがよろしいでしょうか？

**Comment by Takashi-U** [comment]
まだ悟りを開いていない、あの坊主ですか！！僕はその日は行けませんので、よろしくお伝えください…。ちなみに、野毛屋の店長が、@kenjiSugihara 神が来られないと嘆いてましたので、謹んでご報告申し上げます。

あ、領収書ありがとうございます！よろしくお願いします！

**Comment by KaoriMatsuoka** [comment]
@kenjiSugihara　領収書よろしくお願いします。

@Takashi-U 　残りの分担はこれでよい？

受付で受け取ったお金は、うちべっこが封筒で管理

私の分担は
お弁当の引換券
懇親会の入場券
つり銭の準備

名簿は
@ToruKurahashi

**Comment by kenjiSugihara** [comment]
@sakasita001 さん、可能であれば請求書払いが助かりますので、お店にご確認くださいませ。
もちろん当日払いでもOKです。その場合、当日現金徴収額から懇親会費の不足額を
@sho-h さんに現金引き出して頂きますので。

@KaoriMatsuoka さん、25日の打ち合わせにいらっしゃれば、その際に領収書をお渡しします。もちろん当日朝でもOKっす。

@Takashi-U さん、残念！　　うぎゃー、I田さんに顔を見せにいかなきゃー
今日は怒涛の博多、東京、名古屋の３連チャン。1人G1-Cluimax、いくぜ！

**Comment by sakasita001** [comment]
請求書払いの件、畏まりました。
その際、請求書の宛名はいかがいたしましょうか？
FBでメッセージいただけると幸いです。

**Comment by kenjiSugihara** [comment]
@sakasita001さん、了解です！

**Comment by kenjiSugihara** [comment]
ちなみに、なぜ請求書払いがよいかと言いますと
出来る限り、収入、支出の状況を通帳の出入金記載と一致させることで、より正確な会計管理と、分かりやすく決算書類を作成でき、結果、円滑に監査頂けることになるからです。
もちろん現金対応も可能ではあります。
極力の請求書払いにご協力頂けますと助かります！

**Comment by KaoriMatsuoka** [comment]
@sakasita001
お弁当の領収書の宛名は「松江Ruby会議実行委員会」です。
@yoshiokaCB　懇親会も同じでよいですか？

**Comment by kenjiSugihara** [comment]
懇親会の請求書宛名の件、先ほどメッセンジャーで
@sakasita001 さんにお知らせしました。
@KaoriMatsuoka さんの仰る通り「松江Ruby会議実行委員会」でお願いしております！

懇親会、お弁当の領収書の発行名（受領者）も「松江Ruby会議実行委員会」で作成致します。

**Comment by KaoriMatsuoka** [comment]
@kenjiSugihara　
メッセンジャーと書いてありましたね。失礼しました。

参加者にお渡しする領収書の件ですが
前日打合せの時に、@yoshiokaCB に渡しておいてもらってよいでしょうか？
朝の杉原さんはちょっと不安(^^;

**Comment by yoshiokaCB** [comment]
皆様ありがとうございますm(_ _)m
名前必要でしたら適当に使ってください。（「松江Ruby会議実行委員会」でOKです。）
私の印鑑が必要でしたら @kenjiSugihara さんがお持ちですので問題ないですね。
（25日に慌てて印鑑押すでも大丈夫です。）

@KaoriMatsuoka さん 領収書受け取りの件、私は大丈夫です！

**Comment by kenjiSugihara** [comment]
@yoshiokaCB さん、お見込みのとおりお名前、印鑑は使わせて頂きますww

@KaoriMatsuoka さん、25日に呑み会がなければ大丈夫ですが、万一を考えて（←やっぱりww）
@yoshiokaCB さんにお渡しをしておきますね（五十嵐さんからの預かり物も含めて）。

**Comment by yoshiokaCB** [comment]
受付も無事終了したのでクローズします。
