### ISSUE TITLE
懇親会の準備について

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#37]
以下のことの検討が必要かと思います。
- [x] コース（時間）を決める
- [x] 乾杯の挨拶担当
- [x] LT司会進行担当
- [x] 締めの挨拶担当
- [x] 発表の順番を決める
- [x] LT開始時間を決める

**Comment by yoshiokaCB** [comment]
コースはBコース（4,800円　2時間半）に決まりました。

**Comment by yoshiokaCB** [comment]
乾杯は橋本さんか西田さんにお願いします。

**Comment by yoshiokaCB** [comment]
司会進行は坂本さんお願いします。

**Comment by yoshiokaCB** [comment]
タイムキーパーをきむらしのぶさんお願いします。

**Comment by yoshiokaCB** [comment]
閉めは吉岡、杉原さんでします。

**Comment by yoshiokaCB** [comment]
LTは18:30からスタート。

**Comment by sakasita001** [comment]
@ToruKurahashi さん

懇親会の予約人数について、今週末に仮の人数を入れてほしいとの店からの要望がありました。
日曜夕方あたりで懇親会の登録人数を把握したいのですが、教えて頂く事は可能でしょうか？

**Comment by yoshiokaCB** [comment]
無事終了したのでクローズします。
