### ISSUE TITLE
会場の準備について

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#38]
以下、思いつく準備が必要な物をリストアップしました。
適宜修正をして確認をお願いします。
- [ ] 配布物の設置場所の確保
- [ ] wifi環境
- [ ] マイク（音響）
- [ ] プロジェクター・スクリーン（ツイッター用と発表用）
- [ ] 電源タップ
- [ ] LANケーブル（中継との接続用）

※ラボのものを借りる必要がある場合は、松江市の方に確認が必要です。

また、片付けを作業の確認もお願いします。

**Comment by sho-h** [comment]
> ※ラボのものを借りる必要がある場合は、松江市の方に確認が必要です。

#17 によると(懇親会向けではありますが)許可はいただいてるみたいです。

あとWifi環境については前に @kenjiSugihara さんがどこかに書いておられたのを集約しておきたいんですがどこでしたっけ...(忘れちゃった...orz)

**Comment by sakasita001** [comment]
@sho-h さん
お疲れ様です。
懇親会の備品に関してですが、OSSよりお借りするのはケーブル類のみです。
残りのものは懇親会会場の備品となります。

**Comment by sho-h** [comment]
お疲れさまです！

という事は会場向けで追加があって、申請になにか必要な事があれば対応が必要ですね。

**Comment by sho-h** [comment]
> あとWifi環境については...

#10 でした。

**Comment by yoshiokaCB** [comment]
テルサから借りる物
- 音響ワゴン一式
- 映像ワゴン一式
- ワイヤレスマイク3本
- プロジェクターケーブル2本
- マイク代
- 演題
- 司会者台

**Comment by amidaku** [comment]
床置きマイクスタンド１本追加お願いします。

**Comment by sho-h** [comment]
会場、受付、懇親会と別々に借り先別のチェックリスト作った方がよさそうですね。

**Comment by sho-h** [comment]
ラボからは電源用のドラム(2個)と電源用のタップ。許可は取ってあるとの事ですが、改めて報告を行うというTODOあり。

**Comment by yoshiokaCB** [comment]
- プログラムを印刷する（吉岡準備　松江市さんにお願いする）
- SSID表示の紙を準備（高田さん準備）

**Comment by amidaku** [comment]
Matzパネル！

**Comment by teeta32** [comment]
ホワイトボードを1台ラボからお借りする。

**Comment by amidaku** [comment]
適切なissueが見つからなかったので、ココに書きます。
懇親会に向けてラボからケーブルを借りるとありましたが、先日の打合せの際に確認出来たところでは必要なのはHDMIケーブルということで、ラボにはHDMI機材が無くHDMIケーブルも無いため、ラボから借りるものは無くなりました。
懇親会後にラボに返却のために立ち寄ることも無くなりました。（たぶん）

で、 @sakasita001 さんに連絡です。
 HDMIのケーブルについて先日の打合せでいろいろ話をしましたが、社内探してみたところAmazon BASIC謹製HDMI-7.6mケーブルがありました。
これなら貸し出すことが可能です。
ただしmini-PortやDVI、アナログRGBからの変換アダプタは持ち合わせておりませんので、調達等調整をお願いします。（アナログRGBからの変換器は高価なので難しいと思いますけどね）

**Comment by sakasita001** [comment]
@amidaku さん

ケーブルを探していただきありがとうございます。
当日の予備ケーブルとして使用させていただければ嬉しいです。

PCとHDMIの変換器は@ToruKurahashi さんよりお借りする事になっておりますので、大丈夫かと思います。

ありがとうございます。

**Comment by teeta32** [comment]
順調に開催が進んでいますので、本件は終了します。
