### ISSUE TITLE
会場で利用する機材(テルサから借りる機材)について

### ISSUE THREAD

**Issue by teeta32** [matsuerb/matrk#39]
会場で利用する機材をテルサへ予約申請する。
(松江Rubyで予約申請する。予約している大会議室と紐付けてもらう。)
- 予約申請する機材
  - 音響ワゴン一式
  - 映像ワゴン一式
  - ワイヤレスマイク3本
  - プロジェクターケーブル2本
  - マイク(有線) 2 本
  - 演台 1台
  - 司会者台 1台
  - 床置きマイクスタンド 1 本

予算で見込んでいる機材に床置きマイクスタンド1本を追加する。

高田が来週(9/14の週)にテルサに予約を入れる。

**Comment by teeta32** [comment]
テルサに機材の利用を予約しました。
- 予約申請した機材の一覧
  - 音響ワゴン 一式 (ワイヤレスマイク 1 本を含んでいます。)
  - 映像ワゴン 一式
  - ワイヤレスマイク 1本
  - プロジェクターケーブル 2本
  - マイク(有線)           2 本
  - 司会者台 1台
  - マイクスタンド(床上型) 1 本 (マイクスタンドは有線用です。)

予約の報告と確認事項を記します。

当日の進行から演台(演壇)とマイクの本数について @yoshiokaCB さん確認をお願いします。
また、中継用のマイクスタンドについて @amidaku さん確認をお願いします。
- 演台(演壇)について

部屋に備え付けで用意されているので演台は予約不要でした。
演壇(一段高くなる(高さ 20 cm 程度))の貸出があるそうです。
費用が別途かかりますが、演壇を利用する予定でしょうか。

現状は演壇の予約していませんが、演壇がいる場合は予約しますのでコメントください。
- マイクの本数について

大会議室で利用できるワイヤレスマイクは 2 本までだそうです。
音響ワゴン一式にワイヤレスマイクが 1 本含まれているので、
追加のワイヤレスマイクを1本予約しました。

予約を予定していた本数からマイクが1本減っているので、
有線マイクの追加があればコメントください。(マイクの追加は当日でも可能です。)
- マイクスタンド (中継用のマイクスタンド)

有線用のマイクスタンド(床上型)を予約しています。
無線用のマイクスタンドもあります。無線用のマイクスタンドが
よければ予約を変更しますので連絡をお願いします。

**Comment by amidaku** [comment]
OKです。

**Comment by teeta32** [comment]
岩石さん、確認ありがとうございます。了解しました。

**Comment by teeta32** [comment]
こちらも返却しましたので終了します。
