### ISSUE TITLE
写真の共有場所を確保する

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk#4]

**Comment by yoshiokaCB** [comment]
@inoh さん
Flickrに前回の写真をアップしてみました。確認できるでしょうか？
https://www.flickr.com/groups/2847723@N21/pool/

確認できるようでしたら、次に「MatsueRubyKaigi07」のグループを作成するので、撮影した方がそちらにアップできないか試してみたいです。

**Comment by inoh** [comment]
私の方で見れることを確認しました。
Flickrにログインしている状態であればグループに入ってアップできることも確認できました。
これなら07でもグループを作ってもらえらば簡単にできそうですね

**Comment by yoshiokaCB** [comment]
グループ作成完了。

https://www.flickr.com/groups/2901550@N22/

写真撮影部隊はこちらにアップしてもらう用にしたいと思います。
flickerのアカウントが必要なので、撮影をお願いしている方はまたアカウント取得をお願いします。

**Comment by yoshiokaCB** [comment]
![2015-07-12 12 23 24](https://cloud.githubusercontent.com/assets/4011289/8887842/2b52d370-32cf-11e5-8bef-8e1695693003.png)
![Uploading スクリーンショット 2015-07-12 12.23.24.png…]()
