### ISSUE TITLE
会場で利用する機材(オープンソースラボからお借りする機材)について

### ISSUE THREAD

**Issue by teeta32** [matsuerb/matrk#40]
松江Rubyが、オープンソースラボから機材をお借りすることを松江市様から了承を頂いた。

ただし、お借りする機材を松江市様へ改めて報告することがTODOとして残っている。
来週(9/14)の週に松江市様に下記の機材を開催当日に松江Rubyがお借りすると高田が連絡する。
- オープンソースラボからお借りする機材
  - LAN ケーブル 10 本
  - プロジェクターとスクリーン
  - 電源タップ 10 本
  - ホワイトボード 1 台
  - Matz パネル 1 枚
  - 電源ドラム 2 台

**Comment by teeta32** [comment]
上記の機材をお借りしたいことを松江市様に連絡して了承をいただいた。
松江Ruby会議の終了後に、機材の返却を高田が松江市様へ報告する。

**Comment by sho-h** [comment]
個人の名前が載っていたので一応「松江市様」だけに揃えました。

**Comment by teeta32** [comment]
お手数をおかけしました。個人名を載せない配慮ができておらず申し訳ありませんでした。

**Comment by sho-h** [comment]
義務でもないので、皆で意識するのもなかなか難しいところですよね。とりあえずは消せばいいので皆でなるべく注意するとかがいいんですかねぇ。

**Comment by yoshiokaCB** [comment]
そもそもは自分が先に書いてましたね(^^;;)
すみませんm(_ _)m

**Comment by amidaku** [comment]
主犯（首謀者）は私です。
ココで書いてもあれなので、また皆さんとお会いしたときに話させてください。
とりあえず気をつけましょう。お互いに。

**Comment by sho-h** [comment]
何のためかとか、何を思ってそう提案してるかとか、そもそも今の路線で進めるかとかありますもんね。

**Comment by teeta32** [comment]
備品と機材をラボに返却しました。返却済みを連絡しました。
本件は終了します。
