### ISSUE TITLE
会場設営について

### ISSUE THREAD

**Issue by teeta32** [matsuerb/matrk#42]
昨日のミーティングで決定した内容を記します。
- 机と椅子の配置
  机と椅子は基本的に動かさない。(演台などの都合で調整する程度にする。)
- ネットワークの準備
  - 無線LANアクセスポイントを2台設置する。
  - 無線LANのSSIDとパスワードを掲示する紙を用意する。(@teeta32, @sada さん)
  - 演台に有線LANを1本用意する。
  - 動画配信席用に LAN ポートを用意する。
    (@amidaku さんに動画配信席へ引く長いLAN ケーブルの準備がある。)
- 電源の用意
  - 電源ドラム
    - 2台設置する。1台を演台付近に、もう一台を動画配信席に付近に設置する。
  - 電源タップ
    - ノートパソコンの充電に使えるように、会場の壁面の各コンセントに電源タップを2,3台接続する。
- その他
  オープンソースラボから以下を会場に運び設置する。
  - ツイート表示用のプロジェクターとスクリーン
  - ホワイトボード
  - Matzパネル機材

**Comment by teeta32** [comment]
会場で利用する機材の一覧を記します。
- 機材の一覧
  - オープンソースラボからお借りする機材
    - LAN ケーブル 10本
    - プロジェクターとスクリーン
    - 電源タップ 10本
    - ホワイトボード 1台
    - Matz パネル 1枚
    - 電源ドラム 2台
  - Ruby World Conference(一畑電鉄様)からお借りする機材
    - 無線LANルータ 2台
  - テルサから借りる機材
    - 音響ワゴン一式
    - 映像ワゴン一式
    - ワイヤレスマイク 3本
    - プロジェクターケーブル 2本
    - マイク(有線) 2本
    - 演台
    - 司会者台
    - 床置きマイクスタンド1本

**Comment by kenjiSugihara** [comment]
RWCのルーター２台ですが、例えば24日、又は25日にNaCl様サテライトオフィスに持ってきてもよいでしょうか？

**Comment by teeta32** [comment]
無線LANルータを24日にお借りすることになりました。多謝です。

**Comment by teeta32** [comment]
会場の講演者と司会者の机をどうしましょうか。

レンタルリストに、演台と司会者台があるのでこれを使うでしょうか。

演台は立って話をすることになると思うので、いつもラボでイベントをするときのように
会場の長机一台を講演者用に用意して座って講演いただくのがよいでしょうか。

演台は会場に備え付けですが、司会者台は別途レンタルなので不要であれば
キャンセルできます。

**Comment by yoshiokaCB** [comment]
@teeta32 さん
今のところ、演台は一応準備しておいた方が良いかと思います。
ちなみに前日でも変更は前日とか当日でも変更はできましたかね？

@amidaku さん
念のためお聞きしますが、通常のテーブルで講演した場合に撮影で何か不都合がありますか？

@Takashi-U 
司会をお願いしてますが、司会者の台は必要ですか？
前の方に座ってもらってしゃべる時だけ前に行くって感じで良いかと思いますが。
（というか特に司会に関して打ち合わせもしてないよね。。。前日に少ししようと思ってました。ごめんなさい。）

**Comment by teeta32** [comment]
備品のレンタルの変更が当日でもできるか確認します。
(多分、大丈夫だと思います。)

**Comment by Takashi-U** [comment]
@yoshiokaCB 司会の台は必要無いですが、大人の事情で、プログラミングコンテストの景品紹介の時間が必要です。その時に、もしかしたら台がいるのかもしれません。（プログラミングコンテストの時に会場がどんな感じか分からないため念のため…）

それと、懇親会はちょっと難しい情勢になりました。。 @sakasita001 さん、せっかく設営いただいているのに申し訳ないです。。

**Comment by yoshiokaCB** [comment]
@teeta32 さん
司会と講演ともに台有りでお願いします！

**Comment by teeta32** [comment]
了解です。

演台に加えて演壇をレンタルできます。演壇(一段(20cmくらい)高くする壇)はいりますか？

**Comment by teeta32** [comment]
無線LANルータ5台を届けていただきました。ありがとうございました。

**Comment by amidaku** [comment]
中継関係の配置とケーブル系統を考えました。

![ruby 07](https://cloud.githubusercontent.com/assets/772004/10065026/8de5da94-62ba-11e5-8833-4ba2967487aa.png)
![ruby 07](https://cloud.githubusercontent.com/assets/772004/10065027/90212da4-62ba-11e5-8a3d-914188a628b9.png)

系統図の方は、細い線が中継卓上の短いもので太い線が床などを這うものです。また赤の線は長距離を敷設する感じです。

中継卓は真ん中の部屋最後方か一番後ろのテーブルの位置に陣を取らせて頂くことにさせてください。持ち込むケーブルが届くかどうかでどちらにするか決めます。
真ん中の後方に取る理由は、セミナーやコンテストなど様々なコンテンツにカメラ位置を対応させる為で、出来るだけ後ろの方が映像から高さを感じなくなるのでそのようにいたしました。
真ん中後ろに会場全体やステージ付近全体（スライド）撮影用のカメラを置き、あと2台で臨機応変にステージ付近でのコンテンツ進行に対応したいと考えています。（技量に無理かもしれないですが...

**Comment by yoshiokaCB** [comment]
@teeta32 さん

> 演台に加えて演壇をレンタルできます。演壇(一段(20cmくらい)高くする壇)はいりますか？

多分なくて大丈夫です。

それと、ラボから借りるリストに以下の追加をお願いします。
- PC（twitter表示用のMac）
- 壁に貼る用のタイムテーブル用紙（借りるわけではありませんが）

詳細は明日にでもお伝えします！
よろしくお願いいたします。

**Comment by teeta32** [comment]
演壇について了解です。(当日でも演壇のレンタルは可能です。)

ラボからお借りする機材の追加も了解しました。
追加のMacとタイムテーブル用紙もラボからお借りする了承を頂いているでしょうか。
(お借りする連絡がtodoで残っていないか確認させてください。)\

リストに追加の機材を加えて、以下に再掲します。
- ラボからお借りする機材
  - LAN ケーブル 10本
  - プロジェクターとスクリーン
  - 電源タップ 10本
  - ホワイトボード 1台
  - Matz パネル 1枚
  - 電源ドラム 2台
  - PC(twitter 表示用のMac) 1台
  - 壁に貼るタイムテーブル用紙(借りるわけではないが、ラボから会場へ持ち込む。)

**Comment by yoshiokaCB** [comment]
タイムテーブル用紙はお願いして準備してもらってますので、大丈夫です。
Macを借りることは確認中ですので少々お待ちください。

**Comment by yoshiokaCB** [comment]
Macも了承もらいました！

**Comment by teeta32** [comment]
了解です。おつかれさまです！

**Comment by teeta32** [comment]
ワイヤレスマイクの本数の変更などがありますので、テルサからレンタルする機材の一覧を再掲します。
- テルサからレンタルする機材
  - 音響ワゴン 一式 (ワイヤレスマイク 1 本を含んでいます。)
  - 映像ワゴン 一式
  - ワイヤレスマイク 1本
  - プロジェクターケーブル 2本
  - マイク(有線) 2 本
  - 司会者台 1台
  - マイクスタンド(床上型) 1 本 (マイクスタンドは有線用です。)

**Comment by teeta32** [comment]
こちらも、順調に開催が進んでいますので終了します。
