### ISSUE TITLE
会場の利用時間の申請

### ISSUE THREAD

**Issue by teeta32** [matsuerb/matrk#43]
テルサへ機材の利用の予約へ行ったときに会場の利用時間を尋ねられました。
@yoshiokaCB さん、テルサに会場の利用時間は何時から何時で伝えましょうか。

当日9時から会場の準備をするので、利用開始は9時として終了は何時が良いでしょうか。
終了は片付けにどのくらいかかるかですね。

なお、テルサ事務局から 18:00 以降の利用は、午後の利用から夜間の利用に切り替わるので、
18:00 以降の利用がある場合は、午後の利用から追加で費用が発生するとのことでした。

**Comment by amidaku** [comment]
おそらく片付けが18時までに終わるかどうかということになると思います。
一番片付けが遅いのは、常に私なので本当に申し訳ないです。

17:10終わりでおそらく１時間以内に片付けは終わらないですが、部屋からは荷物を出して、なんとか18時には部屋を返却する体裁をとろうと思います。
最悪はラボに運んでもらって片付けをしようと思います。よろしくお願いします。

**Comment by yoshiokaCB** [comment]
再度確認をしますが、丸一日押さえておられるはずです。（予算もそれで出されているはず。）
ですので、夜間も利用でOKのはず。。。
詳細は明日にでも確認します(^^;;)

…部屋の利用は一日中だけど、マイクセットとかの利用だけ18時までって出来るんですかね？

**Comment by amidaku** [comment]
名前を気軽に書かないように！

**Comment by yoshiokaCB** [comment]
はい。気をつけます。

**Comment by teeta32** [comment]
テルサに確認しました。
部屋の利用は一日中だけど、マイクセットなどの機材の利用は18:00までにできるそうです。

18:00前にテルサの事務局にマイクセットなどの返却を連絡をすれば、機材の引き揚げをされるそうです。

**Comment by yoshiokaCB** [comment]
> 部屋の利用は一日中だけど、マイクセットなどの機材の利用は18:00までにできるそうです。

でしたら、マイクセットなどは18時に返す段取りで進めてください。
当日も返すものを先に片付けるように調整しましょう。

**Comment by teeta32** [comment]
了解でーす。

**Comment by teeta32** [comment]
会場は 22:00 まで借りていただいています。会場の片付けが 18:00 を越えても大丈夫です。
レンタル機材は18:00までに返却します。

会場をお借りしている時間は上記の通りですので、本件は終了します。
