### ISSUE TITLE
会場の飲食の申請について

### ISSUE THREAD

**Issue by teeta32** [matsuerb/matrk#44]
会場で飲食をする場合は、飲食の申請が要るとテルサから話がありました。
会場で弁当を食べるので申請が要ります。

申請書のPDFは以下から入手できます。
http://www.sanbg.com/terrsa/info/pdf/catering.pdf

申請書の内容を連絡いただけば、申請書に記入して提出します。
申請書の記入内容は @yoshiokaCB さんにお願いで良いでしょうか。

**Comment by yoshiokaCB** [comment]
了解っす！
記入した物をお送りします！

**Comment by yoshiokaCB** [comment]
搬入業者を調べますので、少々お時間ください。

**Comment by teeta32** [comment]
本件、申請が完了しました。
