### ISSUE TITLE
動画撮影のアングルについて

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#45]
@amidaku さん

ちょっと時間があきましたが、プログラミングコンテストとRubyクイズの動画撮影のアングルについて決めたいと思います。

まず、プログラミングコンテストは本編で上位者のコードを発表すると公言もしている関係で、それを期待した視聴者がいることが想定されます。
ですので、コードを見てもらうことが最優先だと思っています。
（ある程度割り切りは仕方が無いかと思います。）

テレビのイメージで考えると将棋とか囲碁の解説とかのイメージしてます。（盤面だけでなく解説者が端に入る感じ）
解説する人がスクリーンに近い立ち位置で、レーザーポインターなどを使いながら解説って感じを想定しています。問題はそれで画面のコードが読めるかですよね(^^;;)
ちなみに今回のプロコンはコードゴルフ大会になってきたので、コードを大きめに写すことも出来そうな感じはあります。

基本的にはRubyクイズに関しても同じように考えています。
（@shinob さん Rubyクイズで何かご意見あればお願いします！）

**Comment by amidaku** [comment]
**将棋、囲碁の解説のイメージ！！**
わかりやすい例えでした。了解です。

中継機材リストと配置を考えて見ます。
今回はPCの画面出力を直接キャプチャするのは止めにします。

また今の時点での考えですが、真ん中列の最後方に中継班は陣取ろうと思います。
最後方が机の並びの最後列なのか、部屋の一番壁際にテーブルをおいて陣取るかは今のところ検討しているところです。
できるだけ参加の方々の邪魔にならない位置にしようと思います。

**Comment by yoshiokaCB** [comment]
今回は会場のキャパに余裕があるので、割と広めに使ってもらって大丈夫ですよ。

…っていうか来場者をもっと増やさなきゃですけどね(^^;;)
がんばります！

**Comment by amidaku** [comment]
今回はふらっとさん対策が要らないのでその辺りは楽ですねw...スレチでした。ごめんなさい。

**Comment by amidaku** [comment]
#42 にて配置等書きました。

**Comment by yoshiokaCB** [comment]
@amidaku さん
確認しました。
ありがとうございます！
少しレスチですが、人数が会場のキャパに対して少ないので、後ろの席は間引く必要がありそうですね。

**Comment by amidaku** [comment]
今Doorkeeperで参加人数を確認した際に気がついたこと。
「なぜか自分の名前を非掲載にしてる...」
まあそれはどうでも良い話ですが、会場が公表しているキャパはテーブル3人掛けなので、×2/3と考えるとまずまずと思いますよ。
間引いて、会場後ろに人がたまらないように **変な** スペースは作らない方が良いかもしれないですね。

**Comment by yoshiokaCB** [comment]
撮影した動画の扱いについては別のissueを作成した方が良いかと思いますのでクローズします。

**Comment by amidaku** [comment]
同感です。対応ありがとうございます。
後ほど当方でissue立てます。
