### ISSUE TITLE
第四回　直前ミーティング開催について

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#46]
前日に全体ミーティングをしたいと思います！

| 日時 | 場所 |
| --- | --- |
| 9月25日（金）19:00〜21:00 | オープンソースラボ |

当日は基本的にTシャツの受け渡しがメインの目的です。
あとはそれぞれ最終準備の確認となります。

今回は特にdoorkeeperで参加確認はしませんので、お時間ある方は、ぜひご参加をお願いします！

プログラミングコンテストの担当の方はコードの上位コードのチェックと当日の打合せをしたいと思いますのでよろしくお願いします。
担当は　@sho-h @Takashi-U @ToruKurahashi @nobyuki @yoshiokaCB の5名です。

@shinob さん
当日クイズの資料をお渡ししたいと思いますのでよろしくお願いします。

その他、ミーティングで打合せが必要なことや確認が必要なことなどありましたら、ご指摘いただけると助かります。（自分の方でもissueを眺めながら漏れがないか確認してみます。）

よろしくお願いいたします。

**Comment by sho-h** [comment]
今思いつく範囲だと支払いの流れを相談しておきたいですね(相談は始めてるので、TODOで残ってるという点だけのメモ)。

**Comment by amidaku** [comment]
思いついたので書いておきます。

次の枠割り誰がするのか確実にしておいた方が良いと思いました（他のイベントで混乱が起きたことがあるので）。
- 朝一、テルサ事務局へ行って受付
- 会場の開場（シャレじゃ無く）
- レンタル備品の員数の確認
- ラボからお借りする備品の員数確認
- ラボから借りた備品が確実に返却されているか確認
- 部屋返却時のレンタル備品員数の確認
- テルサへの返却対応

あと、当日追加で借りる必要がある備品があったら、誰に連絡すべきか決めておいた方が良いですね。

**Comment by amidaku** [comment]
相談とかじゃないけど、入り口ドア付近は立って見る人がたまりやすいので、部屋の中程に入って頂くように促すように声がけは要りますので、その辺りの話とか、スタッフも講演を見るのであれば壁際に立って見るんじゃ無くて、ちゃんと着席してみるようにとかそういう周知はしても良いかも。

**Comment by yoshiokaCB** [comment]
@sho-h さん
ありがとうございます！
そうですね。その辺はissue作って管理したほうが良いかもしれませんね。
また週末に整理します。

@amidaku さん
ありがとうございます。
会場準備の担当者と相談してみます。会場準備のissueがあるのでまた追記しておきます。

> 相談とかじゃないけど、入り口ドア付近は立って見る人がたまりやすいので、部屋の中程に入って頂くように促すように声がけは要りますので、その辺りの話とか、スタッフも講演を見るのであれば壁際に立って見るんじゃ無くて、ちゃんと着席してみるようにとかそういう周知はしても良いかも。

そうですね。これも徹底しましょう！

**Comment by teeta32** [comment]
項目を整理して頂いた以下について担当できます。
(レンタル備品とラボからお借りする備品の調整をしていますので。)
- レンタル備品の員数の確認
- ラボからお借りする備品の員数確認
- ラボから借りた備品が確実に返却されているか確認
- 部屋返却時のレンタル備品員数の確認
- テルサへの返却対応

備品のレンタルの申請を先日したので、当日追加で備品のレンタルをするときの窓口も担当できます。

**Comment by amidaku** [comment]
@teeta32 さん、ラボ備品とテルサ備品は、ほぼ同時進行なので二人に分けた方が良いと思いますよ。

**Comment by teeta32** [comment]
会場担当に @sada さんが入っています。
@sada さん、備品のレンタルに関する確認を分担して担当していただけますか。

一人ではラボに降りたりで不在の時間を作ることに思いいたりませんでした。

**Comment by sada** [comment]
@teeta32 さん、当日するレンタルされた備品の確認作業でしょうか。
当日の作業ならば対応できるかと思います。

**Comment by teeta32** [comment]
@sada さん、当日の作業です。
当日にラボからお借りする備品の確認作業をお願いしたいです。
- ラボからお借りする備品の員数確認
- ラボから借りた備品が確実に返却されているか確認

当日テルサからレンタルする備品の確認作業を私が担当しようと思います。

**Comment by sada** [comment]
@teeta32 さん、ラボからお借りする備品の確認作業、了解致しました。
