### ISSUE TITLE
プログラミングコンテストの景品をサイトに掲載する。

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#47]
1位　Happy Hacking Keyboard Pro2 英語配列（黒：印字有り）
2位　プログラミング関連の書籍
3位　プログラミング関連の書籍

その他、面白いコードには特別賞として、書籍を準備

@inoh さん
これだけの情報でサイトに掲載は可能ですか？

**Comment by inoh** [comment]
了解です！
わかる範囲でとりあえず修正しておきます。

**Comment by yoshiokaCB** [comment]
ありがとうございます！助かります！

**Comment by inoh** [comment]
@yoshiokaCB 
事後報告になっちゃうんですがホームページにこんな画像を貼っちゃいました。

https://github.com/matsuerb/matsuerb-nanoc/blob/bfa4c90ee6eafbdb3501a08c069df21d313484c7/static/matrk07/img/detail_hhkb-pro2-b-1.jpg

著作権？的によくないかもしれないのでもし現物がもうあるなら撮った写真とかってもらえるもんですか？

**Comment by inoh** [comment]
ちなみにホームージはこんな若干悪趣味なページになっているので画像小さくしろとかなら直します。

<img width="606" alt="2015-09-18 13 15 05" src="https://cloud.githubusercontent.com/assets/1096516/9951847/56960a26-5e07-11e5-9a9f-a3faa905ce53.png">

**Comment by yoshiokaCB** [comment]
@inoh さん
使わない方向がいいですかね。

@Takashi-U さん
現物ってもう届いてます？
梱包とかで写真とか難しいかな？

もしくはflickrの写真使いましょうか？
https://www.flickr.com/photos/abhisawa/10662596393/in/photolist-hfdAqR

以下にflickrの画像の使用方法が書いてありました。
http://naglly.com/archives/2009/01/flickr.php
Original Update by XXX"（XXXは著作者の名前とその著作者のFlickrIDのリンク）でOKみたいですよ。

まぁ、実物と多少違いますが「写真はイメージです。」とかつけとけば大丈夫だと思います。

**Comment by amidaku** [comment]
@yoshiokaCB ｲｲﾈ! みんな得意になったCCです！
ぁ、自分が使ってるやつ写真撮りましょうか？（使用感があってだめかな？）

**Comment by sho-h** [comment]
↑の画像はライセンスがCCですね(Some rights reservedのところ)。前と同じ感じにしつつ、名前とかは↑のようにするのがよさそうですね。

**Comment by sho-h** [comment]
いつもちょっと @amidaku さんに出遅れるぜ...

**Comment by sho-h** [comment]
ところでとりあえずマージして公開前に議論しようと思ったんですけど、よく考えたらそれじゃだめでした。失敗失敗。

今晩少し巻き戻してforce pushかなにかでレポジトリから元の画像を完全に消す事にします。

**Comment by Takashi-U** [comment]
もう届いています…が、商品なので開けてしまうというのはチョットどうかなと思ったりします。
本件、心当たりがありますので、聞いてみます。

**Comment by yoshiokaCB** [comment]
@Takashi-U 
もし使用可能なものがあれば @inoh さんに渡してあげてください。
よろしくですm(_ _)m

@amidaku さん
勉強したことを早速実践できたようで、どやしそうです(･`ω･)
とりあえず、心当たり当たってもらって、なければflickrの写真を使うでいいかなと思います。（使用感は問題ないと思ってますが）

**Comment by Takashi-U** [comment]
問い合わせのメールに対して返信が無く祝日に突入したため、返事自体が見込めない状況になりました…。すみませんが、代替手段が必要となります。

ドヤする感じでお願いできればと。。

むろん、返信が来たらすぐに連絡致します。

**Comment by yoshiokaCB** [comment]
了解っす。

@inoh さん
flickrの写真を使うパターンでお願いします！

**Comment by inoh** [comment]
いろいろ確認いただいてありがとうございます！
flickrでホームページの画像差し替えておきます。

**Comment by sho-h** [comment]
画像を差し替えたので、前の画像は消してpush -fしたので気をつけてください。

**Comment by sho-h** [comment]
すみません、ちょっと以下の2点が気になっていましたが、対応の時間が取れなさそうなのでとりあえず反映しました。
- HHKBのライセンス文のチェック( @ToruKurahashi さんのFAQとの突き合わせ)
  - 最悪開催後に僕が確認します
- 2位以降の景品(橋本が1つ宿題を抱えていますがそれはこれから@nobyuki先生にお願いする予定)

あとこれから急用が入る可能性が出てきたので、当日までに再度更新ができるとは限らない状態です。一応以下に反映の手順が残してあるので、今回はそれを参考にどなたかお願いします。公式サイトのPRの取り込みも含めてすみませんがお願いします。
- https://github.com/matsuerb/matsuerb-nanoc#公式サイトへの反映

**Comment by inoh** [comment]
@Takashi-U さんに正規に確認いただいた画像で差し替えを行いました。
とりあえず修正版のプルリクが送っておきました。

https://github.com/matsuerb/matsuerb-nanoc/pull/314

この画像についてはライセンス表示等は不要ということでご確認いただいております。

**Comment by yoshiokaCB** [comment]
掲載完了なのでクローズします。

**Comment by inoh** [comment]
プルリク取り込みまだやってなかったっす！
