### ISSUE TITLE
撮った写真をアップする

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk#49]
撮った写真は下記のFlickrグループで共有します。

https://www.flickr.com/groups/2901550@N22/

会場で撮影した写真は各々アップをお願いします。
アップする際はFlickrアカウントが必要になるのでFlickrにログインの上アサインお願いします。
もしFlickrアカウントをお持ちでない方は私の方でもアップするので撮影後またください！

**Comment by KatoAtsue** [comment]
@yoshiokaCB さん
@inoh さん
Flickrのサイトで「join request」をしましたので、よろしくお願いします。

**Comment by yoshiokaCB** [comment]
@KatoAtsue さん @tomo-kさん
承認しましたので、ご確認をお願いします！

色々と勘違いしており承認が遅くなりました。
すみませんでしたm(_ _)m

**Comment by yoshiokaCB** [comment]
@inoh さん
07のメンバーに加わってないようですが？
念のため以下のページを確認してみて、アップできなかったら、リクエストをお願いします！

https://www.flickr.com/groups/2901550@N22/

**Comment by inoh** [comment]
あ、ごめんなさい。グループ作り直してグループ抜けちゃいましたw
じゃあ吉岡さんが元々作られたグループで共有ということでアサインしなおしますね

**Comment by yoshiokaCB** [comment]
あっ、どっちでもいいですよ。
@inoh さんが作ってもいいかもって話をしてたけど結論がはっきり出てなかった気がして、とりあえずリクエストの承認をしたところです(^^;;)

**Comment by inoh** [comment]
そもそもに私がFlickrのことを全然知らずに吉岡さんまかせにしたのがよくないと思ってました。
自分で作ってみるといろいろと勉強になってよかったですw
じゃあ吉岡さんの作られたグループで共有させてもらいますね

**Comment by yoshiokaCB** [comment]
了解っす！

**Comment by KatoAtsue** [comment]
@inoh さん
@yoshiokaCB さん
了解です。よろしくお願いします。

**Comment by inoh** [comment]
とりあえず私が持っている写真はグループに追加しました。
写真担当外でも写真がほしい方がおられますかね？
Flickrアカウントを持っている方なら
https://www.flickr.com/groups/2901550@N22
にアサインいただければ見れると思います。

**Comment by nishidayuya** [comment]
準備のときの写真を上げるためにjoin requestしました．確認お願いします．

**Comment by inoh** [comment]
@yoshiokaCB 
@nishidayuya さんのjoin承認お願いします！

**Comment by nishidayuya** [comment]
アップロードしました!

**Comment by sho-h** [comment]
ざっと見た感じ、以下の4人の方の写真があるようですね。(見落としてたらすみません)
- @KatoAtsue さん
- @nishidayuya さん
- @Takashi-U さん
- @inoh さん

後はどんな作業が残ってる感じでしょう？以下とかかなぁ。ものによっては誰かが対応してもいいかもしれません。1/23の定例会くらいでは終わらせてしまうくらいで、できる範囲でやるとかでよさそうですね。:)
- [ ] 上を確認するに @tomo-k さんのupload待ち?
- [ ] やる場合は06などと同じようにセクションごとに分けて見れるようにする
- [ ] 問題のある写真が紛れてないかチェック
- [ ] 公式サイトの更新は #56 で @sho-h が対応しようかと思うので、URLの一覧を #56 に記載

**Comment by tomo-k** [comment]
遅くなってすみません。とりあえず、SDから救出できたデータだけアップロードします。
完了後再度連絡させていただきます。

**Comment by sho-h** [comment]
@tomo-k ありがとうございます！！できる範囲で大丈夫です。:+1:

**Comment by tomo-k** [comment]
@sho-h さん
正常なデータのアップロードが完了しました。
遅くなってすみませんでした。

**Comment by sho-h** [comment]
@tomo-k ありがとうございます！！まぁ僕なんて1年以上置いといたIssueありますから、誤差ですよ。:)

**Comment by sho-h** [comment]
@yoshiokaCB さんとさきほど相談してこれで完了とする事にしました。これから自分の方で公式サイトからのリンクを貼ります。
