### ISSUE TITLE
Matsue.rbのYoutubeに編集後の動画をUPする

### ISSUE THREAD

**Issue by amidaku** [matsuerb/matrk#53]
セッション毎に動画をYoutubeにUPします。

現在中継した動画が https://www.youtube.com/watch?v=tXloh2jIq3E で公開されていますが、中継機器の都合で弊社のアカウントでの中継となりました。
このままの状態はあまり望ましく無いので、できるだけ早く対応する **つもり** です。
各セッションの動画を公開した後、中継の動画は公開を停止する予定です。

**Comment by yoshiokaCB** [comment]
お手数おかけしますが、よろしくお願いいたします！

**Comment by sho-h** [comment]
レポートに記載しますので、再生リストのURL作ったら教えてくださいませー。m(_ _)m

**Comment by amidaku** [comment]
動画ですけど、講演のあとの質疑まで入れた方が良いですかねぇ。

**Comment by inoh** [comment]
私はレポートを書くときには質疑みてなかったです。
普通に見るときは私は質疑まであまり見た印象がないですがどうでしょう

**Comment by amidaku** [comment]
普通質疑とか入れないよねと思いつつ、おもしろいやりとりとかあって、どうしようかと考えてましたけど、まぁ普通にセッションの部分だけにしておきますね。

**Comment by yoshiokaCB** [comment]
はい。質疑はなくて良いと思います。

**Comment by amidaku** [comment]
では質疑は無しで編集しますね。ありがとうございました。

**Comment by amidaku** [comment]
まず、ゲスト講演のみUploadしました。
https://youtu.be/yPVa4fPy97M
ロゴなどCC0のもののみ使用することにしたため、オープニングなどを06から変更してみました。
こんな感じで他のセッションも進めて行こうと思います。

なお、事情によりライブ中継した動画はURIを知ってる方のみ閲覧出来るように変更してます。
検索には引っかからない様になってますので、ご承知ください。

**Comment by amidaku** [comment]
松江Ruby会議07の再生リストは、 https://www.youtube.com/playlist?list=PLbJxhePIoIPBSYjO2enmqSTpucHuHiA9S です。
昨日朝から編集とアップロードを続けてますが、まだ全てのセッションはUploadできてません。
今日もそろそろプロバイダの通信制限にひっかかりそうなので、明日以降に続きのUploadを行おうと思います。

**Comment by sho-h** [comment]
りょうかいです！> 再生リスト

必要になるのは12月頭になりそうなので、特に問題なさそうです。

**Comment by yoshiokaCB** [comment]
@amidaku さん
いいですね！
ありがとうございます！！

**Comment by amidaku** [comment]
編集はすべて終わってるんですが、続けてUploadすると制限がかかるみたいで、時間を空けてUploadしないといけない見たいです。まぁ12月までには全部上げれると思いますけど。

**Comment by amidaku** [comment]
様子見ながらでしたが、全ての動画をUploadしました。
ライブ中継の録画については公開を停止しますね。
やっと俺の#matrk07が終わったw

**Comment by yoshiokaCB** [comment]
@amidaku さん
確認しました。ありがとうございます！
本当にお疲れ様でした！！
これでCloseしてもOKですかね？

**Comment by amidaku** [comment]
OKです。ではcloseしますね。
再編集必要な何かが起きたら、当方メンションつけてissue作ってください。
よろしくお願いします。
