### ISSUE TITLE
プロコン解説記事のランキングが古い？疑惑の確認と対応

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk#54]
(せっかく対応いただいたのに第三者が検索で引っかかってここに来れてしまったりすると悪いのでスタッフ名じゃない方の固有名詞を書いていません...というtry)
#51 で気付いたのですが、我々が見たものと食い違いがあるようです。呼びやすいように以下のようにAとBに分けて比べると、

|  | 想定する評価時間 | 説明 |
| --- | --- | --- |
| A | 2015/09/24 24:00:00 | 順位,ニックネーム,提出コードのみが記載されたprocon.csv |
| B | 2015/10/06 24:00:00 | 解説記事 |

最低でも以下の違いがあるようです。評価時間がそもそも違うため、順位の変動は理解できます。しかし、僕が最近見たprocon.csvが9/25のランキング確認時と違っているかもしれない事を視野に入れてもバイト数が増えるのはよくわかりませんでした。
- yuyaさん
  - A: 全体20位、142バイト
  - B: 全体35位、183バイト
- kuratさん
  - A: 全体21位、144バイト
  - B: 全体26位、158バイト

前者の方は「滑り込みで更新した内容が反映されてない気がする」との事です。後者の方もprocon.csv評価時点より後(たぶん9/25 0:00 - 07:00のどこか)でより短いものをポストされてると記憶しており、B時点ではバイト数が減らないといけない気がしました。

一応そもそも対応するかどうかも含めると以下の点を決めるのがよいかなと思います。
- [x] 正しいランキングかどうかを確認していただくかを決める
  - そこまでしてもらわなくてもという話であればまぁという感じ
- [x] 上記の結果、間違っていたら直していただくかを決める

一般の方が9/26に受賞できない事があればまずいですが、それはなさそうなのでどっちでもよい気もしますが一応Issueを発行しました。どうしましょう？ > @yoshiokaCB

**Comment by sho-h** [comment]
なお、いまのところ原因は「本当にBで見た時間が古い」と推測しています。

**Comment by yoshiokaCB** [comment]
@sho-h さん
調べていただき、しかも分かりやすくまとめてもらって助かります！
とりあえず、先方に確認してみます。

**Comment by sho-h** [comment]
@yoshiokaCB りょうかいです！いくつも修正してもらう事になるので、反応によっては諦めるかなと思ってたのですが、大丈夫そうな雰囲気ですね。ではお手数ですがよろしくお願いします！
