### ISSUE TITLE
写真撮影の主担当を決める

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk#61]
- メインセッション

|セッション|担当|
| --- | --- |
| オープニング | 西田 |
| ゲスト講演 | 井上 |
| 昼休憩 | 木村 / 西田 |
| 基調講演 | 井上 |
| ゲスト講演（松田さん） | 木村 |
| プログラミングコンテスト | 井上 |
| ライブコーディング | 西田 |
| Ruby Quiz | 井上 |
| クロージング | 井上 |

- その他撮影が必要なとこ
    - スタッフ全員写真
        - オープニング前に撮影する
    - 参加者全員写真？
        - いるならいつ撮る？

**Comment by shakkun** [comment]
スパイスライフ様から、当日スタッフTシャツを着た集合写真をプロモーション用で送ってほしいとのことでした。よろしくお願いいたします。

(すみません、ここに書くのは適切ではないと思いましたが写真関連で書きました。)

**Comment by yoshiokaCB** [comment]
@shakkun
当日スタッフだけ集合して写真撮ってもいいかもしれないですね。（できればゲストも）
スタッフ用スケジュールに追加しますね。

**Comment by inoh** [comment]
スタッフだけの集合写真了解しました。
当日私の方で三脚持っていきます！

**Comment by nishidayuya** [comment]
自分はスピードライト持っていきますね．

**Comment by inoh** [comment]
毎度恒例ですが基本的には全員で撮るスタンスは変わりませんが漏れを防ぐために
主担当はとりあえず決めたいと思います。
適当に担当順番にふったのでまた不都合ありましたら言ってください。

**Comment by nishidayuya** [comment]
直前でごめんなさい．今年はRuby Quizやりたい（去年は問題出す側で参加できず）のでどなたか代わっていただけると助かるのですが，どなたかお願いできないでしょうか...

**Comment by inoh** [comment]
クロージングと合わせて僕とろうか？

**Comment by nishidayuya** [comment]
@inoh 良い?ありがとうございます!

**Comment by shakkun** [comment]
お疲れ様でした。

スパイスライフ様へ写真を送る担当ってもう決まっていますか？
データをいただければ私からでも送ります。

**Comment by inoh** [comment]
いちおTシャツを着た集合写真はSlack上の #general にあげてあります。
私は送り先がわからないので送信よろしくおねがします！
もし写真の場所わからなかったらまた言ってください。

**Comment by shakkun** [comment]
@inoh すみませんが、Slackに居なくて私のアドレスが分かれば送っていただけると助かります。

**Comment by sho-h** [comment]
こっちの方は当日用のIssueかと思うのでcloseしちゃいますね。
