### ISSUE TITLE
写真の共有場所を確保する

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk#62]
## Flickr

https://www.flickr.com/groups/3037110@N20/

**Comment by inoh** [comment]
とりあえずFlickrにprivateでグループを作成しました。
写真メンバのメールアドレスを確保次第随時追加していきます！

**Comment by KatoAtsue** [comment]
申し訳ありませんが、今回上手く撮影できなかったため、アップロードできる写真が少ないです。
お役に立てなくてすみません。

**Comment by sho-h** [comment]
数枚ですけどツイートするのにつかった写真をslackの#photoにおきました。(ツイート目的以外では微妙かも

**Comment by nishidayuya** [comment]
自分が撮影した写真をアップロードしました．

主に準備の写真が多いです．

**Comment by inoh** [comment]
私の写真もアップしておきました！
もし見たい方おられればまたアサイン追加します。

**Comment by yoshiokaCB** [comment]
@inoh 

@amidaku さんから以下のような要望がありました。

> いくつか動画を作成してまして、youtubeのカスタムサムネイルを登録しようと思ってます。
撮影班の撮った写真を利用させていただきたいのですが、アクセスさせてもらえませんでしょうか。

写真は公開設定に変更できますか？

**Comment by inoh** [comment]
了解です！
ちょっと明日の朝確認します！

**Comment by inoh** [comment]
@yoshiokaCB 
確認してみましたがFlickr一回privateで作るとpublicに権限変更できないっぽいですね
https://www.flickr.com/groups_create.gne
@amidaku さんのFlickアカウントとかあったりしないですよね。。。？

**Comment by amidaku** [comment]
@inoh お待たせしてます。
Flickrアカウント持ってましたが、Yahoo.comの情報漏えいにビンゴだったので、アカウント削除してました。
あたらめてつくったのでおしらせします。
メアドをここで書くのはいやなので、slackかなにかでDMしたいですが、何がよいですか？

**Comment by inoh** [comment]
@amidaku 
facebookとかでもよいですか？

**Comment by amidaku** [comment]
よろしくお願いします。

**Comment by amidaku** [comment]
joinできました。
ありがとうございます。

**Comment by inoh** [comment]
👍

**Comment by amidaku** [comment]
youtubeで写真の一部をサムネイルに使わせてもらいました。
（トリミングしたり、ちょっと色合い変えさせてもらってます。）
写真メンバの方々、ありがとうございます。
https://www.youtube.com/playlist?list=PLbJxhePIoIPBU5f0cAn4BceCG48EGSHsA

**Comment by sho-h** [comment]
@inoh そろそろレポート用に写真が見れるとありがたいです！残り作業って何があります？(自分もjoinした方が時間的に都合がよければ教えてくださいー

**Comment by inoh** [comment]
@sho-h ご無沙汰しております！ちょっといつもみたいな感じでまた写真整理しときます！

**Comment by inoh** [comment]
とりあえずこのissue的には残はないかと思ってます

**Comment by sho-h** [comment]
@inoh 了解です！じゃあ写真欲しいのはレポートのIssueの方でやりとりさせていただいて、こっちはcloseしておきますねー。
