### ISSUE TITLE
リーフレット作成

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk#65]
08のリーフレットを作成して配布する。
- [x] 昨年度のリーフレットの共有
- [x] 締切を決める
- [x] 今年度のリーフレットを作成
  - 定例会やミーティングで詰めながら
  - 作成したものは本レポジトリにコミットする

**Comment by sho-h** [comment]
昨年度のリーフレットは以下でした。昨年度は #30 で2週間前に配り始めた様子。2週前〜1ヶ月前のどこかで配りはじめられたらよさそう。
- https://github.com/matsuerb/matrk/blob/master/doc/matrk07-pamphlet.docx
- https://github.com/matsuerb/matrk/blob/master/doc/matrk07-pamphlet.pdf

**Comment by macera** [comment]
### 参加したことがない私が気になったところ
- 開催地が「松江テルサ4階」しか書いていないので、初めて行く人がいたら不親切(検索しないといけない)
  - 正式な住所を載せたい
  - 地図を載せたい
- 参加登録は必要なのかどうかが分からない。(事前登録が必要なのでは？)
  - 参加登録について書く(申し込みURL)
- 懇親会の事前申し込みについて情報が全く書いていない
  - せめて事前登録が必要なことは書いて欲しい(申し込みURL)

**Comment by macera** [comment]
### 作る前に知りたい情報
- 日時、場所、スケジュール(サイトの方がかなり詳しいが直前にならないと分からない？)
- サイトURL、参加登録URL
- クイズ、プログラミングコンテストの賞品

### 自分は分からないが、載せた方がいいかもしれない情報
- スポンサー名
- サイトURLのバーコード

**Comment by yoshiokaCB** [comment]
とりあえず、500部印刷する。

**Comment by tomo-k** [comment]
@macera 
一応情報揃いましたので共有します。

[日時、場所、スケジュール]
https://github.com/matsuerb/matrk/wiki/08_01_%E6%A6%82%E8%A6%81

[サイト URL]
http://matsue.rubyist.net/matrk08/

[参加登録 URL]
https://github.com/matsuerb/matrk/issues/59

[クイズ、プログラミングコンテストの賞品]
商品はスポンサー提供なので当日まで？おそらく未定です。
上位入賞者には商品あり程度の掲載になるかと思います。

**Comment by macera** [comment]
承知しました。

> 2週前〜1ヶ月前のどこかで配りはじめられたらよさそう。

10月中に印刷含めてできれば良いでしょうか？

あと
デザインのテーマ・イメージ考えているのですが、何か良い案ありましたら教えて頂きたいです。
テーマ・イメージ例:
  松江、季節(冬)、バトル(熱血)、近未来、可愛い、エレガント、クールなど

**Comment by yoshiokaCB** [comment]
@macera 
イメージカラーはルビーなんで赤と白で。
テーマはクールがいいです。

他のみなさんどうですかね？

印刷含めて10月中で問題ないです。
印刷についてですが、ラクスルのクーポン持ってますんでそこ使いますか？

**Comment by yoshiokaCB** [comment]
@macera 
リーフレットにはタイムスケジュールは無しにしたいですが良いですかね？
タイトル（内容）が来月以降にならないと確定しない気がしてきました。
すみません。

なので、コンテンツの紹介程度で良いかと思っています。

### 例
- 基調講演：講演者の写真と説明
- ゲスト講演１：講演者の写真と説明
- ゲスト講演２：講演者の写真と説明
- プログラミングコンテスト
- RubyQuiz

その他

って感じで。

**Comment by macera** [comment]
@yoshiokaCB 
承知しました

**Comment by sakasita001** [comment]
懇親会の情報なのですが、会場が変更になるかもしれません。
決まり次第、情報連携させてください。

https://github.com/matsuerb/matrk/issues/76

**Comment by macera** [comment]
@sakasita001 
承知しました

**Comment by macera** [comment]
途中経過です。(pngなので画質低くなっていますが)
こういう感じのレイアウトでいかがでしょうか。
よければ、後は地図と作成して、足りない箇所を埋める予定です。
何か忘れていることや問題があれば教えてください。
![ruby](https://cloud.githubusercontent.com/assets/5999886/19629029/6be9d552-99a6-11e6-83b0-aa5816bf31d9.png)

**Comment by macera** [comment]
今週中には必ず完成させる予定です。
去年の様子の写真ですが、写っている方、嫌だったら言ってくださいね。

**Comment by yoshiokaCB** [comment]
@macera 
ありがとうございます。めちゃくちゃいい感じですね！

一点だけ修正お願いします。
優勝者には豪華景品ありとなっていますが、「成績優秀者」もしくは「優秀者」となりますかね？
景品は１位だけでなく３位くらいまであるので(^^;;)

**Comment by sho-h** [comment]
@macera いい感じですね！

僕からは追加では印刷物なのでメールアドレスは _at_ じゃなくてもいいかもと思った程度でした。

**Comment by macera** [comment]
@yoshiokaCB 
ありがとうございます。
松田さんの紹介文と景品の件承知しました！

@sho-h 
ありがとうございます。
確かに！承知しました。

プログラミングがテーマと聞いたので、エディタとER図をイメージしました。

**Comment by yoshiokaCB** [comment]
@macera 
追加ですんません！
公式サイトのURLのQRコードってつけれますかね？
スペース的に難しければ、申し込みのURLとかは公式サイトから見れるので省いても良いかもしれません。

**Comment by macera** [comment]
@yoshiokaCB 
承知しましたー

**Comment by macera** [comment]
途中経過です。
また写真使わせていただきました。問題あれば連絡下さい。
まつもとさんの下あたりにスペースができてしまったので、何かを埋めたら完成です。

![ruby](https://cloud.githubusercontent.com/assets/5999886/19699145/07ef4644-9b2d-11e6-8169-07145583bc49.png)
![-1](https://cloud.githubusercontent.com/assets/5999886/19699146/07efb034-9b2d-11e6-9b7a-75b575904838.png)

**Comment by macera** [comment]
解像度下がっているのでQRコード読めませんが、印刷前にチェックします。

**Comment by sakasita001** [comment]
懇親会の概要、決定しました。
よろしくお願いいたします。

https://github.com/matsuerb/matrk/issues/76

**Comment by macera** [comment]
@sakasita001 
承知しました

**Comment by macera** [comment]
> とりあえず、500部印刷する。

金曜日には完了する予定なので、
土曜日以降印刷できますが、印刷屋の紙の種類多すぎてどれがいいのかわからないので、詳しい方教えてくださると有難いです。

**Comment by sho-h** [comment]
やばい。では僕が紹介文の確認をしないとですね(ごめんなさいまだですorz)。頑張ります！

**Comment by amidaku** [comment]
紙ですが、いわゆるフライヤーならコート紙が良いと思います。
厚みは普通か薄手で良いと思います。

**Comment by yoshiokaCB** [comment]
@macera 
印刷の手配もしていただけますか？
もしされるのでしたら事前（発注前）に金額を教えてもらえると助かります。
一応予算が2,000円となってますので、それを超えるようでしたら、ちょっと色々と対策が必要です。
まぁ、そもそも500部もいらないかもしれないので、そこは枚数の調整でも良いかもしれません。

もちろん、データもらってこちらで発注でもいいですよー。

**Comment by macera** [comment]
最終版をコミットしました。
https://github.com/matsuerb/matrk/tree/master/doc

@amidaku @yoshiokaCB 
印刷の件ありがとうございます。
- コート紙（厚みは普通か薄手）
- 予算2,000円
- 500部(要調整)
  一応他の方も印刷発注できるようにpdfと元データをコミットしました。

@sho-h 
確認のほどよろしくお願い致します。

修正ありましたら、ご連絡お願いします。

**Comment by sho-h** [comment]
@macera コミットお疲れさまです！紹介文の確認取れました！

**Comment by macera** [comment]
昨日ラクスルに注文して、今日最終PDF確認しました。
- コート紙 普通
- 300部
- 受付日確定から5日以内

で注文しました。

¥1400

初回クーポン¥-500
- 税¥72

計¥972

出荷予定日は11月10日です。

領収書は印刷だと300円かかるので、自宅のプリンターで印刷を選びました。
宛名はこちらで編集できるみたいですが、どうしましょう？

**Comment by yoshiokaCB** [comment]
@macera 
それで問題はありません！
よろしくお願いいたしますm(_ _)m

@kenjiSugihara 
宛名に特に指定はあるでしょうか？

**Comment by sho-h** [comment]
あとは #89 みたく別の作業として分解してIssueを分けますかー。
