### ISSUE TITLE
松江Ruby会議08のWebサイトの準備

### ISSUE THREAD

**Issue by sada** [matsuerb/matrk#69]

**Comment by sada** [comment]
9/3のミーティング結果をWebサイトに反映する修正をupdate-matrk08ブランチにコミットしています。
修正の確認を @yoshiokaCB さんにお願いしています。
Webサイトに載っている目的が松江Ruby会議07のままなので、松江Ruby会議08の目的のテキストを教えていただけることになっています。

**Comment by yoshiokaCB** [comment]
@sada 
issue ありがとうございます。確認の件、了解です！
今夜確認します。遅くなってごめんなさい。

**Comment by sada** [comment]
@yoshiokaCB 
いえいえ、問題ありません。
他の方がWebサイトの修正を始めるとブランチにgit pushした作業が重複しそうでしたので、こちらこそ勝手ながらissueにアサインとコメントさせていただきました。 :grin:

**Comment by yoshiokaCB** [comment]
@sada 
目的を修正しました。ご確認をお願いします！

あと、#58 で特に意見がなければマージお願いします。

…「今日」とは言ってない。寝るまでが「今夜」。

**Comment by sada** [comment]
@yoshiokaCB 
#58 を確認しました。
一箇所コメントしました。

そちらの修正を含めてupdate-matrk08ブランチにコミットしました。
あとPRを作成しました。

https://github.com/matsuerb/matsuerb-nanoc/pull/385

**Comment by sada** [comment]
上記のPRがマージ後、Webサイトの公開作業をしようと思います。
よろしくお願い致します。

**Comment by inoh** [comment]
@sada 
@yoshiokaCB 
ホームページ製作まかせっきりで申し訳ないです。。
遅くなりましたがDoorkeeperにイベントを作成しようと思います。
概要とか担当者とか全然頭に入っていないのでこれから状況把握＆整理します！

**Comment by inoh** [comment]
#59 
#70

**Comment by sada** [comment]
PRがマージされたので、Webサイトの公開作業をします。

**Comment by sada** [comment]
公開しました。
http://matsue.rubyist.net/matrk08/

**Comment by sada** [comment]
公式Webサイトは公開したので、このissueは閉じることにします。
