### ISSUE TITLE
Rubyの会から公式サイトへのリンク

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk#70]
以下のようなプルリクを行う。
- https://github.com/ruby-no-kai/rko-router/pull/9/commits/b22e21d700b2331a7242b013e1185cc044339233

**Comment by inoh** [comment]
#69

**Comment by sada** [comment]
PRを作成しました。
https://github.com/ruby-no-kai/rko-router/pull/19

**Comment by sada** [comment]
PRがマージされたのと、http://regional.rubykaigi.org/matrk08 で松江Ruby会議08のWebサイトへリダイレクトされるのを確認しました。
このissueは閉じようと思いますが、よろしいでしょうか。

**Comment by sho-h** [comment]
確かにリダイレクトされてたのでcloseしちゃいます。
