### ISSUE TITLE
基調講演の依頼内容を決める

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#71]
基調講演の依頼内容を決めます。
（すでにまつもとさんへスケジュール調整の依頼済みです。）

**Comment by yoshiokaCB** [comment]
# 構成（案）
- 基調講演30分
- 質問タイム20分

## 講演テーマ
1. オープンソースの育て方。
   1. どうやって手伝ってくれる人を見つけたのか。
   2. 運以外にどのような活動を実際にされたのか。
2. ruby mruby iot についての思いについてお話ししてほしい。

## 質問について

事前に質問を集めて、渡して答えてもらう。一般参加者からも集める。

### 質問内容（例）
1. 私生活について知りたい（月何日出社してる。）  
2. 犬の散歩のルート
3. 子供の頃何してた、松江の感想。  
4. 外国と松江の違い。
5. 並列化について

### 質問の流れ

Doorkeeperの申し込み時に質問を集める。
集まった質問をスタッフで優先順位をつけて、当日時間の限り質問をする。

**Comment by yoshiokaCB** [comment]
講演テーマについて、10/15（土）のミーティングで依頼内容を決めようと思います。
特に講演テーマについて、みなさん何か聞いてみたいことがあれば、ご意見をお願いします！

**Comment by yoshiokaCB** [comment]
@sho-h 

以下の内容で講演依頼をお願いできますか？

# 当日の構成
- 講演30分
- 質問タイム20分

## 講演のテーム
1. オープンソースの育て方。
   1. どうやって手伝ってくれる人を見つけたのか。
   2. 運以外にどのような活動を実際にされたのか。
2. ruby mruby iot についての思いについてお話ししてほしい。

## 質問タイムについて

Doorkeeperの申し込み時に質問を集める。
集まった質問をスタッフで優先順位をつけて、当日時間の限り質問をする。

---

あと、紹介文がOKかどうかの確認も合わせてしてもらえると助かりますm(_ _)m

紹介文

```
我らがRubyの生みの親。小泉八雲氏と肩を並べて松江市名誉市民でもあり、Rubyを通して地方から世界のソフトウェア業界に多大な影響を与えています。
今回も松江ならでは、基調講演でお話をしていただきます。
```

**Comment by sho-h** [comment]
@yoshiokaCB 遅くなりました！紹介文も含めてOKとの事でした！

**Comment by yoshiokaCB** [comment]
@sho-h ありがとうございます！！

**Comment by yoshiokaCB** [comment]
依頼内容が確定したのでクローズします。
