### ISSUE TITLE
Rubyクイズの内容を決める

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#73]
現状以下のような意見が挙がっています。
- 昨年度は見せ方もよくてわいわいできたのがよかった
- 今年度はスキルの差などを配慮してチーム戦などにするとより面白くなるのでは
- 昨年度は解説がほしいという話があった
- 今年度は何回かに分けて休憩時間に解説をしながらやってみてもいいのではないか
- コードわからない人にはQuizの方が面白いかも
- 今年度は受付時点でチーム分けを済ませると参加もしやすいのではないか

**Comment by yoshiokaCB** [comment]
現状以下のような意見が挙がっています。

* 昨年度は見せ方もよくてわいわいできたのがよかった
* 今年度はスキルの差などを配慮してチーム戦などにするとより面白くなるのでは
* 昨年度は解説がほしいという話があった
* 今年度は何回かに分けて休憩時間に解説をしながらやってみてもいいのではないか
* コードわからない人にはQuizの方が面白いかも
* 今年度は受付時点でチーム分けを済ませると参加もしやすいのではないか

**Comment by eijik** [comment]
slack#quizチャネルから転記

- 0. 前提事項
　50分(去年15分)

- 1. 進行について:
　1-1. 勝ち抜き方式: 
　　問題 -> 回答の軽い説明 -> 次の問題 .....
　　最後は結構人が残ったのでジャンケン(人が多かったら、司会者とジャンケン)
　　２商品 * 2サイクル(負けても２回目に参加できるように)
　　1サイクル: 25分(5times * (問題 -> 説明) -> ジャンケン ->  表彰)
　　解説URLは最後終わったら配布。

- 2. 景品: (自分)
　1, 2位 * 2サイクル: 
　　
- 3. 問題について
　　いま集まっている問題でまあ大丈夫そう。

- 4. 当日仕切り: (本多君、自分)

- 5. 11/27のリハーサルでチェック
　- 問題は去年のか、使わない問題でシュミレーション
　- 1サイクル試してみて、20分で完了するかチェック

## 11/27(matue.rbにて)のリハのフィードバック

### 冒頭説明
- ２サイクルある
- スマホやPCをつかわないように
- 各問題をとく時間は1分、説明は３分ぐらい
- 立ったり、座ったりするけど、解けたかどうかは本人しだいなので、ちゃんと覚えておいてくださいね。

### 各問題解いている時
- 時間のタイムを伝える: 30s -> 15s -> 10sをカウントダウン。(visual的なもののほうがなお良い。)

### TODO
- [] 小嵜: 問題で突っ込むナレータポイントを考えておく
- [] 小嵜: 考え中の音楽、画面(1minカウントダウン)を考える。(ustで配信するので、著作権OKなものを選別)
- [] 本多: 問題用のスライドを作成


問題自体はslack#quiz_questionにて限定メンバー(クイズに参加しない人)で共有

**Comment by yoshiokaCB** [comment]
slack#quizチャネルから転記

11/27(matue.rbにて)のリハのフィードバック

冒頭説明
- ２サイクルある
- スマホやPCをつかわないように
- 各問題をとく時間は1分、説明は３分ぐらい
- 立ったり、座ったりするけど、解けたかどうかは本人しだいなので、ちゃんと覚えておいてくださいね。

各問題解いている時
- 時間のタイムを伝える: 30s -> 15s -> 10sをカウントダウン。(visual的なもののほうがなお良い。)

TODO
- 問題で突っ込むナレータポイントを考えておく
- 考え中の音楽を考える。=> 動画で流すので、著作権の大丈夫なものを選別する。

**Comment by yoshiokaCB** [comment]
slack#quizチャネルから転記

# タスク（全体の流れ）

##  1. 冒頭の説明

### 流れ

 - ２商品 x ２サイクル(負けても２回目に参加できますよ〜)
 - １サイクル: ２５分((問題 -> 説明)を５ターム -> ジャンケン ->  表彰)
 - 各問題を解く時間は１分、説明は３分ぐらい。最後に解説の詳細URLを配布しますよ

### 注意事項

 - スマホやPCをつかわないように
 - 立ったり座ったりするけど、解けたかどうかは本人次第なので、自主的に正しく動いてね

## 2. タイムキーパー: 問題を開始してから１分をカウントダウン

 - カウントダウン的な動画があればサブスクリーンで表示(まあ、なしでもOKかと)  
例:  https://www.youtube.com/watch?v=C6crU8Q3ig8 
 - カウントダウン時に流す音楽(著作権フリーのもの)は本多君が調査(動画の音楽でOKそうならここは不要)

## 3. ナレーション: その場をちょっと盛り上げる、なにかネタを言ってみる。(なしでもOK)
 - 事前に本多君から表示する問題のスライドを共有してもらって、ナレーションを挟めそうなとこを考えてみてください。

## 4. プレゼントを渡す: 
 - 残った人でジャンケン(人が多かったら、司会者とジャンケン) => ２人選出
 - 提供企業さん(前の方に座ってもらう)に前に来てもらって、渡してもらうのを誘導。

## 5. 最後に解説URLを配布

**Comment by sho-h** [comment]
@nobyuki PRよろしくですー。

**Comment by sho-h** [comment]
当日用のIssueかと思いますので、closeしてしまいますね。
