### ISSUE TITLE
プログラミングコンテストの内容を決める

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#74]
現状以下のような意見が挙がっております。
- プロコンは事前に投稿もできてたし外部の人にもやれてたのでよかった
- 今からpaizaさんにお願いして間に合うか？ -> 間に合うのではないか。去年は3ヶ月前だった
- コンテストでスタッフが多く入賞してたのは気になった
  - 何か制限を設けた方がいいと思う
    - スタッフは1位取れない
    - スタッフはそもそも入賞できない
    - 部門ごとに分ける
    - など(別途相談)
- もしコンテストをやるなら誰のための企画かよく考えたい
  - スタッフだけが盛り上がってもよくない
  - 会場でしらける人と盛り上がってる人が完全に分かれてた
  - やった人は1ヶ月とかやってるのにやってない人にややっぱり難しい
  - 1位の人とかコードが読むのが大変なので、難しいのでは
  - 最終的に短いコードが有利になるのはよくなかった
    - あまりくわしくない人がしらける要因となった
  - コンテストをやるならもう少し参加してない人に対する配慮をしたいところ
    - 投稿プログラムの前のサンプル回答などの時間をもっと取るなど
- 調整のためには投稿のためのシステムを自分たちで構築するのもよいのではないか
  - paizaの中の人が書いたdockerの本を読んだらシステム作れるんじゃないかと思った
  - わかりやすい(GOLFからの脱却)、参加してない人が盛り上がりやすい形にしやすいのではないか
  - スタッフのみで準備する方向で今後検討してみる

また、 @ToruKurahashi さんのご好意でコンテスト用のサーバの準備ができそうです。

**Comment by yoshiokaCB** [comment]
## 問題は迷路を生成して解いてもらう。

迷路はアスキアートを標準入力を受け取る。

```
＋ー＋＋ー＋＋　＋
｜　　　　　　　｜
＋　＋＋ー＋＋ー＋
＋　＋＋ー＋＋ー＋
｜　　　　　　　｜
＋ー＋＋ー＋＋　＋
＋ー＋＋ー＋＋　＋
｜　　　　　　　｜
＋ー＋＋　＋＋ー＋
```

回答はゴールまでのルートをx y（改行付き）で出力する。

```
# x y
8 1
8 2
7 2
...

```

**Comment by sho-h** [comment]
内容については三回目の打ち合わせで共有した。(記録等は開催後
