### ISSUE TITLE
当日のタイムスケジュールを決める

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#75]
今のところの案は以下のようになっています。
### タイムスケジュール（サンプル）

| 時間 | プログラム |  |
| --- | --- | --- |
| 11:00 〜 11:05 | オープニング |  |
| 11:10 〜 11:55 | ゲスト講演 |  |
| 12:00 〜 13:30 | 昼食休憩（昼食LT） |  |
| 13:30 〜 14:20 | 基調講演 |  |
| 14:30 〜 14:45 | session 1 |  |
| 14:50 〜 15:05 | session 2 |  |
| 15:10 〜 16:00 | Ruby Quiz or プロコン | - |
| 16:10 〜 16:25 | session 3 |  |
| 16:30 〜 16:45 | session 4 |  |
| 16:50 〜 17:05 | session 5 |  |
| 17:05 〜 17:15 | クロージング | 実行委員長 |
#### 関連 issue
#71 基調講演の依頼内容を決める
#72 ゲスト講演の依頼内容を決める
#73 Rubyクイズの内容を決める
#74 プログラミングコンテストの内容を決める

**Comment by yoshiokaCB** [comment]
今回はRuby Quizをメインに考え、以下のようなタイムスケジュールで考えています。

### タイムスケジュール（サンプル）

| 時間 | プログラム |  |
| --- | --- | --- |
| 11:00 〜 11:05 | オープニング |  |
| 11:10 〜 11:55 | ゲスト講演 |  |
| 12:00 〜 13:30 | 昼食休憩（昼食LT） |  |
| 13:30 〜 14:20 | 基調講演 |  |
| 14:30 〜 14:45 | session 1 | 通常発表 |
| 14:50 〜 15:40 | Ruby Quiz | - |
| 15:50 〜 16:20 | session 2 | ライブコーディング |
| 16:30 〜 17:00 | session 3 | ライブコーディング |
| 17:05 〜 17:25 | プログラミングコンテスト結果発表 |  |
| 17:25 〜 17:35 | クロージング | 実行委員長 |

**Comment by tomo-k** [comment]
### タイムスケジュール（サンプル）

| 時間 | プログラム |  |
| ---- | ---- | ---- |
| 11:00 〜 11:05 | オープニング |  |
| 11:10 〜 11:55 | ゲスト講演 |  |
| 12:00 〜 13:30 | 昼食休憩（昼食LT） |  |
| 13:30 〜 14:20 | 基調講演 |  |
| 14:30 〜 14:45 | session 1 | 通常発表 |
| 14:50 〜 15:40 | Ruby Quiz | - |
| 15:50 〜 16:20 | session 2 | ライブコーディング |
| 16:30 〜 17:00 | session 3 | ライブコーディング |
| 17:05 〜 17:25 | プログラミングコンテスト結果発表 |  |
| 17:25 〜 17:35 | クロージング | 実行委員長 |

**Comment by tomo-k** [comment]
### タイムスケジュール（サンプル）

| 時間 | プログラム |  |
| --- | --- | --- |
| 11:00 〜 11:05 | オープニング |  |
| 11:10 〜 11:55 | ゲスト講演 |  |
| 12:00 〜 13:30 | 昼食休憩（昼食LT） |  |
| 13:30 〜 14:20 | 基調講演 |  |
| 14:30 〜 14:45 | session 1 | 通常発表 |
| 14:50 〜 15:40 | Ruby Quiz | - |
| 15:50 〜 16:20 | session 2 | ライブコーディング |
| 16:30 〜 16:50 | プログラミングコンテスト結果発表 |  |
| 17:00 〜 17:30 | session 3 | ライブコーディング |
| 17:25 〜 17:35 | クロージング | 実行委員長 |

**Comment by yoshiokaCB** [comment]
上記サンプルで決定。

メモ

```
スクリーンの準備
会場セッティングは昼食時にしてします。
```

**Comment by yoshiokaCB** [comment]
### タイムテーブル

| 時間 | プログラム |  |
| --- | --- | --- |
| 11:00 〜 11:05 | オープニング |  |
| 11:10 〜 11:55 | ゲスト講演１ |  |
| 12:00 〜 13:30 | 昼食休憩（昼食LT） |  |
| 13:30 〜 14:20 | 基調講演 |  |
| 14:30 〜 14:50 | ライブコーディング | pim |
| 15:00 〜 15:50 | Ruby Quiz | - |
| 16:00 〜 16:50 | ゲスト講演２ | - |
| 17:00 〜 17:20 | プログラミングコンテスト結果発表 |  |
| 17:20 〜 17:30 | クロージング | 実行委員長 |

タイムテーブル修正しました。
基調講演以降の順番について色々と悩んでます。
ご意見お願いします。

**Comment by hidakatsuya** [comment]
> 基調講演以降の順番について色々と悩んでます。

どの辺りを悩んでおられるのでしょう？

個人的には大きな違和感はありません。基調講演→ゲスト講演2→(大休憩)→ライブコーディング... という流れでも良いかなと思いますが、強い意見ではありません。

**Comment by yoshiokaCB** [comment]
> どの辺りを悩んでおられるのでしょう？

あっ、そうですね。それ書いとかないと。ナイス指摘！

プログラミングコンテストの発表で終わるところが気になってます。
プログラミングコンテストの発表が、前回は一部でしか盛り上がらなかったことを考えると最後に持ってくるのは少し不安に思っている次第です。
今回は前回と違う発表形式なので盛り上がるような工夫は考えますが、やっぱり最後は盛り上がって終わりたい。
最後はRubyQuizか発表セッションがいいかなと思ったり。
1. 基調講演
2. ゲスト講演２
3. プロコン
4. ライブコーディング  
5. Ruby Quiz

上記のようにしても良いかなぁ。
ただ、上記の場合だと基調講演とゲスト講演で盛り上がって、そこで帰られる方もおられそうな気もしますね。まぁ、あまり気にしなくても良いかも。

**Comment by sho-h** [comment]
僕は今朝の方の案に +1 です。地元のLTとライブコーディングがくっついてるより離れてる方がいいと思ったくらいの事なのですが。あと、本当にゲストの方とおしゃべりしたい人は懇親会まで残ってもらえる気がしました！

**Comment by tomo-k** [comment]
@yoshiokaCB 
4と5逆にするのはどうでしょう？
最後に座って聴く系のコンテンツ持ってきた方が、スムーズにクロージングに移れるかなと。
RubyQuizにした場合とそんなに変わらないかもしれませんが。。。

**Comment by yoshiokaCB** [comment]
@tomo-k 
それ悩んだんだけど、最後をRubyQuizにしておくと時間調整が可能で良いと思っています。
他のコンテンツより、時間を短縮とかしやすいので。
（逆にリハをきちんとしとかないと一番時間の計算がつかなくなる可能性も…）

**Comment by yoshiokaCB** [comment]
その他、特にご意見なければ以下の内容で決めたいと思います。

### タイムテーブル

| 時間 | プログラム |  |
| --- | --- | --- |
| 11:00 〜 11:05 | オープニング | 実行委員長 |
| 11:10 〜 11:55 | ゲスト講演１ | 越川直人氏（マネーフォワード） |
| 12:00 〜 13:30 | 昼食休憩（昼食LT） |  |
| 13:30 〜 14:20 | 基調講演 | まつもとゆきひろ氏 |
| 14:30 〜 15:20 | ゲスト講演２ | 松田明氏 |
| 15:30 〜 15:50 | プログラミングコンテスト結果発表 | - |
| 16:00 〜 16:20 | ライブコーディング | 佐藤氏(pim) |
| 16:30 〜 17:20 | Ruby Quiz |  |
| 17:20 〜 17:30 | クロージング | 実行委員長 |

**Comment by yoshiokaCB** [comment]
タイムテーブルはwikiにまとめたのでクローズします。

https://github.com/matsuerb/matrk/wiki/08_08_%E3%82%BF%E3%82%A4%E3%83%A0%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB
