### ISSUE TITLE
懇親会の内容を決める。

### ISSUE THREAD

**Issue by sakasita001** [matsuerb/matrk#76]
懇親会でするレクリエーションの内容を決めたいです。

昨年度行ったLTに関して行うとしたら昼食を優先するとのことでしたので、別の企画を考えるようと思っています。

次回のミーティングで決めていきたいです。
- [x] 料金　　3500円(飲み放題1500、食べ物2000）
- [x] 学生参加　参加費2000円　枠10名　
- [x] 申し込み人数　とりあえずで25人見込みと伝えました。
- [x] Doorkeeper最終申し込み期限　12月15日
- [x] 申し込みのチケットを一般と学生でわけるか　申し込みページを分ける　
- [x] 当日の最終回答　15時〆
- [×] 会場　中会議場  　★中会議場で決定しました。

［予約の仕方について］　
12/1に一発目の予約
12/10,12/17に人数の変動を連絡
12/17　15：00飲み物の最終オーダーおよび食べ物の追加があれば最終（コースの枠外）

お店から、「忘年会の季節なので、人数が増える分には対応できる。（余分に仕入れている。）当日に人数が減るのが一番問題。」と聞いています。
ですので、当日以外は３人単位の下振れで人数をお伝えしようと思っています。

［会場準備］　
当日、クロージングから三十分ほど準備の時間がほしいとのことです。
申し訳ないのですが、当日懇親会参加するスタッフの方たちに机の移動をお手伝い願えないでしょうか。

**Comment by sakasita001** [comment]
場所：別会場
レクリエーション：マシュマロチェレンジ
人数：20～30
予算：￥4,000－

**Comment by sakasita001** [comment]
17日の午後３時からお店に下見と打ち合わせにいきます。

**Comment by inoh** [comment]
@sakasita001
@yoshiokaCB  
今回の懇親会は学生と一般わけるとかわけないとかってありますか？

**Comment by inoh** [comment]
## 井上メモ（確認事項）
- [x] 料金
- [ ] 申し込み人数
- [ ] Doorkeeper最終申し込み期限
- [ ] 申し込みのチケットを一般と学生でわけるか

**Comment by tomo-k** [comment]
@inoh 
学生は一般より安めの料金設定になります。
（昨年のスポンサー料の余りを学生の補助に使います。）

**Comment by sakasita001** [comment]
更新滞ってすみません。
カプリチョーザさんとの打ち合わせ結果を更新しました。

**Comment by inoh** [comment]
@tomo-k 
@sakasita001 
去年の余りってどれくらいでしたっけ？
余りによって値段設定とか人数計算しといた方がよいですね。
ちなみに去年だと一般が4800円で学生が1000円の設定でしたが
一般が24名、学生が7名応募ありましたね。

**Comment by inoh** [comment]
@sakasita001 
開場の時間どうしましょうかね。
３０分準備時間とかRuby会議の片付けとか考えると余裕みて18:30くらいにしときましょうか？

**Comment by inoh** [comment]
去年の懇親会の文面とか見えると値段多めに設定してた？っぽいので募集はとりあえず4000円にしています。
「あがることはないけど値段を変更することがあるかも」というのは前回に引き続き文面を書いています。

**Comment by tomo-k** [comment]
@yoshiokaCB 
@inoh 
@sakasita001 
学生は去年と同じで1000円、一般は3500円?4000円?でいいかなと思いましたがいかがでしょう。
doorkeeperの枠自体は学生10人、一般30人で設定でいかがでしょうか。

**Comment by inoh** [comment]
![image](https://cloud.githubusercontent.com/assets/1096516/18876752/d31c6cae-8505-11e6-92c2-6e6efc2b2fec.png)
![image](https://cloud.githubusercontent.com/assets/1096516/18876768/e3a24c6a-8505-11e6-8651-df76e30a7342.png)

**Comment by inoh** [comment]
![image](https://cloud.githubusercontent.com/assets/1096516/18876842/2377e2b4-8506-11e6-9ef5-be219964d149.png)
![image](https://cloud.githubusercontent.com/assets/1096516/18876859/30df6256-8506-11e6-8422-268f76aae95f.png)

**Comment by inoh** [comment]
![image](https://cloud.githubusercontent.com/assets/1096516/18876931/875f1f54-8506-11e6-866f-97c8504b370c.png)
![image](https://cloud.githubusercontent.com/assets/1096516/18876941/90b77fec-8506-11e6-99d5-48d10cc0e047.png)

**Comment by sakasita001** [comment]
時間はそのくらいになると思います。
会費の件ですが、去年の余剰金がいくらか把握してないです。すいません

**Comment by sho-h** [comment]
ではぼちぼち予算案を作成せねば...(←忘れてた)。それを10/15に見てもらう感じですかねぇ。

**Comment by inoh** [comment]
そうか。。。
なんでDoorkeeper前回、一般と学生わけてたんだろうと思ってたけど申し込み人数の制限がチケットごとじゃなくてDoorkeeperのページごとにしか設定できないんですね。

**Comment by inoh** [comment]
一般と学生をわける件については次回の打ち合わせで相談させてくださいということで
とりあえず一般と学生合わせて30人でとりあえずDoorkeeper設定しておきます。

**Comment by kenjiSugihara** [comment]
@sakasita001 さん、皆さん、10月15日の打ち合わせの際に
懇親会予算、参加費（一般、学生）、見込み人数に関して相談させてくださいませ〜
予算作成のためです

**Comment by sakasita001** [comment]
10/15の打ち合わせおよび10/16のお店との申し入れ内容を更新します。（★の入っている項目です。）

会議室について中会議室でやる案が進行中ですのでこちらが決まり次第、チケットがクローズできると思いますが、いかがでしょうか？

**Comment by sakasita001** [comment]
チェックが埋まりましたのでisueeをクローズします。
