### ISSUE TITLE
第二回　ミーティングについて

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#77]
急ですみません。
下記日程でミーティングを開催したいと思います。ご都合のつく方はご参加お願いします。

日時：9/3 午後4時〜
場所：オープンソースラボ

基本的には進捗状況の共有になるかと思います。以下議題です。
- #2: [議題](https://github.com/matsuerb/matrk/wiki/08_00_02_%E7%AC%AC%E4%BA%8C%E5%9B%9E%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0)

**Comment by nobyuki** [comment]
申し訳ありません、ちょっと体調を崩してしまいまして、欠席させてください。
slackの方は確認しておきますので、よろしくお願いします。

**Comment by yoshiokaCB** [comment]
@nobyuki さん、了解です。
お大事にしてください！！
