### ISSUE TITLE
会場準備の概要

### ISSUE THREAD

**Issue by teeta32** [matsuerb/matrk#78]
準備の取り掛かりとして、去年の開催を参考にして準備事項の概要を記す。 
(不足している事項等は、随時、追記します。)
- 会場に必要な資材や機材の用意
  - 会場からレンタルするもの
  - 会場からレンタル以外でお借りするもの 
  - Matuse.rb で用意するもの 

それぞれ、去年の開催時に用意したものを挙げる。
今年、追加するものや不要なものを反映する。   
- 当日の会場準備
  - 会場の机の配置
  - 演台やプロジェクター等の配置 
  - 電源の配置(電源ドラムや電源タップを用意する) 
  - ネットワークの用意
    - 無線 LAN
    - Ustream中継用の有線 LAN
  - 会場で出るゴミの片付け

**Comment by sada** [comment]
松江Ruby会議07にて使用した機材のリストを貼り付けます。

松江Ruby会議07でオープンソースラボから借りた機材。

| 品名 | 数量 |
| --- | --: |
| LANケーブル | 10本 |
| プロジェクタとスクリーン | 1組 |
| 電源タップ | 10本 |
| ホワイトボード | 1台 |
| Matzパネル | 1枚 |
| 電源ドラム | 2台 |
| Mac | 1台 |
| タイムテーブル用紙 | 1枚 |
| 養生テープ | 1個 |

松江Ruby会議07でオープンソースラボに置いていた岩石さんの機材。

| 品名 | 数量 |
| --- | --: |
| 三脚 | 3本 |
| ディスプレイ | 1台 |
| 配線カバー | 5本 |

**Comment by kenjiSugihara** [comment]
@sada さん、お疲れ様です！
会計担当の杉原です。
10月15日の打ち合わせの際に、テルサから有償で借用するものがあれば教えてくださいませ〜
予算作成のためです。

**Comment by teeta32** [comment]
開催が終了しましたので、クローズします。
