### ISSUE TITLE
Tシャツ追加発注

### ISSUE THREAD

**Issue by shakkun** [matsuerb/matrk#79]
- デザインは昨年と同じ(しまねっこ)
- 持っていない方の分だけ追加発注

タスク
- Tシャツスポンサーを依頼
- 注文する人を取りまとめて枚数を確定
- サイズの取りまとめ
- データの受け渡し(再入稿が必要)
- tmixさんに注文
- 受取
- 配付

**Comment by shakkun** [comment]
昨年同様、スポンサー依頼しました。
(これから社内稟議だそうですが、たぶん大丈夫だそうです)
特典について尋ねられましたが、詳細をどなたか教えてください。

3週間前に注文してほしいとのことでしたので、11月下旬には発注したいと思います。

**Comment by yoshiokaCB** [comment]
@shakkun 
調整ありがとうございます！（レスが遅くてすみません。）
ちょっと確認します！週明けには確定すると思います。

一応、以下のような特典をつけさせてもらう予定です。
- サイトへTシャツスポンサーとしてバナーを掲載させていただく。
- るりまの開催報告でスポンサー欄で紹介させていただく。
- どこかで1分程度T-MIXさんの紹介をさせていただく。  
  （昼食LT, Ruby Quiz, プロコン, クロージングのどこか）

**Comment by shakkun** [comment]
@yoshiokaCB ありがとうございます。よろしくお願いいたします！

**Comment by shakkun** [comment]
稟議に無事通ったと連絡がありました！
15枚くらいだそうです。

また、Webサイトに掲載したら教えてくださいとのことでした。

**Comment by yoshiokaCB** [comment]
@shakkun 
ありがとうございます！
Tシャツをまだ持ってられない方を優先的に発注しましょう。

@KatoAtsue @sho-h 
松江Ruby会議のTシャツのデータってGithubのどこかアップしとくことはできますかね？
（著作権の問題もあるので、 @KatoAtsue さんの考え優先ですが。）

**Comment by sho-h** [comment]
@yoshiokaCB しまねっこが入ってる関係でpublicな場所には置けないんですよねー。

**Comment by yoshiokaCB** [comment]
@sho-h なるほど！データ関係は去年整理したのになんでないんだろ？と思ってましたが…
言われてみれば、なんかそんな話もしたかも。

@KatoAtsue ちょっとデータを自分まで送ってもらえると助かりますm(_ _)m
（前回ももらってたらゴメンなさい）

**Comment by shakkun** [comment]
@yoshiokaCB Tシャツデータいただきました。
ありがとうございます。
発注準備、進めます。

**Comment by yoshiokaCB** [comment]
@shakkun 
よろしくお願いします！

**Comment by shakkun** [comment]
Tシャツの発注枚数を確定したいと思います。
昨年と同じデザインですので、昨年スタッフをされていない方は必要になります。Tシャツを希望される方はサイズを、このissue上のコメントにてお伝えください。(個人の費用負担はありません。)

サイズ参考
https://tmix.jp/products/085-CVT#size

期限は10月31日(月)です。

**Comment by yoshiokaCB** [comment]
Tシャツ持ってない方、サイズを教えてください！
1. @hidakatsuya - M
2. @ishikawa999 - S
3. @meg-k - S
4. @hasumon - L
5. @sakasita001 - XL 
6. @macera - 160
7. @fsato0111 - S
8. @YataFumika - S

あと、ゲストが２着と、当日お手伝いのスタッフが１着（XL）

計１１着

他に、ここに名前が挙がってなくてTシャツない人いませんかね？

**Comment by hasumikin** [comment]
Lサイズおねがいします

**Comment by ishikawa999** [comment]
名前挙がってなくてTシャツないです。
Sサイズでお願いします。

**Comment by yoshiokaCB** [comment]
@ishikawa999 すみません。ちょっと間違えて違う人のアカウントをあげてました！
申し訳ないです。

**Comment by hidakatsuya** [comment]
Mをお願いします。

**Comment by yatatatann1793** [comment]
(･ω･)/ 名前なくてTシャツ持ってません！
Sサイズをお願いします。

**Comment by yoshiokaCB** [comment]
@YataFumika 漏れてました。ごめんなさいm(_ _)m

**Comment by meg-k** [comment]
@yoshiokaCB 
Sサイズお願いします！

**Comment by yoshiokaCB** [comment]
@meg-k 
書き込みありがとうございます！
了解っす！

**Comment by sakasita001** [comment]
XLをお願いします！

**Comment by shakkun** [comment]
みなさま、書き込みありがとうございます。

下記の方々、サイズを確認いただいて書き込みをお願いします。
@HappySato 
@macera
@fsato0111

明日を締切日とさせていただいています。
よろしくお願いします。

**Comment by fsato0111** [comment]
すみません

Sをお願いします。

**Comment by macera** [comment]
遅くなってすみません。
160をお願いします。

**Comment by shakkun** [comment]
@macera @fsato0111 ありがとうございます(^_^)

**Comment by yoshiokaCB** [comment]
@shakkun 

以下のような集計になるかと思います。検算お願いします。

また、ゲストのサイズの確認が漏れてましたので確認します。すみませんが少々お時間ください。

# スタッフ

| サイズ | 枚数 |
| --- | --- |
| 160 | 1 |
| S | 4 |
| M | 1 |
| L | 1 |
| XL | 2 |

計 9

# プレゼント用

| サイズ | 枚数 |
| --- | --- |
| S | 1 |
| M | 2 |
| L | 1 |

計 4

**Comment by ml-yamaguchi** [comment]
すみません！！連絡が遅れてしまいました、Mを1つ追加可能でしょうか @shakkun

**Comment by shakkun** [comment]
@ml-yamaguchi ありがとうございます。追加しておきます！

**Comment by ml-yamaguchi** [comment]
@shakkun ありがとうございます、よろしくお願いします！

**Comment by yoshiokaCB** [comment]
@shakkun 

# ゲスト用

| サイズ | 枚数 |
| --- | --- |
| M | 2 |

計 2

となります。

**Comment by shakkun** [comment]
@yoshiokaCB

※XLを2枚→1枚に変更しました。

下記のサイズ・枚数で今週中に発注を考えています。
間にあえば次回ミーティングで配布できればいいなと思います。
送付先はどちらにしましょうか？
(特に指定なければ自宅で受取は可能です)

**スタッフ・プレゼント・ゲスト集計**

| サイズ | 枚数 |
| --- | --- |
| 160 | 1 |
| S | 5 |
| M | 6 |
| L | 2 |
| XL | 1 |
| 計 | 15 |

また、@HappySato さんから回答がありませんが連絡は可能でしょうか？

**Comment by yoshiokaCB** [comment]
@shakkun

> ※XLを2枚→1枚に変更しました。

えーと、XLを1枚に変更したのはどうされました？
当日、配信系のお手伝いで一人来るのでその人ように確保しときたいです。
（@sakasita001 とお手伝い）

> また、@HappySato さんから回答がありませんが連絡は可能でしょうか？

@HappySato のサイズはMでお願いします。

> 送付先はどちらにしましょうか？

後でメッセージで送り先を伝えます。

**Comment by shakkun** [comment]
@yoshiokaCB
すみません、見落としていました(>_<)
XL 2枚了解です。

では、Mサイズ1枚追加しておきます。

よろしくお願いします。

**Comment by yoshiokaCB** [comment]
@shakkun 
先ほど送り先をメールで送りました。
よろしくお願いします！

**Comment by shakkun** [comment]
先ほど注文しました。

定番Tシャツ
色：ホワイト

| サイズ | 枚数 |
| --- | --- |
| 160 | 1 |
| S | 5 |
| M | 7 |
| L | 2 |
| XL | 2 |
| 計 | 17 |

スパイスライフ様に連絡して進めていただくようお願いしました。

**Comment by yoshiokaCB** [comment]
@shakkun 
ありがとうございます！

**Comment by sho-h** [comment]
そういえばTシャツって申請(注文じゃない方)も終わってるんでしたっけ？終わってなくても実際に着るまでのどこかで問題なさげではありますが。

**Comment by shakkun** [comment]
@yoshiokaCB
Tシャツ、発送されました。11月17日(木)に届くと連絡がありました。よろしくお願いします！

**Comment by yoshiokaCB** [comment]
@shakkun 
連絡ありがとうございます！
楽しみです！！

**Comment by yoshiokaCB** [comment]
@sho-h 

> そういえばTシャツって申請(注文じゃない方)も終わってるんでしたっけ？終わってなくても実際に着るまでのどこかで問題なさげではありますが。

ナイス！
去年、多少多めに申請出したので…って話を聞いていたので大丈夫かもしれませんが、確認します。

**Comment by sho-h** [comment]
@yoshiokaCB そういえばそんな話だったかもですね。07+08で既申請分を超えなければいいという事ですね。

**Comment by yoshiokaCB** [comment]
@shakkun 
無事にTシャツ届きました！
ありがとうございましたm(_ _)m

**Comment by yoshiokaCB** [comment]
以下の方、Tシャツ配りました。

@meg-k - S
@YataFumika - S
@macera - 160
@ml-yamaguchi - M 
@sakasita001 - XL

もらってない人は、12/14の夜か当日の朝にお配りします。

**Comment by sho-h** [comment]
> もらってない人は、12/14の夜か当日の朝にお配りします。
@yoshiokaCB https://github.com/matsuerb/matrk/wiki/08_00_03_第三回ミーティング#候補 によると12/15の夜？(じゅ...15の夜！！？

@hidakatsuya @ishikawa999 @hasumon @fsato0111 @hasumon @HappySato @fsato0111 18時〜22時の間でラボに寄っていただいてTシャツを受け取る事は可能です？

**Comment by yoshiokaCB** [comment]
@hidakatsuya , @hasumon は12/16（金）にお渡しします。
@fsato0111 , @ishikawa999 はお渡し済みです。
@HappySato は当日渡します。（もしかするとそれまで渡すかも）

なので12/15（木）には特にお渡ししない予定です。

**Comment by sho-h** [comment]
りょうかいですー。

**Comment by hidakatsuya** [comment]
> 12/16（金）にお渡しします。

お手数おかけしてすみません。了解しました。

**Comment by yoshiokaCB** [comment]
配り終わったでクローズ
