### ISSUE TITLE
懇親会会場予約について

### ISSUE THREAD

**Issue by sakasita001** [matsuerb/matrk#8]
懇親会の会場につきまして、「四季庵」さんの3Fパーティルームを9/26（土）18：00～予約しました。

最大人数が立食で70名弱だそうです。（着席で60名）

四季庵さんHP
http://shiki-enterprise.com/matue_ekimae/index.html

**Comment by yoshiokaCB** [comment]
ありがとうございます！

**Comment by sakasita001** [comment]
@yoshiokaCB @sho-h @skenjiSugihara
料理と時間のコースについて相談させてください。
コース内容
　　　A貸切時間2時間、飲み放題90分、コース料理込　4,300円（生ビール等無）
　　　B貸切時間2時間半、飲み放題120分、コース料理込　4800円（生ビール等あり）

時間配分(決まってるものから)
オープニング　(？？)
スポンサーLT　70分(7分(発表5分場面展開2分)*10)
来季委員長決め　（??）
クロージング　（？？）

以上が判断材料になるかと思います。

**Comment by kenjiSugihara** [comment]
坂本さん、有難うございます！

現時点で数点、教えてくださいませ。

四季庵ですが、当日は貸切を想定していると思いますが、貸切る場合、最小執行金額又は人数の制約はありますでしょうか？
※例えば、テルサ２Fのカプリチョーザの場合、貸切では、約18万円を最低支払額として保証するシステムでは。

Aコース、Bコースの料金（それぞれ4,300円、4,800円）はそれぞれ消費税込みでしょうか？

人数確定は、何日前でしょうか？

今回のRuby会議の会計上のリスクは、収支の穴を埋める財源がないため、企業協賛金ももちろんですが、直接収入としては協賛金より多い、懇親会参加者数をどれだけ確保できるかですね。

時間を90分で行うか、120分で行うかは、スポンサーLT数でも拠ると思いますので、そちらの精査を急ぎます！

**Comment by sakasita001** [comment]
返信が遅くなってすいません。

最小執行人数は10名～です。

料金はそれぞれ税込です。

人数については、予測を九月頭にだして、確定は1週間前です。(キャンセルは25日(金曜)まで無料で対応してくれます。)

**Comment by kenjiSugihara** [comment]
早速のご確認を有難うございます！！！

**Comment by yoshiokaCB** [comment]
@sakasita001 さん

会場って立食でしょうか？
それとも座席に座ってでしょうか？
何か前に聞いた気もしますが、忘れてしまって。。。
立食の場合の定員と座っての場合の人数も教えてもらえると嬉しいです。

**Comment by sakasita001** [comment]
定員は座席で60人、立食で70人です。
立食についてお店としての定員はないですが、動く事考えるとこれぐらいとの事でした。

形式は確定はしていません。
どちらの形式も選択可能だと思います。

事前のお話では立食になっていたかと思います。
理由は、「人が気軽に動いたほうが交流が生まれるから」だったかと思います。

**Comment by kenjiSugihara** [comment]
ここでよいか分かりませんが、懇親会でLTを希望するスポンサーは次のとおりです。

■懇親会でのプレゼン・スポンサー８社（協賛お申込み順）
テクノプロジェクト
ファーエンドテクノロジー
フォックス・リレーション
八雲ソフトウェア
ネットワーク応用通信研究所
システムリンク
フェンリル
モンスター・ラボ
