### ISSUE TITLE
スタッフ用のタイムテーブルを作る

### ISSUE THREAD

**Issue by tomo-k** [matsuerb/matrk#80]
昨年の反省点からスタッフ用のタイムテーブルを作成する。
例）
・機材の準備・撤去
・集合写真

**Comment by yoshiokaCB** [comment]
・集合時間
・会場のセッティング変更（ライブコーディング用のスクリーンの設置）

**Comment by tomo-k** [comment]
@inoh 
@yoshiokaCB 
集合写真クロージング後で時間的に大丈夫ですかね？

**Comment by yoshiokaCB** [comment]
まつもとさんが途中で帰られると思うので、講演が終わったところで撮影もありかなと思っています。
集合写真にまつもとさんもいると嬉しいので。
進行上どうですかね？

ちなみにクロージングでしたら対して話すことないので写真撮影の時間に使って問題ありません。

**Comment by yoshiokaCB** [comment]
> amidaku [8:25 AM]  
> 集合写真となるとカメラマン位置のことを考えるとお客さん帰ったあとが良いですかね。

了解っす！
ではクロージングにしましょう！

**Comment by yoshiokaCB** [comment]
宣伝用にスタッフの集合写真を撮る。（スタッフTシャツ着用）
可能であれば、ゲストも一緒に撮りたい。

**Comment by tomo-k** [comment]
集合写真以外特にない感じですかね？

@yoshiokaCB 
会場前にスタッフのみで集合写真、クロージングで参加者含めて集合写真撮るで、計２回撮るイメージで良いでしょうか？

**Comment by amidaku** [comment]
@tomo-k 
会場前というのは、時間のこと？場所のこと？
スクリーン前で撮影ならマイクやらテーブルやらのセッティングの関係もあるので、クロージング後が良いと思います。大会議室の前（外側）のスペースならいつでも良いかな？
参加者含めた撮影については、かなりテーブルを後ろに寄せる必要があると思うので、すべてのコンテンツが終了してからということになるのかなと思います。

**Comment by tomo-k** [comment]
@amidaku
@yoshiokaCB  
すみません。×会場前→○開場前ですね。
開場前にゲストの方に来ていただけるのかどうかもありますね。
前々回は @amidaku  さんが機材の片付け等で集合写真に入れなかった記憶があるので、そのあたりも踏まえてですね。。

**Comment by yoshiokaCB** [comment]
@tomo-k 
@amidaku 
諸々了解です。

では、以下のような感じでどうですかね？

1. 朝スタッフが集まったら大会議室の前で写真撮影（準備で忙しい人は除く。）
1. クロージングの後に机を動かして、会場内で撮影（忙しい人も一旦手を止めて集まる。）

朝の集合写真はゲストの方は間に合わなければ、仕方ないとしましょう。

**Comment by tomo-k** [comment]
@yoshiokaCB 
ありがとうございます。それでいきましょう！
