### ISSUE TITLE
第三回　ミーティングについて

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#81]
下記日程でミーティングを開催したいと思います。ご都合のつく方はご参加お願いします。

日時：10/15（土） 午後4時〜
場所：オープンソースラボ

基本的には進捗状況の共有になるかと思います。
議題等詳細は後ほどアップします。

**Comment by yoshiokaCB** [comment]
@tomo-k 

次回ミーティングの議題作成をお願いします！

自分の方からは以下のようなことをみなさんに相談しときたいです。
- rubyquizについて（問題を作ってくれる人集める。）
- 懇親会について
- 昼食LTについて
- まつもとさんへの依頼内容を決定する。

**Comment by tomo-k** [comment]
@yoshiokaCB 
次回ミーティングのたたき台作りました。
issue から拾いましたが、追加があったらおしらせください。

[第３回ミーティング議題](https://github.com/matsuerb/matrk/wiki/08_00_03_%E7%AC%AC%E4%B8%89%E5%9B%9E%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0)

**Comment by hidakatsuya** [comment]
議事録ってどなたか書かれていたのでしょうか？ @yoshiokaCB さんやファシリテータの方が記録するのは難しいので、次回MTGから議事録係を決めてから始めると良いと思います。

**Comment by yoshiokaCB** [comment]
@hidakatsuya 議事録はwikiにのミーティングのところに書かれています。
https://github.com/matsuerb/matrk/wiki

[第３回ミーティング 議事録](https://github.com/matsuerb/matrk/wiki/08_00_03_%E7%AC%AC%E4%B8%89%E5%9B%9E%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E8%AD%B0%E4%BA%8B%E9%8C%B2)

副委員長として全容を把握しておいてほしいと思い、議事録係は基本的に @tomo-k にお願いしています。本人に確認して負担が大きいようでしたら次回から別の人にお願いしましょう！

これも終わってたんでクローズしときます。
