### ISSUE TITLE
当日の会場の掲示物

### ISSUE THREAD

**Issue by teeta32** [matsuerb/matrk#82]
当日の会場掲示物として、今年は以下を追加する。
- ポスター (入口の扉用)
- Twitter のハッシュタグ

この他、必要な掲示物を追記する。
- WiFi の SSID とパスワード

**Comment by yoshiokaCB** [comment]
タイムテーブルも追加でお願いします。（大きめの紙で）

**Comment by teeta32** [comment]
@yoshiokaCB タイムテーブル了解しました。

**Comment by yoshiokaCB** [comment]
各スポンサーの企業名をそれぞれA4で印刷しときたいです。
各社の景品を企業名と一緒にディスプレイしたいと思っています。

**Comment by yoshiokaCB** [comment]
@teeta32 
以下の物は自分が印刷してもらって12/16にラボまで持っていきます。

| 項目 | 枚数 |
|----|---|
| リールレットのポスター(A1) | 2 |
| タイムテーブル(A1) | 2 |
| 企業名の印刷(A4) | 1 |

**Comment by teeta32** [comment]
@yoshiokaCB  だんまりで申し訳ないです。上記、了解です。
以下は、自分が印刷をお願いして用意します。

|項目|枚数|
|--|--|
|Twitter のハッシュタグ(A2)|4|
|WiFi SSID(A2)|4|
|WiFi パスワード(A2)|4|

**Comment by teeta32** [comment]
@yoshiokaCB Twitter のハッシュタグを確認させてください ♯matrk08 で良いでしょうか。

**Comment by yoshiokaCB** [comment]
@teeta32 

> Twitter のハッシュタグを確認させてください ♯matrk08 で良いでしょうか。

それで OKです！

**Comment by teeta32** [comment]
了解です。

**Comment by teeta32** [comment]
以下を届けていただきました。サイズはA1より大きそうです。A0でしょうか。

| 項目 | 枚数 |
|----|---|
| リーフレットのポスター | 2 |
| タイムテーブル| 2 |

**Comment by yoshiokaCB** [comment]
はい。A0です！

**Comment by teeta32** [comment]
A1,A2サイズの印刷がうまくいかないとのことだったので、以下は当方にて A3 で用意します。

|項目|枚数|
|--|--|
|Twitter のハッシュタグ|4|
|WiFi SSID|4|
|WiFi パスワード|4|

**Comment by yoshiokaCB** [comment]
あらー(^^;;)
すみませんがよろしくお願いいたしますm(_ _)m

**Comment by teeta32** [comment]
Twitter のハッシュタグ等の印刷を @sada に引き受けてもらいました。

**Comment by sada** [comment]
Twitter のハッシュタグ等のA3サイズを4部ずつ印刷したので、本日のミーティング時に持って行きます。

**Comment by teeta32** [comment]
ありがとうございます。了解しました。

**Comment by teeta32** [comment]
@sada 会場の無線の SSID を変更するので、 SSID をA3サイズで4部印刷をお願いします。 印刷原稿をこれからメールします。お手数をおかけしますが、よろしくお願いします。

**Comment by sada** [comment]
@teeta32: メールにてお送りいただいた SSID の印刷原稿をA3サイズで4部印刷しました。当日の準備に持って行きます。よろしくお願い致します。

**Comment by teeta32** [comment]
@sada ありがとうございます。お手数おかけします。

**Comment by teeta32** [comment]
開催が終了しましたのでクローズします。
