### ISSUE TITLE
スポンサーのロゴ画像をWebサイトに表示する

### ISSUE THREAD

**Issue by sada** [matsuerb/matrk#83]
スポンサーのロゴ画像を松江Ruby会議08のWebサイトに表示する。

**Comment by shakkun** [comment]
Tシャツスポンサーのスパイスライフ様のロゴ掲載をよろしくお願いいたします。m(_ _)m

tmix→TMIXに変更されたのと、ロゴも変更になったとのことでデータをいただきました。
どなたにデータはお送りすればよろしいでしょうか？

**Comment by sada** [comment]
@shakkun: 私か @inoh さんに画像を送っていただけると助かります。
よろしくお願い致します。

**Comment by shakkun** [comment]
@sada 
さきほどメールでお送りしました。
よろしくお願いいたします。

**Comment by sho-h** [comment]
残りのスポンサーさんについて対応する時に matsuerb/matsuerb-nanoc#399 でマージしてない分の削除/修正もよろしくお願いします。 @sada

**Comment by kenjiSugihara** [comment]
他のスポンサーロゴ、入手しているものから @sada さんにお送りしてよろしいでしょうか？
スポンサー了解確認のまだの企業様も含めて急ぎます。

**Comment by sada** [comment]
@sho-h:
了解です。
残りのスポンサー様のロゴ画像の対応時に削除/修正します。

@kenjiSugihara:
既にいただいているロゴ画像は、私に送っていただけると助かります。
お手数をお掛けしますが、スポンサー様への確認よろしくお願い致します。

**Comment by sada** [comment]
> マージしてない分の削除/修正もよろしくお願いします。 

松江Ruby会議08のスポンサーのロゴ画像を表示し、使用していないロゴ画像は削除しました。
そのため、このissueは閉じます。
