### ISSUE TITLE
サブスクリーンのスクリーンの設置場所の確認

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#84]
@amidaku

> そろそろ当日の設備関係考えないといけないですが、まず不確定要素として、会場後方のプロジェクタ画像ディスプレイのことがあります。
> プロジェクタの持ち込みで表示するか、TV等モニターに表示するか、また何台設置するかについて決めないといけないですね。
> 
> 専用にLANを組むのでネットワーク関係の方々に関係するかなーという気がしてます。私が当日オープニングまでは作業に加われないので、事前に手順など完結しておかないといけないなと思ってます。

**Comment by yoshiokaCB** [comment]
まず、当日はメインスクリーンと横にサブスクリーンを設置してtwitteerを流したいと思っていました。
ここまでは去年と同じです。

それで、今年は後ろの人もコードが見やすくなるように、後方の左右に二つスクリーンを設置したいでと思っています。

プロジェクタはラボのものを一つ借りるのと、自分の会社のやつを手配しようかと思っています。
メインスクリーン横のサブスクリーンも常時設置するのであればもう一つ手配しないといけないですね。

タイミングとしては基調講演が終わったところで設置できると良いかなと思っています。

**Comment by amidaku** [comment]
放置プレイしてました。
この仕組みを実現するのに、ラボのMacをお借りして画面共有で対応しようと思います。
会場のLANとは別に画面共有専用のLANを作って、そのLANにMacを繋げます。
- Macのセットアップ
- 専用LANの設置

が必要ですが、私が当日中継関係のセットアップで対応できないので、これらの全てのタスクを会場準備班の方々にお願いしてよいでしょうか？

**Comment by amidaku** [comment]
ちなみに **Macのセットアップ** には、 
- 講師のPCのディスプレイ信号（VGA）のキャプチャ設定
- 画面共有の設定
- 後方プロジェクタへの投影

が含まれます。

**Comment by yoshiokaCB** [comment]
@amidaku 

> これらの全てのタスクを会場準備班の方々にお願いしてよいでしょうか？

了解です。お願いしましょう。

あと、11/27（日）にミーティングをする予定ですが、来れますか？
その時に担当者を決めて作業内容の確認をしたいと思います。
参加が難しかったらここかslack使ってやりとりをしたいと思います。

**Comment by yoshiokaCB** [comment]
あと、設置のタイミングはゲスト講演2が終わったタイミングですね。( - 15:20 )

**Comment by amidaku** [comment]
@yoshiokaCB 
11/27大丈夫ですよ。

**Comment by amidaku** [comment]
映像関係のレイアウトと系統についてファイルUPします。
[松江Ruby会議08映像関係.pdf](https://github.com/matsuerb/matrk/files/618002/Ruby.08.pdf)

@teeta32 さん、ご確認をお願いします。
セットアップは開場までに済ませ（Macのデスクトップ共有も済ませておく）、会場中ほどのスクリーンは、プロコンが終わるまでは下げておきます。
プロコンが終わり、ライヴコーディングが始まるまでにスクリーンを上げ、プロジェクタをONにするなどします。
その後クロージングまでこの形をとります。

**Comment by teeta32** [comment]
@amidaku さん、資料を確認しました。
セットアップは開場までに済ませ（Macのデスクトップ共有も済ませておく）了解です。

会場中ほどに設置するスクリーンに画面を表示する時期を確認させてください。

会場中ほどに設置するスクリーンは、プロコンが終わるまでは使わない。
プロコンが終わり、ライヴコーディングが始まるまでに会場中ほどのスクリーンに
画面を表示する流れで良いでしょうか。
(@amidaku さんが書かれたスクリーンを上げる、下げるの意図を取り違えていないか確認させてください。)

**Comment by amidaku** [comment]
@teeta32 
サブスクリーンの使用目的は、ライブコーディングとRubyQuizで、講演者のPC画面を会場のスクリーンにだけ投影したのでは文字が見にくいため会場の後方の参加者にも見てもらえるように設置するものです。

ただし、常にスクリーンを出しておくと一部の席からは前方が見にくくなります。

* セミナーセッションは講演者が主役
* ライブコーディングとRubyQuizは画面が主役

との考え方で整理し、ライブコーディングとRubyQuizの時だけスクリーンを上げて表示します。

セットアップについての時間がセッション前後の時間では難しいこともあり、開場までにすべてのセットアップを終え（できればプロジェクタとスクリーンの位置関係やフォーカスも含めて）、ライブコーディングの前の時間は、

* プロジェクタの電源ON
* スクリーンを上げる
* 画像の確認

のみ行っていただくのが良いと考えました。

**Comment by teeta32** [comment]
@amidaku 
説明ありがとうございます。会場中ほどに設置するサブスクリーンは
ライブコーデイングとRubyQuizのときだけ使用すること了解しました。

**Comment by teeta32** [comment]
@yoshiokaCB 
twitter 表示用のサブスクリーンをどうしましょうか。
プロジェクタとスクリーンを用意できるかではありますが、スクリーンの設置でバタバタしないように
会場中ほどに設置するスクリーンと別に twitter 用に一式用意でしょうか。。

**Comment by yoshiokaCB** [comment]
@teeta32 

> twitter 表示用のサブスクリーンをどうしましょうか。

今回は無しにしようと思います。
前においても後ろの人は見えないし、特にそれを使って何かする予定もないので。

ちなみにですが、もともとはオープンソースラボで開催していた時に、会場の賑やかしというか、
twitterで流れてきた質問とか感想を司会者が拾って場をつなぐという流れがあって設置してました。
今回は会場の広さやコンテンツの関係もあって、スクリーンを置く必要はないと判断しました。

**Comment by teeta32** [comment]
@yoshiokaCB
twitter用スクリーンを用意しないこと了解しました。

**Comment by teeta32** [comment]
@amidaku サブスクリーンの表示に使う Mac 用に thunderbolt VGA 変換アダプタを1つお貸しいただけないでしょうか。

**Comment by yoshiokaCB** [comment]
@teeta32 
先ほど @amidaku さんから連絡があり、OKとのことです！

**Comment by teeta32** [comment]
上記、了解しました。
@amidaku さん、 @yoshiokaCB さん ありがとうございます。
もう一台あるサブスクリーン表示用Macで使う thunderbolt VGA 変換アダプタは別途にお借りしています。

**Comment by teeta32** [comment]
サブスクリーンに使用した機材の返却は済んでいると思います。
開催が終了しましたのでクローズします。
