### ISSUE TITLE
マシュマロチャレンジに向けた調整

### ISSUE THREAD

**Issue by sakasita001** [matsuerb/matrk#86]
- [x] 司会の決定　sakasita001
- [x] 台本の作成（スライド）　未完成
https://docs.google.com/presentation/d/1KaaVOl29459q9W5c9md3C3rvn-O9BdFU0eWV-A_sxSg/edit?usp=sharing
- [x] 座席のセッティング（中会議室の図面を印刷して作業）
　　中会議室備え付け　21
       ケータリング使用分:8（6+2）
　　懇親会会場使用　3（受付台1荷物置き2）
　　マシュマロチャレンジ使用分　10（1×10チーム）
- [x] 事前準備の洗い出し
  - [ ] 音響について、テルサの方から説明を受ける
  - [x] はさみとメジャーの準備
- [x] チーム決めの方法　入口で紙のくじを引く
- [x] 予算捻出
- [x] 景品　　懇親会担当からも案を出す。
- [x] 開始時間　【案】乾杯後10分程度（乾杯後にアナウンスで番号の席に固まっていてもらう）

**Comment by kenjiSugihara** [comment]
お疲れ様です！
予算担当で気になりますのが、マシュマロ・チャレンジの予算を計上していない点です。
Slackのafterpartyにコメントしましたが、現時点で若干の赤字です。
仮に学生枠を現在の10名から8名にすると約1,800円をマシュマロ・チャレンジに充当可能です（が、収支に全くの余裕がなく、かなり不安です）。
いっそ、学生枠を7、又は6にするとか！？

**Comment by yoshiokaCB** [comment]
@kenjiSugihara 
他の人の意見も聞きながらですけど、お酒飲む人は200 - 300円程度多めに集めるとかもできるかもしれません。元の値段が割と安めなので。

**Comment by yoshiokaCB** [comment]
マシュマロチャレンジの景品はスポンサーに準備をしてもらう。（ティーエム21担当）
景品は4つ準備する。

@sakasita001 
昨日の話で何か共有等が必要な事はこちらかslackにまとめておいてください！
（公開して良い内容かどうかは判断してみてください。）

**Comment by sakasita001** [comment]
@yoshiokaCB さん

昨日でたお話しをチケットの頭にまとめました。

タイトルを書いただけですが台本のスライドも後ほどURLを共有します。（googleスライド）

**Comment by sakasita001** [comment]
ケータリングについてやり取りをしたので反映

**Comment by yoshiokaCB** [comment]
# 懇親会の流れ

| 時間 | 内容 |
|----|----|
|18:00|乾杯|
|18:30|マシュマロチャレンジ|
|19:00|マシュマロチャレンジ表彰|
|19:10|懇談|
|20:00|ドリンクラストオーダー|
|20:20|締め|

## 備考（メモ）
 - マシュマロチャレンジの時は机を一旦片付ける。
 - 乾杯の後に、マシュマロチャレンジの開始時間を告げてそれまでに机が片付くように促す。
 - 開始時にマシュマロチャレンジの道具はすべて置いておく。
 - グラスを2セット準備
 - クロスを貼ってもらう

**Comment by yoshiokaCB** [comment]
準備物
 - ハサミ * 10
 - メジャー * 10

**Comment by yoshiokaCB** [comment]
吉岡
ハサミ 2つ準備
メジャー 2つ準備

**Comment by sakasita001** [comment]
坂本
はさみ二つ
メジャー二つ

**Comment by yoshiokaCB** [comment]
@eijik
ハサミ2つ
メジャー2つ

**Comment by yoshiokaCB** [comment]
@ToruKurahashi
ハサミ2つ
メジャー2つ

@sho-h 
ハサミ1つ
メジャー1つ

今のところ計9セット確保！

**Comment by yoshiokaCB** [comment]
| アカウント | ハサミ | メジャー |
|----|----|----|
| @yoshiokaCB | 2 | 2 |
| @sakasita001  | 2 | 2 |
| @sho-h | 1 | 1 |
| @ToruKurahashi | 2| 2 |
| @fsato0111 | 1 | 1 |
| 計 | 8 | 8 |

できれば前日の12/16にラボまで持ってきてもらえると助かります。

**Comment by sakasita001** [comment]
スライド、レビュー結果反映と背景テーマ適応しました。
頭の一枚に荷物を椅子に置くようにお願いを書きました

**Comment by sho-h** [comment]
返却についてですが、このメンツだと明日(12/21)に受け取るのがよさげですかねぇ。

**Comment by sakasita001** [comment]
物品の返却が無事終わったとのことなのでクローズします。
ご協力いただき、本当にありがとうございました。
