### ISSUE TITLE
プロコンの開始

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk#88]
ぼちぼちの予定だが、まだいつかは決まってない。

**Comment by yoshiokaCB** [comment]
本当に遅くとも11/24（島根ITコミュニティー交流会）までにはスタートして宣伝したいですm(_ _)m

**Comment by sho-h** [comment]
たしかにー

**Comment by sho-h** [comment]
今日の18:30頃に公開して宣伝も完了しました。
