### ISSUE TITLE
リーフレットを配布・設置する

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#89]
# 配り先の学校

事前に各学校の先生に配布OKか確認を行い、リーフレットの配布依頼をする。

 - [x] 島大で配布可能か確認する
 - [x] ビジ専で配布可能か確認する
 - [x] 松江高専で配布可能か確認する
 - [x] 島大 50枚　配布依頼をする
 - [x] ビジ専 50枚　配布依頼をする
 - [x] 松江高専 80枚　配布依頼をする
 - [x] コアカレッジ 30枚　配布依頼をする

# 設置先の施設

各施設に設置可能か確認し、リーフレットを設置する。

 - [x] ソフトビジネスパークで設置可能か確認する
 - [x] オープンソースラボで設置可能か確認する
 - [x] オープンソースラボ 35部　設置する
 - [x] ソフトビジネスパーク 20部　設置する

# 友人、知人経由の配布依頼
 - [x] 浜田高校 ?枚　配布依頼をする（印刷も依頼）
 - [x] 情報科学高校 30枚　配布依頼をする

**Comment by Takashi-U** [comment]
どういった配り方を想定されているか不明ですが、場合によっては学校や行政の許可が必要かもしれません。無論、許可を得る必要があったとしても、内容的には問題無いとは思いますが、確認した方が良さそうです。

学校に直接お願いするのであれば、そこで許可の事も出るでしょうが、例えば生徒さんにお願いするなら、主催側で電話して問い合わせてからが良さそうですね。

大学ならN先生へのお願いもアリかもですね。

**Comment by yoshiokaCB** [comment]
指摘ありがとう！
それぞれの学校の先生に依頼済みですので、ご安心を！！

説明がなく、ちょっとメモ的に使い過ぎたので、後で修正しときますm(_ _)m

**Comment by sho-h** [comment]
OSSラボとテクノアークにも置いておきたいですね。それぞれ20部くらい？

**Comment by sho-h** [comment]
OSSラボとテクノアークは学校じゃないからチケット分けるべきかも。

**Comment by yoshiokaCB** [comment]
@sho-h 
タイトル変えてまとめちゃいますか？
そんなに大きなタスクではないのでまとめても良い気がします。

**Comment by sho-h** [comment]
@yoshiokaCB なるほど。ありですね。

**Comment by yoshiokaCB** [comment]
修正しました。
各学校へは、doorkeeperの公開後に配布したいですね。
なので、今夜あたりdoorkeeperの公開できればと考えています。

**Comment by sho-h** [comment]
仮に今あがってる数字で合計220配る予定としてあと82部です。取り急ぎ思いつくのは皆さんが自社で貼る用に何部か取るとして何人が何部くらいです。それは11/27までに皆で決めてもらうのがいいのかなぁ。僕は壁に貼ったりするので5部くらい欲しいけど、最低3部あればたぶん大丈夫です。欲しい人多いようならまずはラボとテクノアークを少し減らすとかでも調整可能かもしれません。

**Comment by yoshiokaCB** [comment]
@sho-h 
そうですね。
米子高専に何枚必要かによりますね。
皆さんここで良いので欲しい枚数を教えて欲しいです。

（足りなくなったら、会社とかは皆さんで印刷をお願いするかもしれません。）

**Comment by amidaku** [comment]
SITWへの学生等参加は、
- 米子高専（先生1名、学生8名）
- 松江高専（学生2名）
- 松江市内高校生（生徒1名）

という状況です。
まぁ高校生は身近な方で、松江Ruby会議08当日は授業なので配布不要ですが。

**Comment by yoshiokaCB** [comment]
@amidaku 
ラボにとりあえず35部おいておくので、そこから適当に配ってもらうとかでも良いですか？

**Comment by amidaku** [comment]
@yoshiokaCB OK!

**Comment by yoshiokaCB** [comment]
@amidaku 
ラボに設置完了っす。
![15036444_946193358818520_5711809362711561485_n](https://cloud.githubusercontent.com/assets/4011289/20302548/127bfdc0-ab6b-11e6-9a73-485446397750.jpg)

**Comment by sho-h** [comment]
@yoshiokaCB お疲れさまです！サイトの更新後にtwitterでつぶやこうと思うんですけど、この画像使わせてもらってもいいですか？

**Comment by yoshiokaCB** [comment]
@sho-h いいですよー。

**Comment by sho-h** [comment]
@yoshiokaCB どもですー。

**Comment by yoshiokaCB** [comment]
コアカレッジにも30枚お持ちしました。
よってここのタスクは終了したのでクローズします。
