### ISSUE TITLE
第四回　ミーティングについて

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk#90]
下記日程でミーティングを開催したいと思います。ご都合のつく方はご参加お願いします。

日時：11/27（日） 午後4時〜
場所：オープンソースラボ

今回はRubyQuizのリハーサルと進捗状況の共有になるかと思います。
議題等詳細は後ほどアップします。

**Comment by yoshiokaCB** [comment]
@tomo-k

次回ミーティングの議題作成をお願いします！

自分の方からは以下のようなことをみなさんと情報共有したいです。
- 進捗状況の確認
- プロコンの説明
- クイズのリハーサル

先に情報共有をしてそのあとに、リハーサルをしたいと思いますがどうでしょうかね？

**Comment by amidaku** [comment]
私の方では、会場準備班の方と
- 提供インターネット
- サブスクリーン関係（別系統LAN含む）

の話を詰めておきたいです。  
当日、私は中継始まるまでは、たぶん会話も遠慮したいぐらいテンパってると思うので。

あとはカメラ位置とか中継機材の場所を決めておきたいですね。
（各セッションの進行役と講演者等の立ち位置の確認）

PS.
17時ごろ帰ります。

**Comment by yoshiokaCB** [comment]
@amidaku 
レスありがとうございます！了解です！

**Comment by teeta32** [comment]
会場準備班として @amidaku さんから相談いただいたネットワークの準備に対応します。

去年の開催等を踏まえて会場のネットワークの案を提示します。
当日に会場準備班と中継班が別々に担当の準備ができるように調整します。

都合がつかないため、私は打合せ(11/27)に欠席するので
打合せより前にネットワークの案を用意します。

**Comment by yoshiokaCB** [comment]
@tomo-k 
以下、こちらでまとめられるとこまとめました。
確認してもらって追記があれば、お願いします。

https://github.com/matsuerb/matrk/wiki/08_00_04_%E7%AC%AC%E5%9B%9B%E5%9B%9E%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0

**Comment by tomo-k** [comment]
@yoshiokaCB 
ありがとうございます！
作りかけてたのとマージしておきます。

**Comment by yoshiokaCB** [comment]
@tomo-k 
返信遅くなりましたがありがとうございますm(_ _)m

**Comment by tomo-k** [comment]
@yoshiokaCB 
ほとんど書いていただいていたので、差分だけ追記しておきました！

**Comment by teeta32** [comment]
協議事項に挙がっている項目「予算作成について（懇親会、会場準備）」の検討のため
会場からレンタルする物品の確認を皆さんにお願いしたいです。

今年の開催で、去年と変わる部分があるか確認をお願いしたいです。
去年会場からレンタルした物品を Slack の planning チャンネルに貼っています。

よろしくお願いします。

**Comment by yoshiokaCB** [comment]
ミーティング終わったのでクローズします。

@tomo-k 
すみませんが、議事録の作成お願いしますm(_ _)m
