### ISSUE TITLE
賞品の情報をWebサイトに表示する

### ISSUE THREAD

**Issue by sada** [matsuerb/matrk#91]
第四回ミーティングで話があった賞品の情報をWebサイトに表示する。

**Comment by yoshiokaCB** [comment]
# プログラミングコンテスト・RubyQuiz 賞品（予定）
 - **Raspberry Pi 3／ラズパイマガジン10,12月号／ラズパイマガジン企画部品セット**  
（株式会社イーストバック様　ご提供）

 - **Amazonギフト券10,000円分**  
（株式会社島根情報処理センター様　ご提供）

 - **オライリー図書館からお好きな書籍1万円分を贈呈**  
（ファーエンドテクノロジー株式会社様　ご提供）

 - **Ruby関連書籍３冊**  
（株式会社八雲ソフトウェア様　ご提供）    
   - Rubyによるクローラー開発技法 巡回・解析技能の実装と21の運用例
   - Rubyで数独：AIプログラミング入門
   - 恋するプログラム―Rubyでつくる人工無脳 (プレミアムブックス版)  
　
 - **タブレット（8or16GB）**  
（株式会社日本ハイソフト様　ご提供）


### 備考
 - 掲載されている商品は予告なく変更せれる場合があります。
 - 掲載さている内容は一部です。

--- 

今の所こんな感じです。

**Comment by ToruKurahashi** [comment]
一番上のやつは
・Raspberry Pi 3／ラズパイマガジン10,12月号／ラズパイマガジン企画部品セット
でお願いします。

**Comment by yoshiokaCB** [comment]
@ToruKurahashi ラジャー！

**Comment by sho-h** [comment]
@kenjiSugihara さんに掲載OKか確認いただいてるのでしたっけ？その後どうですか？

**Comment by yoshiokaCB** [comment]
@sho-h 
@kenjiSugihara さんには確認済みです。
各社OKを頂いております！

**Comment by sho-h** [comment]
@yoshiokaCB 了解です！

**Comment by sho-h** [comment]
サイトの更新まで完了しました。
