### ISSUE TITLE
受付の準備

### ISSUE THREAD

**Issue by shakkun** [matsuerb/matrk#92]
必要なもの

* 参加者リスト
* お弁当引換券
*  懇親会参加券
* 領収書(お弁当・懇親会一般・懇親会学生の3種類)
* お釣り

過去のテンプレートお持ちでしたら、送っていただけると助かります。

**Comment by KaoriMatsuoka** [comment]
全て用意するので大丈夫ですよ。
（領収書、引換券、参加券は杉原さんから私宛に郵送済）

**Comment by shakkun** [comment]
@KaoriMatsuoka よかったです。ありがとうございます！助かります。

**Comment by KaoriMatsuoka** [comment]
領収書等、無事手元に届きましたので、ご報告(^-^)

**Comment by yoshiokaCB** [comment]
@KaoriMatsuoka 
昨日お話ししましたが、受付用紙は懇親会の参加者がわかるリストも用意しておいてもらえると助かります。
あと、懇親会の参加者リストは懇親会の受付担当に渡してあげてください。

**Comment by KaoriMatsuoka** [comment]
懇親会参加者リストの件、了解です！

**Comment by sho-h** [comment]
closeして大丈夫な気がするのでcloseしちゃいますね！
