### ISSUE TITLE
プロコン結果集計

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk#93]
以下より。12/15予定。

* https://github.com/matsuerb/matrk/wiki/08_00_03_第三回ミーティング#候補

**Comment by sho-h** [comment]
@yoshiokaCB @tomo-k @ToruKurahashi @nishidayuya 集合は18〜19時で来れる人から早めとかでいいでしょうか？

**Comment by sho-h** [comment]
ラボは18時から押さえてもらってるので18時でいいですな。

**Comment by nishidayuya** [comment]
良いんじゃないでしょうか．早めに来ます．

**Comment by yoshiokaCB** [comment]
了解です。
早めに行きます。

**Comment by sho-h** [comment]
完了。
