### ISSUE TITLE
るびまにレポートの作成

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk#96]
以下の作業を行う。

* [x] 人を集める
* [x] 担当を決める
* [x] 締切を決める
    * ~~年3,4回だと思うので、遅くとも2月や3月かなぁ~~4月末
* [x] それぞれがブランチにPRする

**Comment by sho-h** [comment]
メンツについては事前に何もしてなかったので昨年の人たちに直接声をかけました。( @tomo-k さんだけ直接お願いしそこねたー…orz 今年もお願いしても大丈夫ですか？

**Comment by sho-h** [comment]
@amidaku 動画を見ながらレポート作ろうと思っているのですが、未編集のものをいただく事は可能です？サイズによるかもですが。

**Comment by amidaku** [comment]
@sho-h 今回オープニング動画を作ってもらうのでその後の公開になるので、編集がちょっと遅れるかもですね。
編集前動画ありますよ。サイズ小さいです。全部で50GBぐらいです。

**Comment by tomo-k** [comment]
@sho-h 
大丈夫です！

**Comment by sho-h** [comment]
タイトル、資料等は[こちら](https://github.com/matsuerb/matrk/wiki/08_07_当日の予定（注意事項）)を参照

**Comment by sho-h** [comment]
ちょっとタスクが詰まってて間がしばらく空いてしまいました。すみません。

@tomo-k , @nobyuki, @sada, @inoh その後[動画](https://www.youtube.com/playlist?list=PLbJxhePIoIPBU5f0cAn4BceCG48EGSHsA)も上げてもらいましたんでぼちぼち担当を決めて消化していきたいと思います。各自担当の希望あります？1人1つ〜2つになるんじゃないかと思います。LTはまとめて1人にお願いしようかと思います。特になければ決めちゃいます。

**Comment by sho-h** [comment]
あ、そうだ。プロコンなど編集が多いものはもう少しあとという事ですので、プロコンは僕がやろうかと。

**Comment by nobyuki** [comment]
Ruby Quiz については、やった本人ですけど私が担当したいです。
各問題の正答率にも軽く言及した方が良いように思いますが、動画を見るだけだとちょっと確認が難しいかなと思いました。
私はなんとなく覚えてますので^^;

**Comment by tomo-k** [comment]
@sho-h さんの方で割り振り決めていただいて大丈夫です！
ちなみに締め切り当初は3月くらいにしてましたけど、エンドどうしましょうか？

**Comment by inoh** [comment]
@sho-h さんご無沙汰しております！
アサインはおまかせしますー

**Comment by inoh** [comment]
動画からクラウド使って自動で文字おこしとかできないかなぁ

**Comment by sho-h** [comment]
みなさんありがとうございますー。では今週のどこかでランダムで決めちゃおうかと思います。締め切りはとりあえず4末かGW空けかにでもして、次号に間に合わないようなら次々号に載せていただこうかと。

**Comment by sho-h** [comment]
[レポートのドラフト](https://github.com/sho-h/rubima/blob/matsue-rubykaigi08/articles/draft/regional_rubykaigi_report/matsuerubykaigi08.hiki)を作成しました。

担当については以下でお願いできればと思います。

|     |        枠          |    担当者    |
|-----|--------------------|--------------|
| [x] | ゲスト講演1        | @tomo-kさん   |
| [x] | 基調講演           | @inohさん    |
| [x] | ゲスト講演2        | @sadaさん    |
| [x] | プロコン           | @sho-h       |
| [x] | ライブコーディング | @sadaさん    |
| [x] | Ruby Quiz          | @nobyukiさん |
| [x] | その他(写真選別)   | @inohさん |

**Comment by sho-h** [comment]
> 文字起こし

議事録とかでやってるサービスはあるかもですけど、有料かもしれませんね。

**Comment by sho-h** [comment]
進行中。締め切りが8/13になったので、遅くなったけど7月中には片付けたいところ。

**Comment by sho-h** [comment]
上のリストに写真の項目を追加してそっと @inohさん にしました！また写真くださいー。

**Comment by sho-h** [comment]
写真いただいたので反映して上をチェックした。自分の分は後少しでPRしようかなといったところ。(この月火くらいで)

**Comment by sho-h** [comment]
プロコンも書いた。締め切りまでに他のものも含めて見直しとpingの予定。

**Comment by sho-h** [comment]
@amidaku YouTubeのURLを https://www.youtube.com/playlist?list=PLbJxhePIoIPBU5f0cAn4BceCG48EGSHsA してるんですけど、より良いURLあります？(まだ上がってない動画についてはできた時でいいかななんて思ってます

**Comment by sho-h** [comment]
全員分集まったんでちっと修正してPRだしました。PRしたブランチはコミットをまとめてますが、.bkブランチをsho-h/rubima以下に置いてあるので履歴は追える状態。

**Comment by amidaku** [comment]
@sho-h バタバタしてメンションに気がつかなかった！ゴメンナサイ。
短縮URLって意味でした？

**Comment by sho-h** [comment]
@amidaku そんな感じです。例えばでしたけど、クエリパラメータがもっと短いとかあればと思いましたが、後で07の時と比較して同じだったので出しちゃいました。

**Comment by amidaku** [comment]
@sho-h 了解です。
再生リストについては公式な短縮URLは無さそう。（一つ一つの動画にはあるのにね）
